### ISSUE TITLE
search it 6.3. indexiert keine htpassword geschützten Artikel

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/search_it#100]
bei der neuen 6.3. version kann man ja die Art und Weise der Indexierung nicht mehr auswählen - seitdem werden keine treffer in den artikel mehr ausgegben nur in den tabellen. 

im anderen testsystem wo noch das addon 6.1.5 läuft und als Indexierung 
"Artikel-Inhalte (CACHE) : Indexierung der Artikel ohne Template" eingestellt ist funktionierts - kommen auch artikel Treffer. 
Mit den anderen beiden indexierungseinstellungen "HTTP-GET : Indexierung der Artikel über eine HTTP-GET-Anfrage" und "Komplette Seiten (CACHE) : Indexierung der Artikel mit Template" gehts auch hier nicht - keine Treffer bei den Artikel

**Comment by tyrant88** [comment]
Das würde nahelegen, dass in deinem Template etwas eingebaut ist, was einen Fehler beim Indexieren produziert. 
Steht denn in einem solchen Fall etwas im REDAXO-System-Log?
Was wird denn als Status bei der schrittweisen Indexierung ausgegeben?
Die search it Index-Tabelle enthält keine Einträge für die Artikel oder leere Spalten beim Inhalt?

**Comment by fitzliputz** [comment]
Ich weiß nicht, ob ich dasselbe Problem habe, weil ich das AddOn erstmals benutze (6.3 m. Redaxo 5.3.0, PHP 7.0.14, MySQL 5.5.52). Jedenfalls wird klaglos indiziert (schrittweise oder am Stück) aber der Index in der DB enthält keinerlei Inhalt in den Spalten plaintext, unchangedtext, teaser und values. Ich kann als erweiterte Quelle z. B. die values von rex_article_slice angeben, was mir allerdings sinnlos erscheint, weil Artikel im Grunde ja vorwiegend aus slices bestehen. Immerhin wird deren Inhalt indiziert, bei der Ausgabe erhalte ich dann aber die Meldung 'Das Suchergebnis vom Typ db_column kann nicht dargestellt werden.'

Ich finde es eigentlich große Klasse, wie das AddOn aufgebaut und dokumentiert ist und wrde es sehr gerne benutzen – nur ein Suchergebnis sollte halt schon zu erzeugen sein ;-)

Grüße
Ralf

**Comment by alexplusde** [comment]
@fitzliputz kannst du übergangsweise das Addon deinstallieren und die Vorgängerversion aus dem Installer verwenden?

**Comment by fitzliputz** [comment]
**@alexplusde** Okay, ich habe jetzt 6.1.5 installiert, das Ergebnis ist leider unverändert. Der Index zieht  zwar alle Artikel  in die Tabelle, die besagten Spalten bleiben aber nach wie vor leer.

**Comment by tyrant88** [comment]
steht denn was im REDAXO Syslog?

**Comment by fitzliputz** [comment]
**@tyrant88** Nein, der ist auch leer. (Leere scheint heute mein Thema zu sein.)

**Comment by tyrant88** [comment]
kannst du mal eine deiner Seiten aufrufen und in der URL dann `?search_it_build_index=1` anhängen, dann im Quellcode schauen, was alles/ob etwas zwischen den search it Tags liegt ` <!-- search_it  -->`

**Comment by fitzliputz** [comment]
Habe ich gemacht – IRGENDEINE Seite, korrekt? Im Quelltext erscheint nichts, keine search_it tags und auch sonst nichts mit search_it. Leere, ich sag’s ja.

**Comment by tyrant88** [comment]
ach so, sorry war ja Blödsinn, du hattest ja auf 6.1.5 zurückgewechselt... da gab es das noch nicht...

**Comment by fitzliputz** [comment]
Gibt es noch etwas, das ich probieren könnte oder soll ich das AddOn vorläufig lieber abschreiben und eine andere Lösung suchen?

**Comment by steri-rex** [comment]
hast du bei version 6.1.5 schon mal versucht diese einstellung zu machen?
"Artikel-Inhalte (CACHE) : Indexierung der Artikel ohne Template"
ev. musst du dann nochmal eine vollständige indexierung machen und den index cache bzw. keywords löschen

**Comment by fitzliputz** [comment]
Bingo – jetzt tut’s. Meinethalben könnte das so bleiben, die Templates enthalten eigentlich nichts Suchrelevantes und den Vorteil der HTTP-Indexierung gegenüber dem Cache kann ich auch nicht erkennen. Oder gibt es da doch was zu berücksichtigen? Und läuft die Autoindexierung auch mit dieser Einstellung? Das ist für Kundenprojekte natürlich wichtig, weil die keinen Addon-Zugriff haben werden. Auf jeden Fall danke schon mal.

**Comment by tyrant88** [comment]
Ah, also ein HTTP-Problem gewesen in 6.1.5. ! Aber du hattest ja mit der 6.3. auch das Problem: da muss ich noch mal schauen, dass eine Fehlermeldung kommt...
Ja, die automatische Reindexierung nimmt die eingestellte Indexierungsmethode.
Eine Alternative zur automatischen Reindexierung ist immer ein cronjob (falls es Performance Probleme gibt oder ähnliches)

**Comment by steri-rex** [comment]
kann es sein, dass die indexierung über http nicht funktioniert wenn ein htacces passwort/benutzer gesetzt ist?

**Comment by fitzliputz** [comment]
**@steri-rex** Extrem guter Einfall, auf den ich auch selber hätte kommen können. Tatsächlich ist bei meinem besagten Projekt ein PW-Schutz eingerichtet – wenn ich den rausnehme, funktioniert die http-Indexierung zumindest mit 6.1.5. Ich hole mir jetzt nochmal die neueste Version und teste auch die noch.

**Comment by fitzliputz** [comment]
Ok, 6.3.0 tut auch – super und nochmal vielen Dank für die Hilfe!

**@tyrant88** Aus Benutzersicht würde ich zustimmen, dass es mit einer Fehlermeldung getan wäre. Das Problem ist ja eigentlich gar kein echtes, man kapiert nur nicht, was  überhaupt passiert, weil das Indexieren läuft, nur eben unvollständig.

**Comment by tyrant88** [comment]
Eigentlich sollte das im REDAXO Log auftauchen. 
Weil man kann ja nicht unterschieden, wenn 2 Artikel nicht indexiert werden können oder alle...

**Comment by fitzliputz** [comment]
Heute steht es seltsamerweise im Log, gestern tat es das nicht, ich hatte ja extra nachgeschaut (#7 in diesem Thread). Sehr mysteriös. Ich will da jetzt nicht drauf herumreiten, es ist nur irritierend, wenn man indexiert und Erfolgsmeldung sich an Erfolgsmeldung reiht, die maßgeblichen Tabellen aber hartnäckig leerbleiben und keiner kapiert warum. Ich weiß jetzt netterweise Bescheid und kann gut damit leben, könnte mir aber denken, dass es anderen in der Situation ähnlich geht wie mir. Zur Not täte es auch ein Hinweis in der Doku, dass die Indexierung mit PW-Schutz nicht funktionieren wird.

**Comment by tyrant88** [comment]
Da könnte man (und haben wir auch schon) streiten, ob das Nicht-Indexieren von Inhalten, von denen du möchtest, dass sie nur Nutzern mit Kenntnis eines htpasswds zugänglich sind, wirklich ein Fehler ist...

**Comment by fitzliputz** [comment]
Das könnte man in der Tat, muss man aber nicht. Das konkrete Szenario sieht in meinem Fall so aus, dass es das PW während der Entwicklungszeit gibt, später nicht mehr. Der Server steht nicht hier lokal, sondern im Netz, weil mehrere Beteiligte zugreifen sollen. Wichtige Funktionen/Ausgaben erst umzusetzen, wenn der PW-Schutz weg, also die Seite live ist, kann es ja auch nicht sein. Ob dieses Szenario ungewöhnlich ist, kann ich nur schwer beurteilen, bei uns ist es Standard.

**Comment by steri-rex** [comment]
ich denke dass dieses Entwickler Szenario nicht ungewöhnlich ist - gerade in der zeit wo die Webseiten Betreiber mit inhalten befüllen ist ein vorübergehender passwortschutz sehr hilfreich - ich denke auch dass im falle ein hinweis in der doku reichen würde

**Comment by alexplusde** [comment]
Kann man den HTTP-Status nicht bei der schrittweisen Indexierung und vielleicht beim vollständigen Indexieren / beim Cronjob zumindest von der Startseite ausgeben?

**Comment by tyrant88** [comment]
Das schrittweise Indexieren sollte eigentlich eine passende Meldung ausspucken, da muss ich noch mal nach schauen.

**Comment by Hirbod** [comment]
Das AddOn sollte auch settings für den auth-basic Dialog anbieten, damit der Index per GET auch bei geschützten Seiten funktioniert. Da search_it die Sockets nutzt, ist der Aufruf die ServerIP des Servers. Per htaccess oder nginx conf konnte ich dann mittels Satisfy any (nginx) und Satisfy all (Apache) die IP Adresse freigeben, wodurch ein Zugriff ohne auth-basic dialog möglich war.

Das ist dennoch für den unerfahrenen Anwender schwer umzusetzen. Es sollten Username und Passwortfeld für auth-basic eingebaut werden. Die Redaxo-Socket Class unterstützt auch das Übergeben von Username und PW an AUTH

**Comment by alexplusde** [comment]
@Hirbod kannst du einen PR dazu machen? 2 zusätzliche Eingabefelder in den Einstellungen bei der Indexierung in einem eigenen Section-Block + die Übergabe dieser Anmeldedaten in der passenden Klasse? (Wenn es bei dir hoffentlich wieder etwas weniger stressig ist)

**Comment by Hirbod** [comment]
Mir ist eben eingefallen, dass man das auch anders machen kann. Die Auth-Daten stehen in den PHP Superglobals. Man könnte die mit durchschleifen. Würde dann aber nur funktionieren, wenn ein Admin aus dem Backend eingeloggt ist und die Reindizierung nicht z.B. durch einen Cronjob ausgeführt wurde.

Ich glaube aber, dass es meistens eh nur im Backend getriggered wird. Wenn wir uns hier auf einen Weg einigen können, kann ich eine Variante ohne zusätzliche Eingabefelder umsetzen.

**Comment by Hirbod** [comment]
PR is there #134

**Comment by tyrant88** [comment]
Ich hab es jetzt oldschool umgesetzt. Zwei Felder im Backend. Hirbod hat mit ja auf die Method gestupst, damit war es ja einfach (plus 3 Stunden es schön machen :-) Da war ich im Tunnel und hab gar nichts mitbekommen.

**Comment by Hirbod** [comment]
Ich find die Lösung trotzdem falsch, da die auth-basic Daten jetzt im Klartext gespeichert werden. Auf die $_SERVER zuzugreifen macht das ganze "Out of the box" ready, es werden keine Passwörter im Klartext gespeichert und der User muss nix konfigurieren.

**Comment by alexplusde** [comment]
@tyrant88 das mit dem Klartext wurde gefixt, oder? @Hirbod wie schaut's da aus, ist die Umsetzung mit deinem Vorschlag noch gewünscht?

**Comment by Hirbod** [comment]
@alexplusde ich bin nach wie vor noch der meinung man sollte ggf einen ansatz aus beiden punkten umsetzen (würde dann out of the box ohne config funktionieren) und falls man echte scripts nutzen will, die direkt ansurfen, daten eingeben.

**Comment by tyrant88** [comment]
Ja, das mit dem Klartext hat sich durch das neue "Eye"-Feld erledigt.

**Comment by alexplusde** [comment]
Noch ein Beispiel mit Indexierungsproblemen aus Slack: Installation innerhalb von MAMP, Socket-Verbindung lässt sich nicht aufbauen.

**Comment by alexplusde** [comment]
das urspr. Issue wurde behandelt.
