### ISSUE TITLE
Indexierung langer tags

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/search_it#101]
Wir haben hier eine Seite, bei der Bilder aus yfeed als Inlineimages direkt im html ausgegeben werden. Dabei werden die Bildinhalte mit indexiert und teilweise Schneppsel in den Ergebnissen mit ausgegeben. Außerdem wird die rex_search_cache ziemlich groß.
Lg, Wolfgang

**Comment by alexplusde** [comment]
In der Modulausgabe das Element gesondert markieren (z.B. über eine Klasse) und dann mit dem Plaintext-Plugin von der Indexireung ausschließen.

https://github.com/FriendsOfREDAXO/search_it/blob/master/plugins/documentation/docs/de_de/howto-setup.md#module-blöcke-artikel-oder-bestimmte-abschnitte-filtern
