### ISSUE TITLE
negativ-Tags um Bereiche einer Webseite von der Suche auszuschliessen

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/search_it#102]

**Comment by alexplusde** [comment]
https://github.com/FriendsOfREDAXO/search_it/blob/master/plugins/documentation/docs/de_de/howto-setup.md#module-blöcke-artikel-oder-bestimmte-abschnitte-filtern

**Comment by tyrant88** [comment]
*Phh* hätte ich trotzdem gerne umgesetzt...

**Comment by alexplusde** [comment]
Würde es sich vlt. anbieten, diese "Plaintext"-Funktion in dem Zuge aufzuwerten und besser zu erklären? Dass diese keine separate Funktion ist, sondern immer durchlaufen wird und eben mit einem Wert vorbelegt wird?

**Comment by tyrant88** [comment]
keine schlechte Idee!

**Comment by alexplusde** [comment]
https://github.com/FriendsOfREDAXO/search_it/issues/103
