### ISSUE TITLE
Plaintext-Plugin überarbeiten

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#103]
- Soll Plaintext fortan grundsätzlich verwendet werden statt zweier Methoden? (und ist das aktuell noch so?)
- Wie nennen wir Plaintext weniger technisch? (Textverarbeitung, zusätzliche Indexierungseinstellungen, Filter, Vorbehandlung)
- Brauchen wir die Sortierfunktion der einzelnen Features?
- Brauchen wir die Features wie Textile parsen, HTML-Tags entfernen überhaupt? Könnte man nicht stattdessen auch einen EP machen, der sich da einhängt?
- Eine JS-Vorschau wäre stark, in die man Quellcode reinkopieren kann und dann vom Server angezeigt bekommt, wie search_it diesen Text für die DB verändert. 

Das wären für mich so Fragen...

/cc @xong @tyrant88 @olien (du hast das doch sicher schon ein paar Mal benutzt) @Hirbod (Du hast auch oft gute Vorschläge parat)

**Comment by xong** [comment]
Also das Plaintext-Plugin ist für mich sehr wichtig. Damit kann man seinen Index sehr genau auch an spezielle Bedürfnisse anpassen. Und dafür sind alle Sachen wichtig, die jetzt schon drin sind: Sortierfunktion, Textile parsen, strip_tags.
Und mit Hilfe von CSS-Selektoren kann man ja sogar ganze Bereiche ausschließen. Da braucht´s auch keine Auschluss-Tags, weil man ja auch einfach eine CSS-Klasse `.noindex` verwenden könnte.
Und wer unbedingt mit solchen Tags arbeiten muss/möchte, kann sich einfach einen Regex basteln, der diese dann rausfiltert.

Desweiteren läuft das Plaintext-Plugin schon über den EP `SEARCH_IT_PLAINTEXT`. Und das sollte auch so beibehalten werden.
Für mich war damals ausschlaggebend das als Plugin umzusetzen, weil die Plaintextverarbeitung des Plugins sehr rechenintensiv war und meistens sowieso die Standardkonvertierung von RexSearch ausreichte. Tatsächlich hab ich das Plugin bei all meinen Suchen aber aktiviert. Allein schon, damit ich den <head>-Bereich und <script>-Bereiche ausschließen konnte.

**Comment by olien** [comment]
Ich habe das Plaintext-Plugin immer benutzt!

**Comment by tyrant88** [comment]
Ich bin erst im Juni wieder ansprechbar...

**Comment by tyrant88** [comment]
Hier bin ich voll xongs Meinung. Das plugin bleibt so wie es ist.

**Comment by alexplusde** [comment]
Einverstanden. Mittlerweile ist mir die Funktionsweise dieses Plugins auch vertrauter.

**Comment by xong** [comment]
Ich weiß nicht, ob das brandaktuell gebraucht wird, aber für spätere Versionen des Plugins wäre es schön, wenn man unterschiedliche Filterregeln für jeden Datenquellentyp einstellen könnte. Falls also sowieso mal was dran gemacht werden muss, wäre das ein schönes Feature.

**Comment by alexplusde** [comment]
@xong Ich finde es toll, dass du noch aktiv bist hier. Sieht man sich auch wieder am Redaxo-Tag?

**Comment by xong** [comment]
Prinzipiell hab ich schon Lust, aber der letzte hat zeitlich nicht gepasst und war mir auch zu teuer. Außerdem hab ich jetzt tatsächlich eine Festanstellung angenommen, so dass ich Redaxo nur noch selten verwenden kann. Ich verfolge die Community und Entwicklungen natürlich weiter und freue mich, dass es so gut läuft.
