### ISSUE TITLE
Indizierung im Zusammenspiel mit YRewrite bleibt auf Hauptdomain beschränkt

### ISSUE THREAD

**Issue by maxsmily** [FriendsOfREDAXO/search_it#104]
Die Funktion indexArticle in class search_it erzeugt die Scanurl unter Verwendung von rex::getServer(). Bei YRewrite-Urls werden so doppelte Domainnamen zusammengestellt, da rex_getUrl() hier den Domainnamen bereits mitliefert.

Dadurch können die Artikel der Nebendomains nicht richtig für die Indizierung aufgerufen werden.

Die falsch generierten Urls siehen ungefähr so aus: http://www1.example.com/http://www2.example.com/foo.html?search_it_build_index=do+it%2C+baby

Mein aktueller Workarround:

`$scanurl = str_replace(array('../', './'), '', rex_getUrl($_id, $langID,array('search_it_build_index'=>'do it, baby'),'&'));
if(strpos($scanurl, 'http://')===false && strpos($scanurl, 'https://')===false){
    $scanurl = rtrim(rex::getServer(), "/") . '/' . $scanurl;
}`

**Comment by palber** [comment]
Hatte das selbe Problem, habe es aber anderes gelöst, das es bei mir so leider auch nicht immer zu 100% funktionierte - siehe PR #105

**Comment by dtpop** [comment]
Bei mir hat der Patch ausgzeichnet funktioniert - wir hatten das gleiche Problem. Dabei wurden zwar die Seiten in den Index aufgenommen, allerdings mit leerem Inhalt. Nach dem Patch war das Problem behoben. Ich empfehle den Patch zu übernehmen.

**Comment by tyrant88** [comment]
Das sollte jetzt erledigt sein.
