### ISSUE TITLE
Artikelindexierung mit YRewrite funktioniert nicht

### ISSUE THREAD

**Issue by MarshallGibson** [FriendsOfREDAXO/search_it#107]
Bei installiertem YRewrite Addon, werden Artikel zwar indexiert, aber die Spalten plaintext, unchangedtext und teaser bleiben leer, da die Scanurl (search_it.php Zeile 223) bereits mit rex_getUrl() den Absoluten Pfad erhält und somit die Änderung von relativen auf absoluten Pfad nicht mehr notwendig ist.

Meine Lösung:
if(rex_addon::get('yrewrite')->isAvailable()){
                            $scanurl = rex_getUrl($_id, $langID,array('search_it_build_index'=>'do it, baby'));
                        }else{
                            $scanurl = rtrim(rex::getServer(), "/") . '/' . str_replace(array('../', './'), '', rex_getUrl($_id, $langID,array('search_it_build_index'=>'do it, baby'),'&'));
                        }

lg,
Thomas

**Comment by alexplusde** [comment]
https://github.com/FriendsOfREDAXO/search_it/pull/105

**Comment by MarshallGibson** [comment]
Oh! Haha, ok, wer suchen kann ist klar im Vorteil.

Danke! ;D

**Comment by alexplusde** [comment]
Gern geschehen. Wie kommst du insg. mit `search it` zurecht?

**Comment by MarshallGibson** [comment]
Ja doch, danke! Abgesehen vom grundlegenden herausfinden wo sich jetzt was genau befindet.
Schaut ja im vergleich zur Version fürs 4er etwas anders aus ;D

**Comment by alexplusde** [comment]
@MarshallGibson hat dir die Doku denn dabei geholfen oder könnten wir da was verbessern?
