### ISSUE TITLE
Fehlende Indexierungstypen

### ISSUE THREAD

**Issue by xong** [FriendsOfREDAXO/search_it#108]
Hi,
warum sind denn die unterschiedlichen Indexierungstypen (mit/ohne Template, per HTTP-Request) rausgefallen.
Ich habe das gebraucht, um auch Artikel indexieren zu können, die im Template keine Ausgabe haben. Kann man das wieder einbauen?

**Comment by tyrant88** [comment]
Mit diesem Themenkomplex wird sich die nächste Version endgültig beschäftigen.

**Comment by alexplusde** [comment]
Siehe auch: https://github.com/FriendsOfREDAXO/search_it/issues/100

**Comment by alexplusde** [comment]
Was ist daraus geworden? Sollen die Indexierungstypen wieder aufgenommen werden?

**Comment by tyrant88** [comment]
Ich kann es mir nur so vorstellen, dass es eine zusätzliche Option gibt, die alles in der DB indexiert, aber auch nicht behauptet eine Seitensuche zu sein. Halt so wie xong das einsetzt, aber sich dann selbst um die Ausgabe kümmert.
