### ISSUE TITLE
ForumPost:: Leerer Index

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/search_it#111]
https://redaxo.org/forum/addons-packages-r5-f43/search-it-leerer-index-t21784.html#p121914

**Comment by tyrant88** [comment]
Danke Thomas, im Forum hätte ich das übersehen!
Und danke dank an Gerry aus dem Forum.

**Comment by rkemmere** [comment]
Hi, wir haben auch mit der Masterversion den gleichen Fehler. Der Index in der DB ist trotz erneuern immer leer. Neuinstallation brachte auch nichts. 

REDAXO 5.3.0
PHP 7.0.20-nmm1 und auch mit PHP 5.6 getestet. Indextartikel IDs sind angelegt, aber keine Inhalte unter plaintext usw.

Wir kriegen wir das behoben?

**Comment by tyrant88** [comment]
Habt ihr mal die github Version eingespielt? Es sollte jetzt behoben sein...

**Comment by rkemmere** [comment]
Das Problem war das die Seite auf einem Entwicklungsserver mit htaccess Schutz lief und die Suche seit Version 6.3 nur noch die GET Abfrage über HTTP auf die Seite macht.

htaccess Schutz entfernt und dann klappt es auf allen Instanzen.

Vielleicht sollte die Auswahl nach dem Indexmodus doch wieder mit aufgenommen werden?

**Comment by rkemmere** [comment]
Wir haben jetzt auch rausgefunden warum es auf manchen Systemen geht und auf anderen nicht. 
Zur Info auf allen unseren Livesystemen ging es nicht. 

Wenn man HTML Kommentare aus dem Quelltext entfernt: mit Minify oder auch per PHP Funktion, was bei einer produktiven Seite ja Sinn macht. Klappt die Suche eben nicht mehr.

In Zeile 263 wird eben genau dieser HTML Kommentar als Pattern definiert. 

https://github.com/FriendsOfREDAXO/search_it/blob/master/lib/search_it.php#L263

Sinnvoller wäre ein dieser Stelle eine DIV oder ähnliches einzufügen und eben kein HTML Kommentar.

**Comment by tyrant88** [comment]
Naja, ein HTML-Element ist da aus Puristen-Sicht nicht das Richtige... vielleicht eher ein Attribut - aber dann müsste es doch ein Element geben was alles umschließt...
Wieso man HTML-Kommentare rausfiltert erschließt sich mir auch nicht, aber ich mach mir auf jeden Fall mehr Gedanken dazu.
Auf jeden Fall danke Ronny!

**Comment by alexplusde** [comment]
HTML-Kommentare auszufiltern macht man, wenn man jedes Byte, das zum Client übertragen wird, effektiv einsetzen will - oder, weil man eben Teile der Ausgabe im Moment behalten möchte, jedoch nicht aktuell. Ob es best practice sein sollte, sei dahingestellt.

Riskant fände ich, ein Element einzubauen, wenn man im CSS Regeln wie `e > *` benutzt.

**Comment by rkemmere** [comment]
Eine Möglichkeit wäre bei dem Search Index ebenfalls einen conditional comment zu setzen.
Anschließend muss man nur noch das minify umstellen, da das aktuell die conditional comments auch entfernt. Was aber aus meiner Sicht ein Bug ist, weil ich diese ja explizit verwenden möchte.

Beispielsweise so

**Comment by skerbis** [comment]
@tyrant88 ich habe mir den Code von searchit jetzt nicht angeschaut, aber es macht doch eine httpget-Anfrage, kann man nicht einen Client-Header (gerne individuell) senden, auf den man dann in den Templates reagieren - könnte? Dann bräuchte man keinen zusätzlichen (sichtbaren) Code in der Ausgabe für das crawlen. 
Man fragt dann einfach ab, welcher Client gerade die Website abruft und blendet, die ungewünschten Inhalte aus oder sendet nur die erforderlichen an den Crawler. 

Zudem könnte man so sogar die ycom-Authentifiezierung umgehen und ggf. auch interne Dinge crawlen.

**Comment by rkemmere** [comment]
Generell kann man doch eigentlich auch einfach den Text im Body parsen. Zwischen <body und </body>

**Comment by tyrant88** [comment]
@rkemmere es geht hauptsächlich darum, nur den content zu erwischen...
@skerbis die HTML-Kommentare werden schon jetzt nur beim Indexieren in die Ausgabe eingesetzt. Da ist nichts sichtbar, darauf habe ich schon geachtet. Theoretisch könntest du auf den URL-Parameter "search_it_build_index" reagieren...
Die Idee hatte ich ja anders herum, wenn du außer dem Artikel-content Inhalte produzierst, kannst du die mit '<search_it>-Tags markieren, damit sie auch indexiert werden...
Wegen der Authentifizierung: Da bin ich immer noch an einer Lösung, die über die API läuft und alle Umwege überflüssig macht...
