### ISSUE TITLE
der Seach It-Highlighter killt den Body-Tag in der Ausgabe der gefundenen Seite

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/search_it#113]
https://redaxo.org/forum/addons-packages-r5-f43/search_it-highlighter-killt-body-tag-geloest-t21879.html

**Comment by tyrant88** [comment]
Hab geantwortet, ich fixe es bei Gelegenheit.
Danke Oli für die Benachrichtigung.

**Comment by tbaddade** [comment]
> Hab geantwortet, ich fixe es bei Gelegenheit.

Was hast du geantwortet? Passiert hier auch :)

**Comment by tyrant88** [comment]
fixed, thx to frood aus dem Forum
