### ISSUE TITLE
Datenbankspalten auswählen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/search_it#115]
- Checkboxen können sich überlagern
- schlechte Lesbarkeit

Vorschlag:
Checkboxen untereinander setzen.

**Comment by tyrant88** [comment]
Vorschlag: zwei Spalten, statt 4

**Comment by alexplusde** [comment]
multiselect wäre auch möglich gewesen.

**Comment by tbaddade** [comment]
schlechte Lesbarkeit ist immer noch vorhanden.

**Comment by alexplusde** [comment]
@tbaddade wie sieht's denn bei dir aus in der neuen Version? Hast du so lange Feldnamen?

**Comment by tyrant88** [comment]
sonst hätte er es ja nicht gepostet...

**Comment by tbaddade** [comment]
Ich finde es wählt sich leichter aus, wenn das alles untereinander steht. Man findet dadurch einfach schnelle die Spalten und muss nicht links rechts suchen und klicken. Das Multiselect wäre auch eine Option, wobei einmal falsch geklickt alle anderen Optionen weg wären.

**Comment by skerbis** [comment]
@tyrant88  Wenn man das Multiselect von Bootstrap-Select nimmt ist es auch übersichtlich und das Problem von @tbaddade tritt nicht auf
![bildschirmfoto 2017-09-11 um 12 48 42](https://user-images.githubusercontent.com/791247/30271167-8e7e00b0-96ef-11e7-9c77-f375e1af5694.png)

**Comment by tyrant88** [comment]
Ja multiselect war mir auch zu "fummelig".
Das @skerbis schau ich mir mal an.

**Comment by skerbis** [comment]
@tyrant88 
`<select class="selectpicker" multiple>
  <option>Mustard</option>
  <option>Ketchup</option>
  <option>Relish</option>
</select>
`

**Comment by tbaddade** [comment]
Fände es noch gut, wenn die Spalten alphabetisch gelistet würden.

**Comment by tyrant88** [comment]
Da finde ich es eigentlich besser, wenn sie so sind wie in der DB.

**Comment by tbaddade** [comment]
> Da finde ich es eigentlich besser, wenn sie so sind wie in der DB.
Ist doch uninteressant wie die angelegt sind. Sind diese alphabetisch und untereinander kannst die schneller auswählen.

**Comment by tyrant88** [comment]
Finde ich nicht. Ich lege meine Spalten in einer gewissen Reihenfolge an. Andere vielleicht auch, warum sollte ich das übersteuern?

**Comment by tbaddade** [comment]
> Ich lege meine Spalten in einer gewissen Reihenfolge an. 

Das macht YForm von ganz allein und die Spalten werden nach einandern in der DB angelegt. Die Anzeige/Reihenfolge im Backend unterscheidet sich dazu wieder gänzlich.

Wenn du das nicht sinnvoll findest schließe einfach das Issue bitte.

**Comment by tyrant88** [comment]
Es geht ja nicht nur um unsere beiden Meinungen.

**Comment by schuer** [comment]
+1 für alphabetische Sortierung, wenn hier um Meinungen gefragt wird.

**Comment by alexplusde** [comment]
+1 für alphabetische Sortierung, weil in der Tat unterscheidet sich die Reihenfolge im Table Manager von den tatsächlichen Feldern in der db.

**Comment by tyrant88** [comment]
es wird sortiert und auch nur noch eine Spalte

**Comment by alexplusde** [comment]
Grundsätzlich habe ich das in #275 berücksichtigt:

![image](https://user-images.githubusercontent.com/3855487/79748082-1a765e80-830d-11ea-9419-1a560bfb6744.png)

Die Eingabe wäre mit einem Bootstrap Selectpicker nun schneller und es ist direkt ersichtlich, welche Felder ausgewählt wurden.

Man könnte jedoch immer noch Tabellen standardmäßig ausblenden

**Comment by tyrant88** [comment]
auch nice
