### ISSUE TITLE
Beinflussung von Styles in anderen Addons

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/search_it#118]
Hier die Selects bei "Aufgaben"

Mit Search_it
![pasted image at 2017_09_06 12_10 pm](https://user-images.githubusercontent.com/330516/30107048-e55afbc2-92fd-11e7-91c6-b173694ee871.png)

Ohne Search_it
![pasted image at 2017_09_06 12_10 pm 1](https://user-images.githubusercontent.com/330516/30107078-ff1f78e4-92fd-11e7-9534-f9e1877ca493.png)

**Comment by skerbis** [comment]
@lus @oliver_kreischer schuld ist die css-class .placeholder in search_it.css Zeile 177 ...

**Comment by alexplusde** [comment]
Sollte die CSS-Datei nicht ohnehin nur innerhalb von search_it geladen werden?

**Comment by skerbis** [comment]
Entweder so, oder sich nur auf einen Container beziehen

**Comment by tyrant88** [comment]
Ich mach jetzt beides.
Die anderen AddOns sollten auch umgebaut werden, dass sie css und js nur auf ihren eigenen Backendseiten geladen werden... Außer so Sachen wie QuickNavigation... ;-)
