### ISSUE TITLE
Zusätzliche Datenquelle

### ISSUE THREAD

**Issue by loesungsmittel** [FriendsOfREDAXO/search_it#119]
Wir haben eine per yform erstellte Tabelle, die von search_it berücksichtigt werden soll. In den Einstellungen wurde die ID der Tabelle und Text-Datenfelder mit eingezogen.   

Bei den indexierungeinstellungen sind aktiv:
x Artikel (ADD, EDIT, DELETE) automatisch (de)indexieren
x Reindexieren aller Spalten, wenn Tabellen mit YForm oder form bearbeitet werden

Beim Speichern eines Eintrages der Tabelle über die Tabellenverwaltung in Redaxo erscheint folgender Fehler:

`"ErrorException" thrown in /mnt/web007/e0/34/54167834/htdocs/ecomai/redaxo/src/addons/search_it/functions/functions_search_it.php on line 757
Fatal error: Call to a member function getTableName() on null`

REDAXO 5.2.0
PHP 5.6.31 
MySQL 5.6.37-log
yform 1.0
search_it 6.3.0

**Comment by tyrant88** [comment]
Vielleicht liegt es an der etwas alten Version von YFORM, die du nutzt (1.0).  Das kann ich gerade schlecht überprüfen...

**Comment by alexplusde** [comment]
Hallo @loesungsmittel, habe gerade gesehen, dass das dein erstes Issue hier ist. Vielen Dank dafür! Bist du denn auch im Redaxo Slack-Channel?

**Comment by tyrant88** [comment]
Kam nichts mehr, deshalb zu.

**Comment by alexplusde** [comment]
@loesungsmittel lass uns wissen, wenn es hierzu noch Probleme gibt. Im übrigen brauchst du nicht die ID indexieren, wenn du keine Suche der ID-Werte willst, Die ID wird dir automatisch beim Treffer mitgegeben.

**Comment by loesungsmittel** [comment]
Vielen Dank für die Antworten. Wir haben bei dem Projekt Probleme mit dem Updaten, vermutlich weil wir da teilweise Beta-Versionen im Projekt haben. Deswegen sind wir da nicht weitergekommen.
