### ISSUE TITLE
Test-Suchbegriffe landen in der Statistik

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/search_it#122]
Die in der Testsuche eingegebenen Begriffe landen stets in der Statistik.
Ggf. wäre ein Parameter interessant, mittels dessen man selbst festlegen kann, ob Test-Suchbegriffe in die Statistik aufgenommen werden sollen; insb. dann, wenn man Test-Suchen auf einem Live-System durchführt.

**Comment by alexplusde** [comment]
@tyrant88 fände ich sinnvoll, denn es kann auch sein, dass man die Keywords für die Ähnlichkeitssuche vorbefüllen will, aber das nicht in die Nutzungsauswertung rein soll. 

Während der Entwicklung ist es ja egal, da kann man die Statistik ggf. zurücksetzen.

**Comment by tyrant88** [comment]
Einverstanden, ich sprech mal mit dem, der dieses feature eingebaut hat... ;-)

**Comment by tyrant88** [comment]
Der Cache muss auch ausgeschaltet werden...

**Comment by tyrant88** [comment]
siehst du @alexplusde , was das alles nach sich zieht...? :-)

**Comment by alexplusde** [comment]
Haja, im Frontend zu testen war ja vorher auch nicht anders. Das seh ich gelassen :)

**Comment by alexwenz** [comment]
Da hatter nicht unrecht, der Herr Plus. Konsequenterweise könnte man eingeloggte Backendnutzer vom Statistizieren in Front- und Backend ausnehmen...

**Comment by tyrant88** [comment]
Ja, das kriegt der Herr Plus locker hin...

**Comment by alexplusde** [comment]
Der @tyrant88 (oder irgendwer) baut mir einen Schalter in die Klasse ein (`normal / in statistik + keywordindex`, `nur keywordindex`, `ohne`) ich füg das ganze in die Beispiele und die Testseite ein ;)

**Comment by tyrant88** [comment]
Noch mehr Schalter? *würg* Ich tendiere mehr zu @alexwenz Vorschlag

**Comment by alexplusde** [comment]
Habe ihn nicht aufmerksam genug gelesen und hiermit nachgeholt :)

**Comment by tyrant88** [comment]
teste jetzt doch nur auf den "search_it_test_keywords" Parameter.

**Comment by alexplusde** [comment]
Praktisch. Danke.
