### ISSUE TITLE
Examples are still using OO-style

### ISSUE THREAD

**Issue by DavidBruchmann** [FriendsOfREDAXO/search_it#126]
see #125

**Comment by tyrant88** [comment]
oder war da noch mehr? @alexplusde kannst du mal schauen?

**Comment by alexplusde** [comment]
Wie beschrieben: Ein Teil der Doku ist noch offen. Da ich search_it demnächst wieder einsetzen werde, werde ich mich nochmal damit auseinander setzen - außer jemand ist schneller.

**Comment by alexplusde** [comment]
Wurde das gefixt?

**Comment by tyrant88** [comment]
Ja, konnte kein OO mehr finden. Und dass du die Doku verbessern willst ist auch klar :-)

**Comment by alexplusde** [comment]
Gut, muss an mir vorbei gegangen sein, dass das korrigiert wurde :)
