### ISSUE TITLE
YForm - Relationstabellen nicht mit auflisten

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/search_it#127]

**Comment by tyrant88** [comment]
lass mich raten, du hast viele davon? :-)
Hilf mir gleich: Was macht eine Tabelle zur Relationstabelle?

**Comment by tbaddade** [comment]
> Was macht eine Tabelle zur Relationstabelle?

Das versteht man am besten am Beispiel in der Doku
https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/table_manager_feldtypen_be-manager-relation.md

**Comment by tyrant88** [comment]
:-) Anders ausgedrückt ein: "if ( thomassagtesisteinerelationtabelle($table) == true ) " beschleunigt die Implementierung

**Comment by tyrant88** [comment]
Da es kein einfaches Kriterium gibt, scheint mir der Aufwand nicht gerechtfertigt. 
Zumal auch sonst jede Tabelle (außer den Search it-eigenen) angezeigt wird, ob es Sinn macht oder nicht.
