### ISSUE TITLE
Datenbankspalten vorselektieren und Tabellen kenntlich machen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/search_it#128]
Zur besseren Übersicht könnte man die Checkboxen anhakeln, die auch initial durchsucht werden (Bsp. die Spalten in `rex_article`).

Außerdem fände ich gut, dass nur die Tabellen grün angezeigt werden, wo auch Checkboxen ausgewählt wurden. Alle anderen Panels könnten als `panel-default` ausgegeben werden.

**Comment by tyrant88** [comment]
Das ist ein Mißverständnis: da werden keine Spalten durchsucht.
Initial wird nur das auf der Frontendseite angezeigte, von einem article content Ausgegebene indexiert.
Die Spalten baucht man für Artikel nur, wenn Werte suchbar sein sollen, die nicht angezeigt werden.

**Comment by alexplusde** [comment]
Genau, Spalten in rex_article sollten nur zusätzlich indexiert werden, wenn sie Meta-Angaben enthalten, die nicht im Frontend ausgegeben werden. es handelt sich dann um einen Datenbanktreffer und keinen Artikeltreffer, wodurch ggf. ein Artikel doppelt in den Suchergebnissen auftauchen kann.

**Comment by tbaddade** [comment]
> Genau, Spalten in rex_article sollten nur zusätzlich indexiert werden, wenn sie Meta-Angaben enthalten, die nicht im Frontend ausgegeben werden.

Sollten dann die restlichen Spalten dann nicht versteckt werden?

**Comment by alexplusde** [comment]
Kommt eben au fden Anwendungsfall an @tbaddade

**Comment by tyrant88** [comment]
Ab jetzt werden nur ausgewählte Tabellen grün angezeigt. 
Der Rest des Themas belibt wie es ist.
