### ISSUE TITLE
Search it kann nicht mit Silbentrennung &shy; umgehen

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/search_it#130]
**Beispiel:**
Das FOR-AddOn **Hyphenator** _(https://github.com/FriendsOfREDAXO/hyphenator)_ nimmt in Texten durch Einfügen des Trenn-Symbols **&shy** eine Silbentrennung vor:
`echo hyphenator::hyphenate(REX_VALUE[id=1]);`

Dadurch werden dann im Frontend silbengetrennte Wörter ausgegeben.

Da Search it (**Version 6.4.1**) nur noch über das Frontend indexiert, landen dann durch **&shy** die Silben _(anstatt der ganzen Wörter)_ im Suchindex.

**Fazit:**
Search it kann allgemein nicht mit **&shy** umgehen.

Evtl. wäre dies ein Argument, um wieder eine DB-Indexierung zuzulassen...

**Comment by tyrant88** [comment]
Nee das ist nur ein Argument die Worttrenung von search it zu überprüfen.

**Comment by greatif** [comment]
Ok, oder so...

**Comment by tyrant88** [comment]
Genau. Ich gehe davon aus, dass das was im Frontend erscheint (Endergebnis aller Ersetzungen), das ist was gesucht und gezeigt werden soll.

**Comment by xong** [comment]
Siehe Issue #108. RexSearch war noch als reines Indexierungs-Addon gedacht. Das man damit auch eine Fulltextsuche durchführen konnte, war für mich nur ein bestimmter Anwendungsfall.
Ich hatte früher oft den Fall, dass ich nicht nur (Frontend-)Artikel durchsuchen wollte, sondern alle möglichen Datenquellen. Das ist im Moment so leider nicht mehr möglich.

Zum Problem hier: Eventuell kann das Plaintext-Plugin _&shy;_ vor dem Indexieren mittels Regex filtern.

**Comment by tyrant88** [comment]
Worttrennung ging nicht zu ändern, da die die RegEx Klasse [:punc:] (punctation) auf das Semikolon von "&shy;" anspringt...
Xongs Vorschlag macht ja noch mehr Sinn, da eine HTML-Entity eigentlich eh nichts im plaintext zu suchen hat. 
Nur wollte ich nicht, dass ein Normalo erst das plaintext plugin anwerfen muss, weil er Hyphenator benutzt... deshalb wende ich auf den plaintext ein html_entity_decode an... 
Die Spezialisten wiederum können mit dem plaintext plugin das Standard-Verhalten umgehen.

**Comment by greatif** [comment]
Der Normalo hat sich sogar zuerst mit dem Plaintext-Plugin beschäftigt. Leider führt die Hilfe-Seite für das Plugin `/index.php?page=packages&subpage=help&package=search_it/plaintext`, die auf  die Doku im "alten Wiki" verweist, auf einen toten Link. Sprich: Keine Doku verfügbar.
Also wurde "auf gut Glück" versucht, beim Plaintext-Plugin unter "**Reguläre Ausdrücke**" 1. Zeile `'&shy;'` durch 2. Zeile `''` zu ersetzen. Allein dies zeigte keinen Effekt bei der Indexierung.
Wenn die Hilfestellung für eine korrekte Verwendung hier etwas besser wäre, dann wäre es m.E. auch dem Normalo zuzumuten, das Plugin zu nutzen.
Praktikabelste Lösung im Moment: Auf d. Addon Hyphenator verzichten u. via CSS `hyphens: auto;` die Silbentrennung machen.
Konsequenz: Die Frage, ob ein FOR-Hyphenator-Addon Sinn macht?
Fazit: Eine zumindest rudimentäre Doku zum Plaintext-Plugin wäre für den Normalo jedenfalls interessant.

**Comment by tyrant88** [comment]
Du bist doch gar nicht gemeint! :-) 
Genau das Gleiche hab ich auch probiert, die Lösung ist: die zweite Zeile muss eine Leerzeile sein.
Deshalb hab ich auch die Doku angepasst.
Und es ist aber auch nicht mehr nötig, weil ich das &shy; durch html_entity_decode umwandele.

**Comment by alexplusde** [comment]
> Fazit: Eine zumindest rudimentäre Doku zum Plaintext-Plugin wäre für den Normalo jedenfalls interessant.

@greatif was sollte da deines Erachtens drinstehen? Hast du dich in soweit damit beschäftigt, dass du was dazu schreiben kannst?
