### ISSUE TITLE
Installer-Version defekt

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#131]
`Illegal result returned from api-function install_package_update. Expected a instance of rex_api_result but got "NULL".`

**Comment by tyrant88** [comment]
Ich hab leider keine 6.4.0 zum testen mehr, bei 6.3.0 und 6.1.4 hatte ich keine Probleme..
Ich teste bei Gelegnheit noch mal..

**Comment by tyrant88** [comment]
Hab gerade mblock geupdated:
```Illegal result returned from api-function install_package_update. Expected a instance of rex_api_result but got "NULL"```

**Comment by tyrant88** [comment]
Kollege Gregor sagt ist bekannt... wird sich gekümmert

**Comment by tyrant88** [comment]
Es passiert, wenn du ein AddOn aktualisierst und dann einen Reload der Seite machst.

**Comment by alexplusde** [comment]
Danke.
