### ISSUE TITLE
Schrittweise Indexierung - Sprachmischmasch und fehlender Titel

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#137]
```
Done: Article "Website" (ID=27,deutsch)
Article (ID=26,deutsch) Response not ok bei der Indexierung per HTTP-GET
Done: Article "SMV und Gremien" (ID=25,deutsch)
Article (ID=2,deutsch) is excluded
```
Hier (und andernorts) könnte man mal aufräumen und die lang-Dateien in versch. Sprachen über ytraduco pflegen. Außerdem wird bei Blacklist-Artikeln nicht der Artikelname ausgegeben.

**Comment by tyrant88** [comment]
über ytraduco habe ich doch schon pull-requests bekommen, das läuft doch wohl, oder?
Und Aufräumen ist immer gut, macht man aber nur zu gewissen Zeiten.

**Comment by tyrant88** [comment]
Hab es überarbeitet. Die Übersetzungen müssen natürlich von wo anders kommen...

**Comment by alexplusde** [comment]
Klasse, danke.
