### ISSUE TITLE
Schrittweise Indexierung erfolgreich - Nichts gefunden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/search_it#138]
Info: Website mit htaccess-Schutz

**A - Ohne Hinterlegung der htaccess-Daten**
Die Indexierung suggerierte einen Erfolg, da n/n Artikel indexiert wurden. Tatsächlich wurde aber nichts indexiert, zumindest ergab die Suche keinen Treffer. 

**B - Mit den htaccess-Daten** kam ebenfalls der Erfolg von *n/n Artikel*. Nun fand die Suche auch Treffer.

Aus der Doku geht hervor:

> Search it erstellt den Index, in dem es die Artikel der Website im Frontend aufruft und den Artikelinhalt indexiert.

Für mich hätte daher die Indexierung **A** gleich abbrechen müssen, da gar keine Artikel aufgerufen werden konnten. Sinnvoll wäre gar eine Info, dass keine Indexierung ohne den htaccess-Daten möglich ist.

**Comment by tyrant88** [comment]
hier clos, weiter in #139

**Comment by tbaddade** [comment]
> hier clos, weiter in #139

Das sind zwei unterschiedliche Verhalten.

**Comment by tyrant88** [comment]
Ja da hab ich mich irgendwie verguckt...

**Comment by darwin26** [comment]
HI... iwie hab ich das Problem öfter noch und steige nicht durch, was es sein könnte.
- htaccess ist nicht aktiv
search_it findet nur Daten aus den Zusätzlichen Datenquellen. rex_article bleiben leer in der DB:rex_search_it_index ...

lokal funktioniert es (noch) ... aufm Server plötzlich nicht mehr (sry, keine Ahnung was da anders wäre). Kann ich das iwie herausfinden was es sein könnte.

Server:
REDAXO 5.6.4
search_it 6.6.3
PHP 7.2.10
MySQL 5.6.26

lokal:
REDAXO 5.6.4
search_it 6.6.3
PHP 7.1.12
MySQL 5.6.38

egal was ich einstelle - rex_article nimmt er nicht.
Systemlog wirft nen Fehler:
`
Warning | You should not use non-secure socket connections while connecting to "meine-domain.de"!
`
sobald ich search_it im Backend starte ...

Danke

**Comment by darwin26** [comment]
hmm... schon einen Schritt weiter:
`Warning: A non-numeric value encountered in /meine-domain.de/htdocs/redaxo/src/addons/search_it/lib/search_it.php on line 139`

**Comment by alexplusde** [comment]
Schrittweise Indexierung sollte hier bereits korrekte Fehlermeldung ausgeben. Nur Erfolgsmeldung darf dann natürlich nicht sein

**Comment by tyrant88** [comment]
Hast du minifiy im Einsatz oder irgend etwas, was HTML Kommentare aus dem Quellcode filtert?
Häng mal ?search_it_build_index=doit an eine deiner URLs und schau im Quelltext ob du so was wie hier findest
![zwischenablage-1](https://user-images.githubusercontent.com/1277494/49251652-36304a80-f422-11e8-8596-8c37bf1a57c5.jpg)

**Comment by darwin26** [comment]
"" ... ist im Quelltext
minify - nein - nicht installiert

redaxo syslog:
`Warning | You should not use non-secure socket connections while connecting to "meine-domain.de"! redaxo/src/core/lib/util/socket/socket.php | 268`

ich hab noch einen ältere Version des Projektes (lokal) da läuft es...
hat es doch was mit dem (nichtvorhsnden SSL oder fehlerhaft konfig des servers zu tun)?
Wobei ich mir einbilde, das es vor ein paar Tagen (auch aufm Server) noch funktioniert hat.

*strange*

**Comment by tyrant88** [comment]
Nein ich hab es auch auf einem "nicht-SSL" System laufen. Die syslog Meldung habe ich dabei auch immer.

**Comment by darwin26** [comment]
die numeric warnung hab ich schon rausgefiltert... und auch weg...
aber wird immernoch nichts gefunden... gehe gerade schritt weise meine changes zurück ...
aber iwas is da faul.. kann mich erinnern, das ich das auch schon früher hatte und diese aber nur bis search_it 6.1.5 .. weil danach eben keine treffer mehr kamen ...

**Comment by tyrant88** [comment]
Tja, dann würde ich als nächstes in der Funktion "indexArticle" ein bisschen debuggen, wann und wo das Ergebnis "leer" wird.

**Comment by darwin26** [comment]
hmm...
er matched nicht (mehr)
 ... (links server // rechts lokal)
<img width="1130" alt="00002" src="https://user-images.githubusercontent.com/189407/49256771-6aab0300-f430-11e8-8a50-f9085658ecfd.png">

**Comment by tyrant88** [comment]
Das würde bedeuten in deinem Artikel mit der id 1 kommt "" nicht vor?
Sehe gerade das würde eigentlich sogar heißen alle deine Artikel bestehen aus Artikel 53, 119 und 54...

**Comment by tyrant88** [comment]
Noch spezifischer: dein Template besteht aus 3 Aufrufen von getArticle... mit immer den gleichen ids... holst du den eigentlichen Inhalt irgendwie anders als mit `$this->getArticle` oder `REX_ARTICLE[]` ?

Was ist denn Artikel 119?

**Comment by alexplusde** [comment]
Verstehe zwar nicht, dass das ein Indexierungsproblem auslöst, aber gut, dass die Quelle gefunden wurde :)

**Comment by tbaddade** [comment]
> Es hat(te) also nichts, niente, de nada mit -> search_it zu tun!

irgendwie dann doch, wenn durch einen regulären Aufruf `rex_article_slice::getSlicesForArticleOfType` nichts indexiert wird.

**Comment by darwin26** [comment]
in meinem Fall---> doof ---> da ich versehentlich 2x den selben Artikel (ID54) in unterschiedliche Templates auf unterschiedliche Weise eingebunden habe....

**Comment by tyrant88** [comment]
Freut mich dass das Problem gelöst wurde, aber Thomas hat nicht ganz unrecht. Muss mal prüfen, wie sich das verhält, wenn das Template nur aus Slice-Ausgaben besteht...

**Comment by tyrant88** [comment]
Eigentlich passt ja Darwins Problem genauer auf den Titel des issues ;-)
Dein ursprüngliches issue ist ja, dass es bei der Schrittweisen Indexierung keinen Fehlercode für "konnte Artikel nicht aufrufen" gibt, oder?

**Comment by IngoWinter** [comment]
Bin ich heute auch drüber gestolpert. Im Template des Artikels stand `REX_ARTICLE[1367 ctype=3]` , `REX_ARTICLE[1367 ctype=3]` , `REX_ARTICLE[1367 ctype=1]`,`REX_ARTICLE[1367 ctype=2]`,`REX_ARTICLE[1367 ctype=4]` drin, die `rex_search_it_index` blieb leer.

**Comment by tyrant88** [comment]
Hmm. Das sollte eigentlich kein Problem sein... 
kannst du den Artikel mal mit `URL?search_it_build_index=do-it` aufrufen und im SeitenQuellcode nach den `<!-- search it  xx -->` suchen?

**Comment by IngoWinter** [comment]
Es stehen 2 Kommentare drin:
`<!-- search_it 5 -->` die ID des aktuellen Artikels
`<!-- search_it 1367 -->` die ID des per `REX_ARTICLE[1367 ctype=1]` inkludierten Artikels

**Comment by tyrant88** [comment]
So sollte es auch sein. Alles dazwischen wandert in den Index... und der war leer?

**Comment by IngoWinter** [comment]
Ja, verlässlich reproduzierbar. lasse ich die ctypes über `if (rex_get('search_it_build_index', 'string', '') != 'do-it-with-yrewrite')` beim Indexieren nicht ausgeben, wird die Tabelle gefüllt, ansonsten bleibt sie leer. Fehlermeldungen beim Indexieren gibts nicht.
Wenn du mir einen Tipp gibst, wo ich am besten zum Debuggen ansetzen kann, mach ich das gerne.

**Comment by IngoWinter** [comment]
Geiles Addon übrigens. Bis auf diese obskure Nummer war alles sehr geschmeidig 👍

**Comment by tyrant88** [comment]
Das AddOn ist von @xong 
kannst du mir bitte mal die Quellcode-Ausgabe von oben zeigen/geben?
Die wandert dann in ` preg_match_all('/<!--\ssearch_it\s([0-9]*)\s?-->(.*)<!--\s\/search_it\s(\1)\s?-->/s', $articleText, $matches, PREG_SET_ORDER);`

**Comment by tyrant88** [comment]
Ah vielleicht, weil die eine ID doppelt vorkommt?

**Comment by IngoWinter** [comment]
Ich glaube ja. Wenn ich dem Regex ein `U` als zusätzliche Option mitgebe, funktionierts.

**Comment by IngoWinter** [comment]
```
<!-- search_it 1367 -->
<!-- /search_it 1367 -->
...
<!-- search_it 1367 -->
<!-- /search_it 1367 -->
...
<!-- search_it 5 -->
<!-- /search_it 5 -->
...
<!-- search_it 1367 -->
<!-- /search_it 1367 -->
```
Der Original Regex matcht alles zwischen der ersten und der letzten Zeile und da kommt dann nix bei rum...

**Comment by tyrant88** [comment]
Ich prüf das nochmal sobald ich Zeit habe... das wäre ja cool, wenn wir den Fehler hätten! Danke schon mal bis hier!

**Comment by alexplusde** [comment]
@tyrant88 ping

**Comment by tyrant88** [comment]
das haben wir schon längst eingebaut habe ich gerade parallel geprüft...
