### ISSUE TITLE
Indexerstellung beachtet https nicht

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/search_it#140]
Und da ich eine 301 Weiterleitung auf https bei NICHT https-Anfragen in der htaccess stehen habe, kommt im Systemlog ein 301 und dadurch ein Fehler. "Response not ok"

1) Dachte ich das Weiterleitungen bis zu einer Tiefe von 3 redirects berücksichtigt werden (scheint nicht zu laufen)

2) sollte search_it yRewrite's Domain oder die System-Server Einstellung beachten und ggf. normalisieren, zumindest aber das Protokoll sollte immer genutzt werden.

**Comment by Hirbod** [comment]
Fehlalarm: search_it funzt einfach nicht mit mod_security (zumindest in den Einstellungen die auf dem Server aktiv waren). Nach der Deaktivierung hat alles ganz normal funktioniert.

**Comment by alexplusde** [comment]
Hier auch noch fürs Protokoll: mod_security hat auf einem Server mal `echo` geblockt und `print` wiederum zugelassen. Ich glaube, bei einer exotischen Server-Konfiguration kann man da nicht viel machen.
