### ISSUE TITLE
Fehler in Statistik-Ausgabe

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/search_it#142]
https://redaxo.org/forum/addons-packages-r5-f43/search_it-addon-darstellungsfehler-bei-sstatistik-t22039.html

![statistik](https://user-images.githubusercontent.com/791247/34650939-79ca2f90-f3c9-11e7-8f38-12dc9c0187e5.png)

Ich kann den Fehler bei mir ebenfalls sehen:

**Comment by staabm** [comment]
@tyrant88 kann vermutlich jetzt geschlossen werden?

**Comment by tyrant88** [comment]
wollte es nur nicht gleich selbst machen... :-)

**Comment by skerbis** [comment]
Gut gut ... ich hab's geöffnet und schließe es wieder ;-)

**Comment by tyrant88** [comment]
hoffentlich auch getestet ;-)

**Comment by skerbis** [comment]
Ja ... alles bestens

**Comment by tyrant88** [comment]
Danke auch fürs Forum-Beobachten!

**Comment by helpy** [comment]
Danke auch an dieser Stelle für die schnelle Fehlerbehebung.

**Comment by skerbis** [comment]
Ich habe zu danken.
