### ISSUE TITLE
Aufruf von pdftotext ist fehlerhaft.

### ISSUE THREAD

**Issue by helpy** [FriendsOfREDAXO/search_it#145]
https://github.com/FriendsOfREDAXO/search_it/blob/d351632169890be015740549b2813f1871c62811/lib/search_it.php#L618

Dieser Aufruf funktioniert nicht in meinem Webhostingpaket. Ich habe den Aufruf über SSH-Kommandozeile probiert. Da wird nur der Hilfe-Text von `pdftotext --help` angezeigt.

Ich habe den Aufruf umgestellt:
```
exec('pdftotext -enc ' . $encoding . ' ' . escapeshellarg(rex_path::base($_filename)) . ' ' . escapeshellarg($tempFile), $dummy, $return);
```

So funktioniert der Aufruf und PDF-Dateien werden indiziert.
Ich verwende pdftotext version 4.00!

Leider enthält der Plaintext eine Menge Unicode-Zeichen (UTF-8 "EE 84 AD" usw, ). Leider habe ich es noch nicht geschafft diese herauszufiltern.

**Comment by tyrant88** [comment]
Auf meinen Servern ist die Syntax immer noch anders...
Ich muss mal testen, ob deine auxch bei mir funzt...

**Comment by tyrant88** [comment]
Dein Aufruf geht bei mir auch, also kommt er ins nächste Release

**Comment by tyrant88** [comment]
Ist drin
