### ISSUE TITLE
Möglichkeit zur Ausgabe aller indexierten Einträge

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/search_it#161]
Hallo, ich suche gerade verzweifelt nach einer Möglichkeit alle indexierten Einträge auszugeben.
Hintergrund: Wenn der User keinen Suchbegriff eingegeben hat, sollen alle indexierten Einträge ausgegeben werden. Mit der Suche soll dann verfeinert werden.

Im Prinzip so was:
`$search_it->search('*');`

**Comment by tyrant88** [comment]
Das ist nicht das, wofür search it gedacht ist.
Ich glaube du brauchst ein anderes Werkzeug.
