### ISSUE TITLE
Index von allen per ycom Login gesperrten Artikeln leer (v6.6.2)

### ISSUE THREAD

**Issue by Dollique** [FriendsOfREDAXO/search_it#162]
Hallo Zusammen

search_it Version: 6.6.2
ycom Version: 2.1b5

Unsere Inhalte sind per ycom Login für User und scheinbar auch für die Such-Indexierung gesichert.

Bei einer Indexierung wird nur das Login selbst korrekt indexiert. Alle anderen Tabellen sind zwar in der Index-DB drin, jedoch sind alle Einträge leer:

<img width="1621" alt="bildschirmfoto 2018-04-10 um 11 32 43" src="https://user-images.githubusercontent.com/11680332/38548837-0f2b48d0-3cb3-11e8-8484-b946520ac399.png">

Der einzige Workaround aktuell ist, alle Rechte zu entfernen, den Index zu schreiben und danach die Rechte wieder einzufügen.

Besten Dank!

**Comment by tyrant88** [comment]
Ja, das Indexieren von nicht öffentlichen Inhalten ist noch kein feature von search it.

**Comment by alexplusde** [comment]
(war mal eins von Rex_Search ;))

**Comment by alexplusde** [comment]
Könnte der Crawler nicht einen Token bei der URL mitgeben, der vom Modul / Template abgefangen wird und so hinter den Login schauen kann?

**Comment by xong** [comment]
Ihr geht an die Erstellung des Suchindex meiner Meinung nach völlig verkehrt ran. Im Index sollten erstmal alle Inhalte landen, völlig unabhängig davon, wer darauf Zugriff hat. Jegliche Autorisierung erfolgt dann beim Verwenden des Indexes, also z. B. in den Modulen oder Addons. Der Index ist ja per se nicht auf klassische Volltextsuchen beschränkt.

RexSearch war/ist so konzipiert, dass es einfach nur einen Index aufbaut. Korrekter wäre da wahrscheinlich der Name "RexIndex" gewesen. Mit der Vorgabe, dass Inhalte (fast) nur noch per HTTP-Request abgefragt werden, habt ihr den mächtigsten und für mich wichtigsten Teil des Addons massiv beschnitten.

Siehe auch Ticket #108.

**Comment by alexplusde** [comment]
Ich bin damit auch nicht glücklich und fühle mich von dem "ihr" jetzt nicht angesprochen ;)

**Comment by alexplusde** [comment]
Nochmal Gedanken dazu. In der Ergebnis-Liste erst nach der Berechtigung zu fragen ist ja zu spät, da man ja nur sichtbare Treffer zählen will. 

Man könnte wie folgt vorgehen:
* In YCom gibt es eine zusätzliche Rolle "search_it"
* search_it crawlt mit dieser Rolle - so kann man einstellen, ob wirklich alles indexiert werden soll oder bestimmte Inhalte bestimmter Rollen dann wirklich nie
* der search_it-Index-Abruf wird erweitert um die Information, welche Artikel-Treffer auch der aktuellen Rolle und den aktuell zugewiesenen Artikel-Rollen entsprechen. 
* nur die mit den passenden Berechtigungen landen auch im Index.

Dasselbe könnte man mit den Medienpool-Medien und media-auth übrigens auch machen.

**Comment by alexplusde** [comment]
Fürs Protokoll: Inhalte hinter Logins können im Zweifel über eine Datenbankindexierung realisiert werden.
