### ISSUE TITLE
Zusätzl. Datenquellen :: Diverse Tabellen erst gar nicht anzeigen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/search_it#163]
Man könnte die Liste der Tabellen minimieren. Folgende Tabellen bräuchten man sicherlich nicht indexieren

- rex_action
- rex_clang
- rex_config
- rex_media_manager_type
- rex_media_manager_type_effect
- rex_metainfo_field
- rex_metainfo_type
- rex_user
- rex_user_role
- rex_ydeploy_migration
- rex_yform_email_template
- rex_yform_field
- rex_yform_history
- rex_yform_history_field
- rex_yform_table
- rex_yrewrite_alias
- rex_yrewrite_domain
- rex_yrewrite_forward

Dann alle 
- <del>unsichtbare YForm-Tabellen</del>
- Relationstabellen in YForm

**Comment by alexplusde** [comment]
unsichtbare Tabellen würde ich drin behalten, die Szenarien dafür gäbe es. Aber sonst stimme ich vorbehaltlos zu.

**Comment by tbaddade** [comment]
> unsichtbare Tabellen würde ich drin behalten

stimmt. Können Datentabellen in popups sein. Habe ich oben korrigiert

**Comment by xong** [comment]
Ich mach mal ´n Veto.
Ihr wisst nicht, wofür Search it verwendet wird. Am Ende ist das nur ein Index, der aufgebaut wird. Ich indexiere für Spezialfälle auch Systemtabellen von Redaxo. Die Volltextsuche ist ja nur ein Einsatzgebiet für das Addon.

**Comment by tyrant88** [comment]
Ich hatte da eh keinen sinnvollen Ansatz gesehen, wer wie bestimmen soll welche Tabellen sichtbar sein sollen. Jemand installiert ein neues AddOn mit 50 Tabellen, das search it nicht kennt, und es erscheinen trotzdem 50 Tabellen.
Wenn es eine Eigenschaft gäbe wie "Systemtabelle" oder so ähnlich könnte man die  ausblenden und dann mit ner checkbox "auch Systemtabellen anzeigen" wieder einblenden.

**Comment by xong** [comment]
Eventuell könnte man auch einfach den Auswahlprozess in den Einstellungen so umstellen, dass man über eine Selectbox die Tabelle auswählen und dann auf "hinzufügen" klicken kann. Dann ist das nicht mehr so unübersichtlich.

**Comment by alexplusde** [comment]
* rex_article_slice_history
* rex_cronjob
* rex_url_generate
* rex_yform_history 
* rex_yform_history_field
* rex_yrewrite_alias
* rex_yrewrite_domain
* rex_yrewrite_forward

**Comment by alexplusde** [comment]
Ich war erst zuversichtlich, dass das entfernen die Ansicht übersichtlicher macht - muss aber sagen, dass das Ergebnis ernüchternd ist: 
![image](https://user-images.githubusercontent.com/3855487/79750075-96be7100-8310-11ea-9327-f2ab07d26d16.png)

**Comment by alexplusde** [comment]
in diesem Zuge könnte man höchstens sagen, dass die Tabellen von Search it selbst noch ausgeblendet gehören. (und yform_rest_token vermutlich auch)

Aber wie gesagt, richtig hilfreich war's jetzt nicht bei so vielen verbleibenden Tabellen. Ich würde daher gerne lieber dieses Issue schließen.

**Comment by tyrant88** [comment]
mal über xongs Vorschlag nachdenken.. bzw. so ähnlich...
Ein Multiselect was alle Tabellen und alle Spalten enthält mit dem man Spalten auswählt. Und eine eigene Anzeige für alle bereits ausgewählten...

**Comment by tyrant88** [comment]
Den Dialog optimieren finde ich gut das issue unter diesem Titel kannst du gerne schließen, weil ich keine Tabellen ausgeblendet haben möchte.

**Comment by alexplusde** [comment]
Ziel muss sein, möglichst einfach Felder an/abwählbar zu machen. Ich denke, wir finden da eine bessere Eingabemöglichkeit, die ein Ausblenden überflüssig machen.
