### ISSUE TITLE
Dokumentation Beispiele Modulausgabe Suche

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/search_it#164]
statt 
```$request = rex_request('search', 'string', false);```
sollte z.b.
```$request = htmlspecialchars (rex_request('search', 'string', false));```
verwendet werden um XSS zu verhindern

wobei ich sehe dass das schon thema war:
https://github.com/FriendsOfREDAXO/search_it/commit/42621c43ae5aa8ecf94c341e1b0755b41637b6d2

aber ist das auch schon in den Beispiel Modulausgaben berücksichtigt?

**Comment by alexplusde** [comment]
Sollte das wirklich im Beispiel-Template/Modul behandelt werden, oder nicht viel eher bei der Entgegennahme des Suchbegriffs innerhalb von search_it?

**Comment by tyrant88** [comment]
mist falsch issue nummer

**Comment by alexplusde** [comment]
@steri-rex du hast recht, da der Suchbegriff auch wieder 1:1 ausgegeben werden kann, sollte die Eingabe vorher escaped werden.

**Comment by tyrant88** [comment]
Das kann ja dann zusammen mit #170 erledigt werden...

**Comment by alexplusde** [comment]
Könnte man hier auch mit dem CSRF-Token arbeiten, um XSS zu vermeiden? Wie müsste ein Sucheingabeformular aussehen, das den CSRF-Token berücksichtigt? Geht das nur mit YForm oder auch so? @dergel

**Comment by alexplusde** [comment]
ping @dergel 

Wäre ein Umstieg auf rex_form eine Option? Oder kann man die CSRF-Features in REDAXO auch in eigenen HTML-Formularen verwenden?

**Comment by alexplusde** [comment]
Nach kurzer Rücksprache hat sich das erledigt, CSRF schützt hier gar nicht an der Stelle.

Alles andere wurde bereits in der Doku umgesetzt.
