### ISSUE TITLE
Indexierung für Nicht-Admins ermöglichen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#165]
Einzelnes Benutzer-Recht für die Indexierung ermöglichen.

**Comment by tyrant88** [comment]
Ich denk du baust an deinem hallo AddOn...

**Comment by tbaddade** [comment]
Das Recht scheint es bereits zu geben
https://github.com/FriendsOfREDAXO/search_it/blob/master/package.yml#L13

**Comment by tyrant88** [comment]
Ich hab es mal getestet. Mit Rechten mach ich wenig. Was fehlt dir @alexplusde ?

**Comment by alexplusde** [comment]
Ich habe den Wunsch aus dem Slack-Channel herangetragen, habe selbst allerdings nicht auf dem Schirm, dass es wohl gehen soll. (Ich mach mit Rechten nichts und mit Benutzerrechten auch wenig ;))

Scheint also bereits zu gehen?

**Comment by tyrant88** [comment]
Dann von mir ein "Ja"
