### ISSUE TITLE
Dokumentation: Meldung "Typ db_column kann nicht dargestellt werden" verbessern

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#170]
In Slack stolpern die Entwickler darüber, dass bei einem Datenbank-Treffer nicht schon von Haus aus etwas kommt und halten die Meldung für eine Fehlermeldung. In Wirklichkeit muss der Entwickler allerdings selbst tätig werden. Wie können wir das besser kommunizieren?

**Comment by alexplusde** [comment]
einfach dump()?

**Comment by tyrant88** [comment]
vielleicht eher print_r()

**Comment by alexplusde** [comment]
Ich hab hier ehrlich gesagt keine gute Idee und jeder, der sich ein bisschen die Beispielmodule anschaut, bekommt es doch auf die Reihe. Die Fragen haben nachgelassen.
