### ISSUE TITLE
Doku: Dateiindexierung - was wird wie indexiert?

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#172]
![image](https://user-images.githubusercontent.com/3855487/44022877-360b432c-9ee9-11e8-8001-8fe3476595da.png)

Mir ist nicht mehr ganz klar, wann was indexiert wird. Verstehe ich das richtig:

1) Dateitypen, die indexiert werden sollen (ohne Quelle)
2) Quelle 1: Medienpool
3) Quelle 2: Dateiverzeichnis

Das heißt, 1 allein auszufüllen bedeutet, dass noch keine Datei indexiert ist und erst, wenn 2 oder 3 ausgefüllt sind, werden diese auch indexiert?

**Comment by tyrant88** [comment]
Ja, 1) gilt als Einschränkung für 2 und 3 man müsste  es eigentlich nach ganz unten rutschen.

**Comment by alexplusde** [comment]
Danke. Das würde ich bei Gelegenheit klarer formatieren.
