### ISSUE TITLE
Datei-Indexierung: Auf Medienpool-Kategorien beschränken

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/search_it#173]
kwT

**Comment by tyrant88** [comment]
Du möchtest nur bestimmte Kategorien auswählen können?

**Comment by alexplusde** [comment]
Genau. So, wie man auf einen Kategorie-Baum bei den Artikeln beschränken kann.

**Comment by tyrant88** [comment]
Im neuen Medienpool wird es keine kategorien mehr geben... ;-)

**Comment by alexplusde** [comment]
Dann eben auf Tags ;)

**Comment by tyrant88** [comment]
Das sollte eigentlich ja nur eine Fleißarbeit sein...
