### ISSUE TITLE
Wunsch: Datei-Indexierung: Mehrere Regeln aufstellen können

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#174]
z.B.
im Medienpool in Kategorie 5 nur pdf indexieren
im Medienpool allgemein nur text indexieren
im Dateisystem-Ordner `/example/` alle Dateien indexieren

**Comment by xong** [comment]
Ich würde das nicht in die Indexierung nehmen, sondern ins Suchmodul. Und da funktioniert das ja auch schon.

**Comment by alexplusde** [comment]
Auch mein Szenario?

**Comment by xong** [comment]
Sicher, du hast zwar alle Dinge im Index, aber schränkst im Suchmodul ein, was durchsucht werden soll.

**Comment by alexplusde** [comment]
Wie?

**Comment by xong** [comment]
Ich weiß zwar nicht, was du mit 
> im Medienpool allgemein nur text indexieren

meinst, aber die anderen beiden würde ich so lösen:

```
// im Medienpool in Kategorie 5 nur pdf durchsuchen
$search_it->searchInFileCategories(5);
$search_it->setWhere('fileext = "pdf"');

// im Dateisystem-Ordner /example/ alle Dateien durchsuchen
$search_it->setWhere('filename LIKE 'example/%');
```

Und wenn du auf Probleme stößt, die mit den bisherigen Einschränkungsmethoden nicht lösbar sind, muss das Addon erweitert werden. Aber ziemlich viel geht auch so schon.
Kritisch wird es z. B., wenn du mehrere Bedingungen mit OR verknüpfen möchtest. Das musst du dann entweder ausschließlich über setWhere lösen oder du musst mehrere Suchinstanzen verwenden.

**Comment by alexplusde** [comment]
Das wusste ich bis jetzt wirklich nicht. Toll! Muss alles in die Doku....
