### ISSUE TITLE
Bug: Zusammenspiel von Search_it, YRewrite und nicht vorhandenem Fehler 404-Artikel

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#177]
Ohne es selbst näher getestet zu haben ist mir heute wieder ein Fall begegnet, bei dem jemand im Slack-Channel von Problemen bei der Indexierung berichtet hat.

Irgendwie gibt es ein Problem mit der Indexierung, wenn...
* Der Fehler 404-Artikel im System nicht gesetzt ist
* oder auf den Home-Artikel zeigt,
* oder nicht in YRewrite richtig gesetzt ist,
* oder auf den Home-Artikel zeigt,
* oder auf einen Artikel außerhalb des Mountpoints,
* oder eine Kombination aus oben genannten Fällen.

Das Problem tritt nicht auf, wenn 
* ein separater Fehler-404-Artikel 
* unterhalb des Mountpoints angelegt ist, 
* der sowohl unter "System",
* als auch ggf. in YRewrite korrekt angegeben wurde.

Diese Anforderung sollte entweder klar in der Doku sein und im Addon vor einer Fehlkonfiguration gewarnt werden, oder eine ungünstige Konfiguration sollte nicht zu einem Problem mit der Indexierung führen.

@tyrant88 was meinst du dazu?

**Comment by tyrant88** [comment]
Das würde ich gerne mal überprüfen im Code, ob sich da was findet, was sich darauf bezieht.
Das Indexieren über Sockets nutzt z.B. nur den 404 StatusCode. 
Wird der ordentlich gesendet, wenn man keinen FehlerArtikel gewählt hat?
YRewrite muss ich auch nochmal checken, ob es jetzt wirklich eine Vorraussetzung ist.
Etc. Gib mir ein paar Tage, dann wollte ich mich eh mal wieder ran machen.

**Comment by alexplusde** [comment]
Wo ist das passende Issue? (Link)
