### ISSUE TITLE
Feature: Gewichtung von Fundstellen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#18]
Es sollte möglich sein, Treffern eine Gewichtung mitzugeben. Bspw.
- Titel höher gewichten als Artikeltext, h1 höher gewichten als h2, Meta-Feld höher oder niedriger gewichten.
- Aktuelle Artikel höher gewichten als ältere, siehe https://github.com/tyrant88/search_it/issues/19

**Comment by dpf-dd** [comment]
Dieses Problem hatte ich die Tage ebenfalls - und konnte es lösen.
Es ist allerdings nur ein Workaround im Ausgabemodul, am AddOn-Code habe ich nichts modifiziert.

`	if($result['count'] > 0)
	{
		### WORKAROUND => NEUESTE ARTIKEL IMMER ZU ERST LISTEN => ARRAY UMSORTIEREN
		for($x = 0; $x < count($result['hits']); $x++)
		{		
			$updatedate = new rex_article($result['hits'][$x]['fid']);
			$updatedate = $updatedate->getValue('updatedate');
			$result['hits'][$x]['updatedate'] = $updatedate;
		}
    usort($result['hits'], function ($a, $b)
		{
	  	return strcmp($b['updatedate'], $a['updatedate']); ### ABSTEIGENDE REIHUNG
	  	#return strcmp($a['updatedate'], $b['updatedate']); ### AUFSTEIGENDE REIHUNG
		});
		### WORKAROUND ENDE		

		$output .= '<h3>Die Suche ergab folgende Ergebnisse:</h3>';
		$output .= '<ul class="searchresults">';
		foreach($result['hits'] as $hit)
		{
`

Mit diesem Snippet werden die vom AddOn ermittelten Daten neu sortiert und die neuesten Artikel (die den Suchbegriff beinhalten) vor alten Artikeln gelistet.

ACHTUNG, es gibt auch einen Nachteil: Das Relevanz-Kriterium geht verloren. Es werden nun nicht mehr die Pages mit den meisten Hits zuerst ausgegeben. Aber ok, das war ja auch Sinn der Sache. Wollte es nur erwähnt haben :)

**Comment by alexplusde** [comment]
Zu bedenken ist, dass dies nur für kleine Suchanfragen reicht, bei der alle Suchergebnisse auf einer Seite dargestellt werden. Sobald es mehr als bspw. 10 Einträge sind (`LIMIT 10`), werden nur die aktuellen 10 Treffer einer Ergebnisseite sortiert und nicht alle.

**Comment by alexplusde** [comment]
Ich glaube, hier wird absehbar nichts passieren, sonst hätte sich hier noch jemand gemeldet.

Und inzwischen bin ich davon überzeugt, dass ein ordentlicher Index und eine ordentliche Struktur der Website deutlich mehr dazu beitragen, gute Suchergebnisse zu erzielen.
