### ISSUE TITLE
VIEW Tabelle als zusätzliche Quelle erzeugt negative IDs im Search it Cache

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/search_it#183]
Ich habe eine VIEW Tabelle mit den Spalten: id,schlagwoerter als zusätzliche Quelle ausgewählt. Nach dem Indexieren steht in der Search it Tabelle "rex_search_it_index" in Spalte "fid" die negative ID der VIEW Tabelle.

**Comment by tyrant88** [comment]
Ja, bei der Indexierung zusätzlicher Spalten sucht search it nach Spalten mit einem primär Schlüssel Index. Den haben views aber nicht, weshalb es in den Modus für Medeinpool-Dateien verfällt, der einfach die Einträge der Such-Index-Tabelle "durchnummeriert"...

**Comment by alexplusde** [comment]
Ohne Primärschlüssel sollte dann einfach `id` verwendet werden, oder? Bzw. was ist so schlimm daran, negative IDs dort zu haben? Da ich search_it auch mit Views im Einsatz habe, sehe ich da kein großes Problem drin.

**Comment by tyrant88** [comment]
Es geht darum, das die "fid" benötigt wird, um gezielt diesen Eintrag z.B. neu zu indexieren. Im Moment wird dann die ganze Tabelle neu indexiert.
