### ISSUE TITLE
Feature: Reihenfolge der Suchergebnisse: Sortieren nach Datum ASC/DESC

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/search_it#19]
War ein häufig gefragtes Feature, das entweder nie verbaut wurde oder es nie so dokumentiert wurde, dass man es verwenden konnte.

**Comment by skerbis** [comment]
oder nach Artikel-ID

**Comment by xong** [comment]
Um nach einem Datum sortieren zu können, muss jedes Item im Suchindex ein solches Datum haben. Sonst wird der Suchindex inkonsistent.
Ich habe per Standard nach dem relevantesten Suchergebnis sortieren lassen.

Wenn ihr das Datum als Such- und/oder Sortierkriterium mit hineinbringen wollt, müsst ihr darauf achten, dass die Indexierung dann auch für spezielle Items, z. B. Dateien, aber auch Datenbankspalten, die Möglichkeit anbietet, ein Erstell-/Änderungsdatum mit in den Index aufnehmen zu können.

**Comment by tyrant88** [comment]
Du darfst gerne auch selbst wieder Hand anlegen, wenn ich Search it zu FOR umgezogen habe. Deine Kenntnisse können wir gebrauchen.

**Comment by alexplusde** [comment]
@xong wie wird denn aktuell Relevanz berechnet? Wo kann man da Parameter setzen?

**Comment by tyrant88** [comment]
Das war für mich die größte Erkenntnis: MySQL berechnet die Relevanz.
Und es gibt eine Funktion:
$search_it->setOrder(array('createdate'=>'ASC'));
funzt aber nicht

**Comment by alexplusde** [comment]
Ins Blaue reingeraten: createdate ist gar nicht überall in Datenbanktabellen verfügbar (bspw. yform), außerdem gibt's dieses Feld auch nirgends in den `Search it`-Tabellen. Dieses Datum müsste doch bei der Indexierung "nur" in `rex_search_it_index` mit aufgenommen werden, oder nicht?

Entweder, indem der vorhandene Wert von `createdate` verwendet wird, oder, falls nicht vorhanden, das Datum der Indexierung mit `NOW()`.

**Comment by alexplusde** [comment]
Ich habe ein Doku-Issue geschlossen, darf ich mir wünschen, dass dieses Feature als nächstes umgesetzt wird? :P

**Comment by tyrant88** [comment]
Ja. :-)

**Comment by alexplusde** [comment]
Rund vier Jahre später nochmals die Frage: Was muss man tun, damit `$search_it->setOrder(array('createdate'=>'ASC'));` funktioniert?

**Comment by alxndr-w** [comment]
Hier noch einen interessanten Ansatz gefunden, der relevance und zeitstempel gleichermaßen berücksichtigt. https://stackoverflow.com/questions/28616611/mysql-fulltext-search-and-sort-by-relevance-time

**Comment by tyrant88** [comment]
Ja, das ist interessant.
