### ISSUE TITLE
Socketfehler bei Nicht-Standardport (hier: 20080) in einem Docker-Setup

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/search_it#191]
Offenbar gibt es einen Socketfehler, wenn nicht die Standardports verwendet werden. Bei mir tritt es im [Docker-Setup](https://github.com/FriendsOfREDAXO/redaxo-mit-docker) auf, sowohl ohne SSL auf **localhost:20080** als auch mit SSL auf **localhost:20443**, wie im Screenshot zu sehen.

![screenshot 2019-02-17 at 13 08 16](https://user-images.githubusercontent.com/1297466/52912721-7088e580-32b5-11e9-9667-77e81a1885cc.png)

**Comment by tyrant88** [comment]
Hast du den Port auch bei der domain notiert?

**Comment by schuer** [comment]
@tyrant88 Yessir!

**Comment by tyrant88** [comment]
sorry, habs gerade auch in deinem scrrenshot gesehen.

**Comment by tyrant88** [comment]
Also bei mir schnurrt es local auch mit Port 20080... 
![zwischenablage-1](https://user-images.githubusercontent.com/1277494/53739509-382aff00-3e92-11e9-8e60-73e9492db77e.jpg)

**Comment by schuer** [comment]
Danke, ich werde nochmal testen…

**Comment by tyrant88** [comment]
kann die fsockopen Funktion eingeschränkt sein? ping @gharlan

**Comment by staabm** [comment]
Ggf. Via php-ini auf der liste der forbidden/disabled functions?

**Comment by staabm** [comment]
Ggf. Steht im php error log was genaueres?

**Comment by staabm** [comment]
Oder der docker container hat keinen internet zugang?

**Comment by gharlan** [comment]
Kenne mich mit Docker ja noch nicht wirklich aus, aber könnte mir vorstellen, dass innerhalb des Containers über Port 80 aufgerufen werden müsste, wenn ich mir das hier so anschaue:
https://github.com/FriendsOfREDAXO/redaxo-mit-docker/blob/master/docker-compose.yml#L9-L10
20080 gilt vermutlich nur vom Host aus.

**Comment by schuer** [comment]
Ich weiß nicht, was Search it genau tut, aber ja, was Gregor sagt: Innerhalb des Containers Port 80. Werde mir das bei Gelegenheit mal genauer anschauen, auch das error log.

**Comment by gharlan** [comment]
[Es ruft das Frontend über `rex_socket` auf](https://github.com/FriendsOfREDAXO/search_it/blob/fdf8848edb4b86e80bdf5e2b7dcbb93656790a91/lib/search_it.php#L238). Also ein HTTP-Request auf das Frontend, über die Frontend-URL.

Die große Frage ist, wie man nun search_it dazu bringen könnte, da eine andere URL (anderen Port) zu verwenden.
Aber vielleicht kannst du bei Gelegenheit an der Stelle ja mal bisschen debuggen, ob es mit anderem Port dort überhaupt klappen würde.

**Comment by schuer** [comment]
@tyrant88 Was Gregor sagt. Search it nimmt `rex::getServer()` als URL, und die ist in meinem Fall localhost:20080, wenn ich REDAXO im Browser aufrufe, wird im Docker-Container jedoch auf den Standardport 80 gemappt.

Ich bin mir nicht sicher, wie sinnvoll es ist, aber vermutlich könnte man Ports generell wegkappen, so dass Search it immer auf den Standardports indexiert:

```php
// get url without the port
// e.g. http://localhost:20080/ -> http://localhost/
$url = str_replace(':' . parse_url(rex::getServer(), PHP_URL_PORT), '', rex::getServer());
```

Könntest du an der Stelle einbauen, die Gregor verlinkt hat. Gerade getestet, und in meinem Fall zumindest funktioniert Search it damit prächtig.

**Comment by tyrant88** [comment]
Die Ports generell wegschneiden halte ich für wenig sinnvoll, denn das würde ja den "normalen" Fall kaputtmachen, dass man eine Instanz mit einem anderen Port anspricht.
Es müsste also eher eine Option sein. ("Ich bin @schuer, mach die die Ports weg" , oder so ähnlich) ;-)
Oder man macht gleich eine Eingabe für die zu scannende URL... wer weiß was man damit noch für tollen Unfug machen könnte... :-)

**Comment by schuer** [comment]
Na dann los, Option! :)

**Comment by alexplusde** [comment]
> Oder man macht gleich eine Eingabe für die zu scannende URL...

Problematisch mit YRewrite. Das übrigens auch eine Porteingabe nicht zulässt.

@schuer es gibt keine Möglichkeit innerhalb von Docker, die Anfrage auf den Port :20080 an :80 weiterzurouten?

**Comment by schuer** [comment]
> es gibt keine Möglichkeit innerhalb von Docker, die Anfrage auf den Port :20080 an :80 weiterzurouten?

@alexplusde Hm, das weiß ich nicht. Vermutlich gibt es Möglichkeiten. Allerdings lösen sie das hier vorliegende Problem in Search it nicht, sondern bilden nur einen Workaround auf Anwenderseite.

**Comment by alexplusde** [comment]
Ein Problem, das doch erst durch die Anwenderseite entsteht, oder? Mir wäre nur kein weiterer Fall bekannt, in der das Problem je aufgetaucht ist. 

Wäre es in Ordnung, wenn #108 gelöst würde? Dann würde sich die Frontend-Indexierung ja erübrigen.

**Comment by schuer** [comment]
Wenn es für euch funktioniert und an dieser Stelle keine weiteren Maßnahmen erfolgen sollen, dann schließt gerne. Ich habe ja keinen echten Bedarf an einer Lösung.

Und ja, #108 it is!

**Comment by tyrant88** [comment]
Ich möchte immer noch eher eine Option, wo man die zu indexierende URL einstellen kann.

**Comment by tyrant88** [comment]
Nur das bug-label stört mich.

**Comment by tyrant88** [comment]
Das müsste jetzt eigentlich mit der neuen Version umsetzbar sein. Ich habe ja eine solche Option eingebaut.

**Comment by schuer** [comment]
Top. Dann kann hier sicherlich geschlossen werden, oder? Danke dir!
