### ISSUE TITLE
Search Highlighter "umdrehen" - nur in erlaubten Bereichen ersetzen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/search_it#194]
Da der Search Highlighter nach wie vor an manchen Stellen Probleme macht, wäre es vlt. der bessere Ansatz, die Ersetzungen nur innerhalb bestimmter Bereiche explizit zu erlauben. Man könnte ihm einen anderen Modus verpassen, in denen er

* nur in Suchergebnis-Treffern sowie
* nur in bestimmten HTML-Elementen mit fest definierten Klassen

hervorheben darf.

Ich würde sogar so weit gehen, zu sagen: Wer es dann anders benötigt (auf der kompletten Website, etc.), kann Highlighting auch per JS nachrüsten.

**Comment by alexplusde** [comment]
Welcher Weg wäre denn der gewünschte? Dieser Vorschlag hier oder #186 ? Eins von beiden kann zu imho.
