### ISSUE TITLE
Compilation failed: invalid range in character class at offset 4 

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#197]
preg_match() [<a href='https://php.net/manual/function.preg-match'>function.preg-match</a>]: Compilation failed: invalid range in character class at offset 4 |  

<details>
<summary>System report (REDAXO 5.7.0, PHP 7.3.0)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.7.0      |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.3.0      |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                        |
| ------------: | :--------------------- |
|       Version | 5.6.35-log             |
| Character set | utf8 (utf8_general_ci) |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/72.0.3626.121 |
|      Protocol | HTTP/1.1             |
|         HTTPS | no                   |

| Packages                    |             |
| --------------------------: | :---------- |
|                accessdenied | 1.0.5       |
|                     adminer | 1.5.0       |
|                      backup | 2.3.0       |
|                    be_style | 2.7.0       |
|         be_style/customizer | 2.7.0       |
|                     bloecks | 1.3.15      |
|            bloecks/cutncopy | 1.3.12      |
|              bloecks/status | 1.3.12      |
|                cache_warmup | 3.6.0       |
|                     cronjob | 2.4.0       |
|                   developer | 3.8.0       |
|                       dsgvo | 0.9beta5    |
|             global_settings | 2.1.0       |
|                       hello | 0.4.4-dev   |
|                     install | 2.5.0       |
|                 maintenance | 2.0.0       |
|                    markitup | 3.2.0       |
|      markitup/documentation | 1.0.1       |
|                      mblock | 3.1.0       |
|               media_manager | 2.6.0       |
|                   mediapool | 2.5.0       |
|                    metainfo | 2.4.0       |
|                       mform | 5.3.0       |
|                  mform/docs | 1.0         |
|                      minify | 2.1.0       |
|          navigation_factory | 2.0.1       |
|                   phpmailer | 2.5.1       |
|                  pixelfirma | 1.1         |
|         pixelfirma/px_admin | 1.0.5       |
|           pixelfirma/px_lib | 1.0.3       |
|         pixelfirma/px_style | 1.0.6       |
|                     project | dev         |
|            quick_navigation | 3.5.7       |
|                   search_it | 6.6.5       |
|     search_it/documentation | 6.6.5       |
|         search_it/plaintext | 6.6.5       |
|             search_it/stats | 6.6.5       |
|                       sprog | 1.2.0       |
|                   structure | 2.7.0       |
|           structure/content | 2.7.0       |
|                       theme | 1.1.1       |
|                    uploader | 2.0.4       |
|                         url | 2.0.0-beta3 |
|                       users | 2.5.2       |
|                      watson | 2.1.0       |
|               xoutputfilter | 3.0.0-beta1 |
|       xoutputfilter/backend | 3.0.0       |
| xoutputfilter/documentation | 1.0.0       |
|      xoutputfilter/frontend | 3.0.0       |
|                        ycom | 3.0-beta4   |
|                   ycom/auth | 3.0-beta4   |
|                   ycom/docs | 3.0-beta4   |
|                  ycom/group | 3.0-beta4   |
|                       yform | 3.0         |
|                  yform/docs | 3.0         |
|                 yform/email | 3.0         |
|               yform/manager | 3.0         |
|                  yform/rest | 3.0         |
|             yform_usability | 1.4         |
|                    yrewrite | 2.5         |
|                   yuploader | dev         |

</details>

**Comment by tyrant88** [comment]
?

**Comment by alexplusde** [comment]
Kommt beim indexieren

**Comment by pschuchmann** [comment]
Das hatte ich eben auch gerade. Das scheint der HTML Parser aus dem Plaintext zu sein. Das steht in der Zeile: `if (!preg_match("/^[\w-:]+$/", $tag)) {`


![grafik](https://user-images.githubusercontent.com/35096518/58092094-8b783800-7bcb-11e9-87c7-4cd6c6f3cdae.png)

**Comment by pschuchmann** [comment]
Ok, ich seh gerade, dass in der vorhandenen Klasse einige Anpassungen zum Original vorgenommen wurden. Vielleicht ist es effektiver wenn @tyrant88 nochmal rein schaut :sweat_smile:

**Comment by tyrant88** [comment]
mach doch mal einen Backslash vor das "-" ,
also `!preg_match("/^[\w\-:]+$/", $tag)`

**Comment by pschuchmann** [comment]
Läuft damit dann auch unter PHP 7.3 :+1:
