### ISSUE TITLE
Mehrsprachige Datenbank

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/search_it#201]
Bei mehrsprachigen Seiten kommt es vor, dass auch mehrsprachige zu durchsuchende Datenbanken im Spiel sind. Bei den Datenbankergebnissen wird aber die Sprache nicht ins Feld search_it_index.clang geschrieben. So werden bei der Suche gegebenenfalls auch Datensätze gefunden, die nicht zur aktuellen Sprache gehören. Nicht so schlimm, die kann man ja bei der Ausgabe rauswerfen. Aber der Wert `$result['count']` stimmt dann nicht mehr. - Wäre ein enhancement.

**Comment by dtpop** [comment]
Issues schreiben und nicht zumindest einen Workarround liefern - geht ja eigentlich nicht ...
Daher zumindest diese Lösung:
Das Sprachfeld der Tabelle mit indizieren lassen.
Dann als zusätzliche Where Klausel setzen:
```$search_it->setWhere("`values` LIKE '%\"clang_id\";s:1:\"1\"%' OR ftable = 'rex_article'");```
wenn das Sprachfeld clang_id heißt.

**Comment by alexplusde** [comment]
Kann ruhig auf bleiben, ist ja ein Bug. Datensätze sollten kompatibel zu mehrsprachigen Seiten indexiert werden können.

**Comment by dtpop** [comment]
Ein Lösungsansatz könnte noch ein Extensionpoint "SEARCH_IT_INDEXING_FINISHED" sein, dann könnte man von dort aus das clang Feld selber füllen.

**Comment by tyrant88** [comment]
Danke Wolfgang, das sollten wir irgendwie in eine Doku packen.
Und eigene Extensionpoints sind auch ne Idee...

@alexplusde :  Muss schon wieder stänkern, aber es ist definitiv kein "Bug".
Nur wenn jeder Datensatz immer automatisch einer REDAXO-Sprache zugeordnet wäre...

**Comment by alexplusde** [comment]
Korrigiere: Missing feature

**Comment by alexplusde** [comment]
#242
