### ISSUE TITLE
Offline-Artikel bleiben nach "offline"-Schaltung im Suchindex

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/search_it#202]
Artikel, die offline geschaltet werden, verbleiben weiterhin im Suchindex/-ergebnis, wenn kein manueller Reindex gemacht wird. Andersrum funktioniert es, d.h. Offline-Artikel, der bisher nicht gefunden wird, erscheint nach Online-Schaltung im Suchergebnis

Getestet in:
Redaxo 5.7.0
Search-it 6.6.5

**Comment by alexwenz** [comment]
Frage hierzu: sollte man Artikel die in den "Seo-Daten" in Redaxo auf "noindex" stehen auch aus dem Suchindex werfen? Die oben getesteten Artikel sind auf "noindex" geschaltet.

**Comment by alexplusde** [comment]
Ich halte das für eine robots-Anweisung, nicht für search_it. Man kann anhand eines GET-Parameters die Ausgabe für die Indexierung unterbinden, wenn man es benötigt.

Das ursprüngliche Issue unterstütze ich. Offline sollte eine Reindexierung nötig machen. Müsste Mal testen, ob das nicht so ist.

**Comment by alexwenz** [comment]
Haben noch ein wenig getestet (Danke Wolfgang):

- es betrifft nur Startartikel (also Artikel, die gleichzeitig eine Kategorie sind). "Normale Artikel" werden brav aus dem Suchergebnis (ohne Reindex) entfernt, wenn man sie offline schaltet
- Ein interessantes Phänomen ist nun, wenn man den offline-Startartikel (der im Suchergebnis vorkommt) bearbeitet, d.h. einen Slice öffnet und speichert, ist er danach aus dem Suchergebnis entfernt.

**Comment by alexplusde** [comment]
https://github.com/tyrant88/search_it/blob/master/boot.php#L64 der EP ist allerdings vorhanden.

In der aktuellen Version von REDAXO gibt es auch einen Fehler beim Verschieben von Kategorien, womöglich hat es damit aber nichts zu tun.

**Comment by tyrant88** [comment]
Hab mal in den Code geschaut... ja da muss man nachbessern...
