### ISSUE TITLE
Für Pedanten: <mark> statt <strong> verwenden

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#205]
Hier https://github.com/FriendsOfREDAXO/search_it/blob/b2293d801b27753959262778ed154a8455036b7f/lib/search_it.php#L50 und als Voreinstellung.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark

Danke @Pixeldaniel

**Comment by tyrant88** [comment]
Das ist dann aber ein "breaking change". Da müssen die Leute ihr CSS ändern... Zumindest wenn die config Values mal weg sein sollten...

**Comment by alexplusde** [comment]
Das ist nicht BC, nur die default-config wird verändert. Bestehende Werte bleiben ja...
