### ISSUE TITLE
Status einer Sprache beim Indizieren berücksichtigen

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/search_it#206]
Hi, das AddOn scheint aktuell den Status einer Sprache nicht zu berücksichtigen. Es wäre schön, wenn es dazu eine Option wie bei den Artikeln gäbe um offline gestellte Sprachen auszuschließen.

**Comment by alexplusde** [comment]
Du kannst bei den Suchergebnissen die clang berücksichtigen, Infos dazu müssten in der Doku sein.

**Comment by alexplusde** [comment]
https://github.com/FriendsOfREDAXO/search_it/blob/master/plugins/documentation/docs/de_de/howto-languages.md

**Comment by DanielWeitenauer** [comment]
Das ist schon klar. Ich hatte es allerdings gerade mit einer Seite mit  jeder Menge Artikeln und einigen offline gestellten Sprachen zu tun, die dann alle unnötig indiziert wurden. Das produziert eine Menge Daten, die gar nicht benötigt werden. Da wäre es nett, wenn man sich diese und die Sprachen überspringen könnte. Analog der Möglichkeit, offline gestellte Artikel zu überspringen.

**Comment by alexplusde** [comment]
Ich schätze, das wird ein bisschen aufwendiger. In dem Vorschlag müsste auch das offline/online-Stellen von Sprachen via EP berücksichtigt werden und dabei würden auf einen Schlag sehr viele Daten indexiert werden müssen - wofür die Schrittweise-Indexierung nötig sein kann.

**Comment by tyrant88** [comment]
Ich hab mal angefangen es mir anzuschauen. Muss alle Stellen ändern wo indexiert wird und dort den Status der Sprache berücksichtigen.
Beim Statuswechsel würde ich lediglich ne Meldung ausgeben, dass der Index erneuert werden sollte.

**Comment by tyrant88** [comment]
Wobei es nur einen EP 'CLANG_UPDATED' gibt. Ob dann der Status geändert wurde, weiß man nicht.

**Comment by alexplusde** [comment]
Einmal zu viel indexieren, auch wenn sich der Status nicht geändert hat, wäre ja nicht schlimm. Mit einem passenden Hinweis würde es ja schon klar genug werden.

**Comment by alexplusde** [comment]
#242
