### ISSUE TITLE
DB Suchindex unvollständig bei schrittweiser Indexierung

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/search_it#208]
In einer mittleren Präsenz muss der Index schrittweise erstellt werden. Dabei fiel auf, dass der db Suchindex unvollständig ist.
Wenn ich nun aber alle Slices und Artikel aus der Präsenz lösche und den Index auf einen Schlag erstellen kann, ist der Index vollständig.
Ich habe mal ein bisschen im Code gestochert. Mir kommt es so vor, als lösche die Zeile 419 in der search_it.php bei jedem 100er Block die zuvor indexierten Datensätze. Wenn ich testweise diese Zeile auskommentiere, dann ist der Suchindex auch bei schrittweiser Indexierung vollständig.
Allerdings habe ich die Vermutung, dass in diesem wirklich großartigen AddOn diese Zeile doch irgendwie ihren Sinn hat. Daher verzichte ich heute mal auf einen Pullrequest und hoffe, dass Du @tyrant eine Lösung aus dem Hut zaubern kannst und sage dafür Danke!

**Comment by tyrant88** [comment]
Man! Super schön formuliert. Ich danke dir.
Ich muss auch immer wieder betonen ich habe das AddOn nur portiert.
Ich bin ziemlich unter Zeitdruck gerade, könntest du versuchen die Zeile 419 so zu ersetzen und das testen?
```if ( $_start === false || $_start == 0 ) { $delete->delete(); }```

**Comment by alexplusde** [comment]
Vielleicht kann @xong sich erinnern?

**Comment by alexplusde** [comment]
Könnte auch Ursache für #207 sein, jetzt bin ich mir nicht mehr sicher, ob ich vollständig oder schrittweise indexiert habe.

**Comment by tyrant88** [comment]
xong kann sich nicht erinnern, weil ich den Teil geändert habe.

**Comment by dtpop** [comment]
Super Norbert. Danke. Habe das getestet und es funktioniert.

**Comment by tyrant88** [comment]
cool, danke auch dir.
