### ISSUE TITLE
Fehler beim Indexieren

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/search_it#210]
Hallo Leute,

ich habe soeben auf dem GN2-Server ein Rex5 mit der search_it installiert.
Beim schrittweisen Indexieren erhalte ich pro Eintrag dabei folgende Fehlermeldung:

Warning: preg_match() [<a href='https://php.net/manual/function.preg-match'>function.preg-match</a>]: Compilation failed: invalid range in character class at offset 4 in redaxo/src/addons/search_it/plugins/plaintext/lib/simple_html_dom.php on line 769

Kennt jemand das Problem?

**Comment by tyrant88** [comment]
https://github.com/FriendsOfREDAXO/search_it/issues/197
Ist es das ?

**Comment by iceman-fx** [comment]
Könnte sein.
