### ISSUE TITLE
Nach Update: Aufforderung, den Suchindex zu erneuern

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/search_it#213]
Nachdem ein Update von search_it vorgenommen wurde, sollte der Benutzer dazu aufgefordert werden, den Suchindex zu erneuern - es könnte ja bereits im Vorfeld Probleme durch einen Bug gegeben haben, die vorher nicht aufgefallen sind.

**Comment by alexplusde** [comment]
Vorschlag: Aufnahme eines config-Werts `rex_config::set("search_it", "index_outdated", 1)` wird bei der install.php, update.php und via EPs gesetzt und bei erfolgreichem Indexieren wieder auf 0 gesetzt.

**Comment by tyrant88** [comment]
Sehe ich keine Veranlassung dazu. Wenn wir die Doku austauschen würden in einem Update? Dann kommt die Meldung "Sie sollten den Suchindex erneuern?"
Denke so was sollte im Bedarfsfall in die Release Notes.

**Comment by alexplusde** [comment]
Das schöne ist doch: mein vorgeschlagener Lösungsweg lässt sich pro Bedarfsfall nutzen.
