### ISSUE TITLE
Zusammenspiel mit Maintenance AddOn ermöglichen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/search_it#214]
evtl. wird das auch in maintenance selbst gelöst ... mal sehen

**Comment by staabm** [comment]
macht es sinn während wartungsarbeiten den such-index neu zu generieren?
in der regel kann man dann erwarten dass wg. wartung und ggf. damit verbundenen tasks die seite gar nicht funktioniert/keine korrekten inhalte liefert?

**Comment by alexplusde** [comment]
Ja. Kurz vor der Live-Schaltung bspw. - nicht wenige Entwickler haben keinen getrennten dev/live-Workflow.

**Comment by skerbis** [comment]
Es macht nicht wirklich Sinn, aber vermeidet Suchergebnisse die zur Maintenance URL oder Seite führen im Index.

**Comment by staabm** [comment]
aber dann bekommt man suchergebnisse die ggf. anderweitig nicht repräsentativ sind?

**Comment by skerbis** [comment]
Was wäre dein Vorschlag? Indizieren während der Wartung unterbinden? Ich denke das wäre auch eine gute Lösung. Du könntest auf den Maintenance Modus reagieren und das indizieren unterbinden.

**Comment by staabm** [comment]
du kannst vom addon aus eine API anbieten mit der andere addons einfach bestimmen können ob gerade die Wartung läuft.

Wenn die Wartung läuft könnte dieses Addon hier den "suchindex aufbauen" knopf auf disabled setzen.

**Comment by staabm** [comment]
> Ja. Kurz vor der Live-Schaltung bspw. - nicht wenige Entwickler haben keinen getrennten dev/live-Workflow.

ob man den index nach abschalten der wartungsseite oder vorher neu generiert ist vermutlich kein großer unterschied für den end-user

**Comment by skerbis** [comment]
@staabm Es würde reichen die Config vom Maintenance AddOn zu befragen.

**Comment by staabm** [comment]
> Es würde reichen die Config vom Maintenance AddOn zu befragen.

ich würde in addons ausserhalb von "maintenance" möglichst wenig logik, wie das addon funktioniert verteilen.

am einfachsten wäre sowas (Beispiel):

```
if (class_exists('MaintenanceMode') && MaintenanceMode::isActive()) {
  
}
```

wissen über die config, wann/wie/warum die wartung aktiv ist sollte niemand haben ausser das maintenance addon selbst

**Comment by skerbis** [comment]
Ich werde es  beim Maintenance-AddOn lösen. Die Funktionen der AddOns sollten nicht durch Maintenance beeinflusst werden.
