### ISSUE TITLE
Kategorie-Auswahl: $_ignoreoffline = false 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/search_it#215]
https://github.com/FriendsOfREDAXO/search_it/blob/cbd7b15b381f6aa98efb7ac86dc6cbd24d1772a7/functions/functions_search_it.php#L31

So können auch offline gelistete Kategorien in die Blacklist aufgenommen werden. 
Denn anscheinend werden online-Artikel in Offline Kategorien indexiert.

**Comment by tyrant88** [comment]
Das werde ich nutzen beim Aufruf der Funktion im Config-Dialog, gute Idee.
