### ISSUE TITLE
Autocomplete Status 500

### ISSUE THREAD

**Issue by danielellm** [FriendsOfREDAXO/search_it#219]
hallo,
ich bekomme bei autocomplete den status 500
suche funktioniert !

bei eingabe geht er auf https://domain.de/kategorie/kategorie/index.php?rex-api-call=search_it_autocomplete_getSimilarWords&rnd=0.15232916428200605&q=suchbegrif

Console sagt status 500

ich verwende neuste redaxo version mit yrewrite
was läuft flasch?

**Comment by tyrant88** [comment]
das PlugIn ist von @rkemmere 
500er ist ja ein ziemlicher low-level Fehler. Da ist was ganz Grundlegendes nicht in Ordnung. Sowas wie eine fehlende PHP Erweiterung oder fehlendes Apache rewrite...
Ich kann auf den ersten Blick nichts im PlugIn finden, was sowas auslösne könnte.

Der Link den du gepostest hast ( mit "/kategorie/kategorie" ) dürfte so nicht ganz in Ordnung sein.

**Comment by rkemmere** [comment]
Richtig der 500er!
Denn eine index.php gibt es nicht unter /kategorie/kategorie
So wäre es richtig.
https://domain.tld/index.php?rex-api-call=search_it_autocomplete_getSimilarWords&rnd=0.3053237135097837&q=me

**Comment by danielellm** [comment]
ok vielleicht habe ich die url nicht optimal hier angegeben..
die seite befindet sich noch im aufbau:
https://cms.salzgeber.de

wenn ich die url aufrufe ohne q= , kommt eine meldung empty q
https://cms.salzgeber.de/index.php?rex-api-call=search_it_autocomplete_getSimilarWords&rnd=0.8793547421236928

sobald die variable q dran hängt kommt fehler 500
https://cms.salzgeber.de/index.php?rex-api-call=search_it_autocomplete_getSimilarWords&rnd=0.8793547421236928&q=kino

habt ir eine idee?

**Comment by alexplusde** [comment]
Versuch Mal, `index.php` wegzulassen. Ich glaube da gab es Letzt erst was mit YRewrite, bei dem was umgestellt wurde.

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yrewrite/issues/298

Irritierend ist der 500er. Würde in den Systemeinstellungen ein separater Fehlerartikel hinterlegt? Die Domain korrekt in YRewrite hinterlegt?

**Comment by tyrant88** [comment]
kannst du in der config page vom autocomplete PlugIn mal auf "speichern" klicken?
Und dann deinen zweiten API Call noch mal machen?

**Comment by danielellm** [comment]
@tyrant88 das wars, jetzt läuft es..
vielen dank an alle!
