### ISSUE TITLE
Enhancements Autosuggest Darstellung und Mobile Funktion

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/search_it#221]
Im js vom Autosuggest Plugin gibt es ein keypress. Das ist deprecated und funktioniert nicht auf allen mobilen Devices. Eine Änderung auf keyup löst das Problem.

Die Anzeige des Autosuggest erfolgt standardmäßig im Body und wird dann positioniert.
Eine Änderung auf
```
m.addClass(s.resultsClass).appendTo(C.closest('.search_it-form')), l(), e(window).load(l).resize(l), C.blur(function() {
            setTimeout(function() {
                m.hide()
            }, 200)
        });
```
Setzt das Autosuggest in das Suchformular mit dem Input selbst. Es lässt sich dort leichter positionieren. Nachteil: IE kennt kein closest, dort funktioniert es dann nicht mehr.

**Comment by tyrant88** [comment]
Das mit keyup würde ich unterstützen.
Das andere empfände ich als Rückschritt, wenn es in weniger Browsern gänzlich funktioniert, um in einigen Browsern eine Verbesserung zu haben.

**Comment by alexplusde** [comment]
@rkemmere du hattest zuletzt das autocomplete-Plugin verbessert gemäß der Commits hier auf GitHub. Nutzt du es noch? Wie würdest du das Problem lösen?

**Comment by rkemmere** [comment]
@alexplusde ich schau mir die Problematik mal an. Generell hab ich kein Problem im mobile.
