### ISSUE TITLE
Cronjob "Tabellen aktualisieren": parameter fieldname must not be empty!

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#222]
**rex_sql_exception:** parameter fieldname must not be empty!
**File:** redaxo/src/core/lib/sql/sql.php
**Line:** 604

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                         | Line     |
| -------------------------------------------- | -------------------------------------------- | -------- |
| rex_sql->getValue                            | redaxo/src/core/lib/list.php                 | 936      |
| rex_list->getValue                           | redaxo/src/core/lib/list.php                 | 848      |
| rex_list->replaceVariable                    | redaxo/src/core/lib/list.php                 | 873      |
| rex_list->replaceVariables                   | redaxo/src/core/lib/list.php                 | 704      |
| rex_list->getParsedUrl                       | redaxo/src/core/lib/list.php                 | 931      |
| rex_list->getColumnLink                      | redaxo/src/core/lib/list.php                 | 1057     |
| rex_list->get                                | redaxo/src/addons/cronjob/pages/cronjobs.php | 136      |
| include                                      | redaxo/src/core/lib/packages/package.php     | 228      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php        | 474      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php        | 430      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/cronjob/pages/index.php    | 15       |
| include                                      | redaxo/src/core/lib/packages/package.php     | 228      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php        | 474      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php        | 413      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                  | 215      |
| require                                      | redaxo/src/core/boot.php                     | 135      |
| require                                      | redaxo/index.php                             | 11       |

</details>
<details>
<summary>System report (REDAXO 5.8.0, PHP 7.3.6-nmm1)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.8.0      |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.3.6-nmm1 |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                            |
| ------------: | :------------------------- |
|       Version | 5.7.26-nmm1-log            |
| Character set | latin1 (latin1_swedish_ci) |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/78.0.3904.70 |
|      Protocol | HTTP/2.0            |
|         HTTPS | yes                 |

| Packages                   |            |
| -------------------------: | :--------- |
|               accessdenied | 1.0.6      |
|                    adminer | 1.7.0      |
|            article_presets | 1.1.0      |
|                     backup | 2.4.0      |
|                be_password | 1.1.0      |
|                   be_style | 2.8.0      |
|        be_style/customizer | 2.8.0      |
|            be_style/redaxo | 2.8.0      |
|                    bloecks | 2.1.1      |
|           bloecks/cutncopy | 2.1.1      |
|             bloecks/status | 2.1.1      |
|               cache_warmup | 3.6.1      |
|                    cronjob | 2.5.0      |
|     cronjob/article_status | 2.0.0      |
|    cronjob/optimize_tables | 2.3.1      |
|                      dance | 1          |
|                  developer | 3.8.0      |
|                      feeds | 2.2.1      |
|            global_settings | 2.4.1      |
|                    install | 2.5.0      |
|                maintenance | 2.1.1      |
|                   markitup | 3.3.2      |
|     markitup/documentation | 1.0.1      |
|                     mblock | 3.1.0      |
|              media_manager | 2.7.0      |
|                  mediapool | 2.6.0      |
|                   metainfo | 2.5.0      |
|                      mform | 5.3.1      |
|                 mform/docs | 1.0        |
|                     minify | 2.1.0      |
|                  phpmailer | 2.6.0      |
|                 pixelfirma | 2.0.5      |
|        pixelfirma/px_admin | 2.0        |
| pixelfirma/px_dsgvo_client | 2.0        |
| pixelfirma/px_hello_client | 2.0        |
|          pixelfirma/px_lib | 2.0.5      |
|        pixelfirma/px_style | 2.0.3      |
|                    project | dev        |
|           quick_navigation | 3.7.1      |
|                  redactor2 | 4.0.2      |
|                  search_it | 6.6.6      |
|    search_it/documentation | 6.6.6      |
|            search_it/stats | 6.6.6      |
|                      sprog | 1.2.0      |
|                  structure | 2.8.0      |
|          structure/content | 2.8.0      |
|          structure/history | 2.8.0      |
|           structure_tweaks | 1.1.1      |
|                      theme | 1.1.1      |
|                   uploader | 2.0.4      |
|                        url | 1.0.1      |
|                usage_check | 2.2.1      |
|                      users | 2.5.2      |
|                     watson | 2.1.0      |
|                      yform | 3.3.1      |
|                 yform/docs | 3.3.1      |
|                yform/email | 3.3.1      |
|              yform/manager | 3.3.1      |
|                yform/tools | 3.3.1      |
|            yform_usability | 1.4        |
|                   yrewrite | 2.6        |

</details>

**Comment by alexplusde** [comment]
Im Log sieht man, dass dafür eine nicht mehr vorhandene Datenquelle in den Einstellungen verantwortlich war. Das sollte besser abgefangen werden.

**Comment by tyrant88** [comment]
? Bist du hier richtig?

**Comment by alexplusde** [comment]
Ja! Eine nicht mehr vorhandene Datenbanktabelle bei den zusätzlichen Datenquellen in search_it, die indexiert werden sollte, war verantwortlich für diesen Fehler. Im Stracktrace ist dies jedoch nicht aufgetaucht, was mich auch gewundert hat.

**Comment by tyrant88** [comment]
Das ist ja dann auch beim einfachen manuellen Neu-Indexieren der Fall, oder?

**Comment by alexplusde** [comment]
stimmt eigentlich, hatte ich nicht getestet. Ein Whoops sollte dann trotzdem nicht ausgelöst werden, sondern eine Fehlermeldung erscheinen.

**Comment by alexplusde** [comment]
scheint gelöst zu sein. 

@tyrant88 schreib am besten `closes #issuenummer` in den PR, damit das Issue automatisch geschlossen wird.
