### ISSUE TITLE
Datenbank-Speicherengine und -Kollation an Core anpassen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#223]
bei search_it aktuell:

![image](https://user-images.githubusercontent.com/3855487/68299234-994b4800-009b-11ea-8ac6-243d3cea7102.png)

soll: 

InnoDB | utf8mb4_general_ci

**Comment by tyrant88** [comment]
Ich hab die install.php neugemacht, die Tabelle werden dadurch automatisch vom Typ innoDB sein, wenn neu installiert wird.
Bei utf8mb4 bin ich noch nicht im Thema. (Auch nach Rücksprache mit Gregor, die Umstellung der Collation auf mb4 ist ja im Core noch nicht gemacht)

**Comment by alexplusde** [comment]
Okay. Ich werde mir die Tabellen vom Add-on Mal genauer anschauen und kann dir dann ziemlich sicher mitteilen, wenn es erwartbare Probleme gäbe.

**Comment by alexplusde** [comment]
@gharlan würde mit `ensure()` automatisch das ganze angepasst werden?

**Comment by gharlan** [comment]
Nein, die prüft rex_sql_table nicht, und ändert sie auch nicht.

**Comment by alexplusde** [comment]
Laut 5.9 soll: `utf8mb4_unicode_ci` (nicht `...general_ci`)

**Comment by alexplusde** [comment]
Seltsam. Gerade installiert und alles bereits korrekt. 
![image](https://user-images.githubusercontent.com/3855487/79247684-1c5aa080-7e7b-11ea-895d-dd6cfbc5684b.png)
