### ISSUE TITLE
Datenbankspalten werden immer sprachunabhängig indexiert.

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/search_it#228]
Wenn man Felder einer Datenbanktabelle in den Suchindex aufnimmt, landen die keywords in der Tabelle search_it_keywords immer mit dem Eintrag clang = -1.
In den Suchergebnissen lassen sich die Fundstellen zwar rausfischen.
Beispiel:
```
$otherlang = rex_clang::getCurrentId() == 1 ? '2' : '1';
$search_it->setWhere("`fcolumn` NOT LIKE '%_".$otherlang."'");
```
Anmerkung: Beispiel funktioniert nur wenn die jeweiligen Felder mit den Sprachsuffixen _1 und _2 benannt sind und es nur zwei Sprachen gibt.
Wenn man aber beispielsweise autosuggest verwendet, das die search_it_keywords Tabelle und den jeweiligen clang Eintrag nutzt, bekommt man auch Vorschläge aus anderen Sprachen.

**Comment by alexplusde** [comment]
Ich schätze, Xong wird sich dazu nochmal melden, aber das ist ein beabsichtigtes Verhalten. Vereinfacht gesagt: Die Indexierung soll immer so viele Daten wie möglich vorhalten. Indexierung != Suche.

Bei der Suche sollen dann gewählte Parameter dafür sorgen, dass nur der Teil des Index ausgegeben wird, der relevant ist.

Dein Beispiel ist doch ein super Trick! In der Doku gibt es schon ein paar Worte zur Mehrsprachigkeit, da könntest du dein Beispiel oben erläutern und einfügen.

**Comment by alexplusde** [comment]
#242
