### ISSUE TITLE
Kein automatischer ReIndex bei Contentänderung in Verbindung mit Version-Addon

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/search_it#229]
Hallo,
search_it macht keinen automatischen ReIndex, wenn das Version-Addon aktiv ist und Änderungen am Content vorgenommen werden.

Die in der boot.php aufgeführten ExtensionPoints für die Contentänderung werden sofort aufgerufen, so dass die eben erfolgten Änderungen noch nicht live sind und daher der "alte" Content reindexiert wird.

Es müsste noch ein EP rein, welcher nach der Liveschaltung des Artikels einen ReIndex ausführt.

**Comment by tyrant88** [comment]
Ah, interesant. Eine konzeptionelle Lücke bei "automatischem Reindexieren". 
Als noch der Artikelinhalt und nicht über das Frontend indexiert wurde, passte das.

Hmm. Wie geht denn das Version-AddOn vor? Ändert das die Artikel? Müsste das nicht den "EDIT"-Extensionpoint triggern?
Als work-around ist im Moment nur ein cronjob möglich.

**Comment by iceman-fx** [comment]
Soweit ich weiß, legt das Version-Addon eine Kopie des Artikels an, in welchem alle Contentänderungen dann std.mäßig durchgeführt werden.
Beim Liveschalten wird der Inhalt der Kopie dann dem Hauptartikel zugewiesen.

Den Edit-EP anzutriggern würde nicht viel bringen, da die geänderten Daten zu diesem Zeitpunkt nicht im Hauptartikel drin sind.
Man müsste jetzt raus bekommen, ob das Version-Addon eigene EPs mitbringt, an welche man sich hängen kann,

**Comment by tyrant88** [comment]
Was ich meinte ist, beim Liveschalten müsste es den EDIT triggern, weil ab dann ja der neue Inhalt (eventuell) online also übers FE erreichbar ist.

**Comment by iceman-fx** [comment]
Sollte man da noch ein Issue beim Version-Plugin öffnen?

**Comment by iceman-fx** [comment]
Hast Du für den Workaround mittels Cronjob zufällig eine kurze Anleitung?

**Comment by tyrant88** [comment]
search it installiert einen vorgefertigten cronjob-Typ für das cronjob AddOn.

**Comment by alexplusde** [comment]
Ich glaube ja, denn konzeptionell wäre das da korrekt aufgehoben - auch andere Addons könnten ja auf den Aufruf des EP warten und es findet ja eine Form von Editierung statt.

**Comment by alexplusde** [comment]
@iceman-fx @lus für REDAXO 5.9 sind die Voraussetzungen geschaffen. Möchte jemand den PR dazu hier machen?

@gharlan sollte man die redaxo Version ab prüfen, oder ist das kein Problem, wenn der EP in R5.8 (und älter) nicht existiert?

**Comment by gharlan** [comment]
> @gharlan sollte man die redaxo Version ab prüfen, oder ist das kein Problem, wenn der EP in R5.8 (und älter) nicht existiert?

Ist kein Problem

**Comment by gharlan** [comment]
Wobei: search_it hängt sich vermutlich aktuell an SLICE_ADDED/UPDATED/DELETED?
Wenn es sich zukünftig an ART_CONTENT_UPDATED hängt, sind die anderen eigentlich nicht mehr notwendig, ansonsten wird der Code ja doppelt ausgeführt.
Daher eventuell doch versionsbasiert arbeiten.

**Comment by tyrant88** [comment]
Ja und ja. Und deshalb: ja.

**Comment by alexplusde** [comment]
Dieser PR wäre nun bereit gelöst zu werden:
https://github.com/redaxo/redaxo/pull/3191

**Comment by tyrant88** [comment]
Problem dabie, das es uns auf REDAXO 5.9 zwingt was ich gar nicht mag

**Comment by alexplusde** [comment]
Kann man dafür keine Weiche bauen?

**Comment by alexplusde** [comment]
Ist im Branch für die kommende Version 7.0 - wird dann erst ab R5.9 kompatibel sein.
