### ISSUE TITLE
Min-php version in package.yml notieren

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/search_it#232]

**Comment by tyrant88** [comment]
hmmm...
mit 5.6 lief es auf jeden Fall noch...

**Comment by staabm** [comment]
aufgrund der min redaxo version ergibt sich ja auch schon eine min-php version.. d.h. es könnte sein dass du auch schon ^7.0 hast.

mir gehts gar nicht darum welche es ist, nur dass eine definiert ist, ist wichtig

**Comment by tyrant88** [comment]
ist mir klar.
Ich hätte es nur eigentlich gerne niedrig...
min REDAXO steht noch auf 5.3... 

ich denk mir was aus.

**Comment by staabm** [comment]
ggf. mittels https://github.com/llaville/php-compat-info ermitteln

**Comment by staabm** [comment]
oder du machst hier einen travis build und lässt es testen auf php X.Y.Z

**Comment by tyrant88** [comment]
ähhh...what?

**Comment by staabm** [comment]
z.b. https://github.com/FriendsOfREDAXO/linter einbinden (siehe readme dort) und dann von travis das repo gegen alle php versionen testen lassen.. damit siehste dann ob es von 5.6-7.x taugt

**Comment by tyrant88** [comment]
alright!

Extensions Analysis

    Extension  Matches REF      EXT min/Max     PHP min/Max PHP all
    Core               Core     5.3.0           5.3.0
    date               date     4.0.0           4.0.0
    gd                 gd       4.3.2           4.3.2
    iconv              iconv    4.0.5           4.0.5
    json               json     5.2.0           5.2.0
    mbstring           mbstring 4.3.0           4.3.0
    pcre               pcre     4.3.0           4.3.0
    standard           standard 5.0.0           5.0.0
    xml                xml      4.0.0 => 7.1.25 4.0.0
    zlib               zlib     4.0.1           4.0.1
    Total [10]                                  5.3.0

Namespaces Analysis

    Namespace Matches REF  EXT min/Max PHP min/Max PHP all
    +global           Core             5.5.0
    Total [1]                          5.5.0

No interface found

No trait found

Classes Analysis

    Class                                          Matches REF  EXT min/Max PHP min/Max PHP all
    PHPlot                                         8       user             5.0.0
    PHPlot_truecolor                                       user             4.0.0
    pdf2txt                                        1       user             5.3.0
  U rex                                            60      user             4.0.0
  U rex_addon                                      55      user             4.0.0
  U rex_api_function                               1       user             4.0.0
    rex_api_search_it_autocomplete_getSimilarWords         user             5.0.0
  U rex_article                                    6       user             4.0.0
  U rex_article_content                            1       user             4.0.0
  U rex_be_controller                              1       user             4.0.0
  U rex_category                                   1       user             4.0.0
  U rex_clang                                      8       user             4.0.0
  U rex_content_service                            1       user             4.0.0
  U rex_cronjob                                    1       user             4.0.0
  U rex_cronjob_manager                            1       user             4.0.0
    rex_cronjob_reindex                                    user             5.4.0
  U rex_dir                                        2       user             4.0.0
  U rex_extension                                  14      user             4.0.0
  U rex_extension_point                            4       user             4.0.0
  U rex_file                                       8       user             4.0.0
  U rex_finder                                     1       user             4.0.0
  U rex_fragment                                   35      user             4.0.0
  U rex_i18n                                       25      user             4.0.0
  U rex_logger                                     7       user             4.0.0
 CU rex_markdown                                   2       user             4.0.0
  U rex_path                                       9       user             4.0.0
  U rex_plugin                                     6       user             4.0.0
  U rex_select                                     2       user             4.0.0
  U rex_socket                                     2       user             4.0.0
  U rex_sql                                        40      user             4.0.0
  U rex_sql_column                                 30      user             4.0.0
  U rex_sql_index                                  5       user             4.0.0
  U rex_sql_table                                  6       user             4.0.0
  U rex_textile                                    1       user             4.0.0
  U rex_url                                        10      user             4.0.0
  U rex_view                                       28      user             4.0.0
  U rex_yrewrite                                   1       user             4.0.0
    search_it                                      12      user             5.4.0
    search_it_stats                                7       user             4.0.7
    self                                           3       Core 5.0.0       5.0.0
    simple_html_dom                                5       user             5.0.0
    simple_html_dom_node                           4       user             5.0.0
    Total [42]                                                              5.4.0

Functions Analysis

    Function                                        Matches REF      EXT min/Max     PHP min/Max
    Header                                          2       standard 4.0.0           4.0.0
    ImageArc                                        1       gd       4.0.0           4.0.0
    ImageCreateFromGIF                              1       gd       4.0.0           4.0.0
    ImageCreateFromJPEG                             1       gd       4.0.0           4.0.0
    ImageCreateFromPNG                              1       gd       4.0.0           4.0.0
    ImageFilledArc                                  2       gd       4.0.6           4.0.6
    ImageFilledEllipse                              2       gd       4.0.6           4.0.6
    ImageFilledPolygon                              11      gd       4.0.0           4.0.0
    ImageFilledRectangle                            10      gd       4.0.0           4.0.0
    ImageFontHeight                                 1       gd       4.0.0           4.0.0
    ImageFontWidth                                  1       gd       4.0.0           4.0.0
    ImageLine                                       36      gd       4.0.0           4.0.0
    ImagePolygon                                    2       gd       4.0.0           4.0.0
    ImageRectangle                                  4       gd       4.0.0           4.0.0
    ImageSetThickness                               6       gd       4.0.6           4.0.6
    ImageTTFBBox                                    2       gd       4.0.0           4.0.0
    ImageTTFText                                    1       gd       4.0.0           4.0.0
    abs                                             6       standard 4.0.0           4.0.0
    addcslashes                                     3       standard 4.0.0           4.0.0
    array_diff                                      4       standard 4.0.1           4.0.1
    array_diff_assoc                                16      standard 4.3.0           4.3.0
    array_fill                                      6       standard 4.2.0           4.2.0
    array_key_exists                                29      standard 4.0.7           4.0.7
    array_keys                                      7       standard 4.0.0           4.0.0
    array_map                                       32      standard 4.0.6           4.0.6
    array_merge                                     16      standard 4.0.0           4.0.0
    array_push                                      5       standard 4.0.0           4.0.0
    array_reverse                                   2       standard 4.0.0           4.0.0
    array_shift                                     4       standard 4.0.0           4.0.0
    array_slice                                     1       standard 4.0.0           4.0.0
    array_splice                                    3       standard 4.0.0           4.0.0
    array_sum                                       2       standard 4.0.4           4.0.4
    array_unique                                    2       standard 4.0.1           4.0.1
    array_unshift                                   1       standard 4.0.0           4.0.0
    array_values                                    1       standard 4.0.0           4.0.0
    base64_encode                                   2       standard 4.0.0           4.0.0
    basename                                        2       standard 4.0.0           4.0.0
    call_user_func                                  3       standard 4.0.0           4.0.0
    call_user_func_array                            8       standard 4.0.4           4.0.4
    ceil                                            10      standard 4.0.0           4.0.0
    chr                                             1       standard 4.0.0           4.0.0
    chunk_split                                     1       standard 4.0.0           4.0.0
    class_exists                                    1       Core     4.0.0           4.0.0
    closure-253-258                                         user                     5.3.0
    closure-45-52                                           user                     5.3.0
    closure-762-765                                         user                     5.3.0
    color_range                                     3       user                     4.0.0
    compact                                         6       standard 4.0.0           4.0.0
    cos                                             3       standard 4.0.0           4.0.0
    count                                           76      standard 4.0.0           4.0.0
    count_data_sets                                 2       user                     4.0.0
    date                                            8       date     4.0.0           4.0.0
    define                                          37      Core     4.0.0           4.0.0
    defined                                         1       Core     4.0.0           4.0.0
    deg2rad                                         3       standard 4.0.0           4.0.0
    draw_data_table                                 4       user                     4.2.0
    dump                                            2       user                     4.0.0
    dump_html_tree                                  2       user                     4.0.0
    error_reporting                                 1       Core     4.0.0           4.0.0
    escapeshellarg                                  2       standard 4.0.3           4.0.3
 C  exec                                            1       standard 4.0.0           4.0.0
    explode                                         16      standard 4.0.0           4.0.0
    extract                                         10      standard 4.0.0           4.0.0
    file_exists                                     2       standard 4.0.0           4.0.0
    file_get_contents                               2       standard 4.3.0           4.3.0
    file_get_dom                                            user                     4.0.4
    file_get_html                                           user                     4.0.4
    file_put_contents                               2       standard 5.0.0           5.0.0
    floor                                           7       standard 4.0.0           4.0.0
    flush                                           2       standard 4.0.0           4.0.0
    func_get_args                                   11      Core     4.0.0           4.0.0
    function_exists                                 2       Core     4.0.0           4.0.0
    fwrite                                          1       standard 4.0.0           4.0.0
    get_class                                       3       Core     4.0.0           4.0.0
    get_object_vars                                 1       Core     4.0.0           4.0.0
    getimagesize                                    1       standard 4.0.0           4.0.0
    gmdate                                          1       date     4.0.0           4.0.0
    gzuncompress                                    1       zlib     4.0.1           4.0.1
    header                                          7       standard 4.0.0           4.0.0
    hexdec                                          7       standard 4.0.0           4.0.0
    highlight_string                                1       standard 4.0.0           4.0.0
    html_entity_decode                              1       standard 4.3.0           4.3.0
    htmlentities                                    3       standard 4.1.0           4.1.0
    iconv                                           3       iconv    4.0.5           4.0.5
    imagecolorresolve                               7       gd       4.0.0           4.0.0
    imagecolorresolvealpha                          2       gd       4.0.6           4.0.6
    imagecolortransparent                           1       gd       4.0.0           4.0.0
    imagecopy                                       2       gd       4.0.0           4.0.0
    imagecopyresampled                              1       gd       4.0.6           4.0.6
    imagecreate                                     3       gd       4.0.0           4.0.0
    imagedestroy                                    3       gd       4.0.0           4.0.0
    imagefilledrectangle                            1       gd       4.0.0           4.0.0
    imagefontheight                                 1       gd       4.0.0           4.0.0
    imagefontwidth                                  1       gd       4.0.0           4.0.0
    imageistruecolor                                1       gd       4.3.2           4.3.2
    imageline                                       30      gd       4.0.0           4.0.0
    imagepng                                        2       gd       4.0.0           4.0.0
    imagerectangle                                  4       gd       4.0.0           4.0.0
    imagesetstyle                                   1       gd       4.0.6           4.0.6
    imagesetthickness                               15      gd       4.0.6           4.0.6
    imagestring                                     1       gd       4.0.0           4.0.0
    imagettfbbox                                    4       gd       4.0.0           4.0.0
    imagetypes                                      1       gd       4.0.2           4.0.2
    implode                                         49      standard 4.0.0           4.0.0
    in_array                                        21      standard 4.0.0           4.0.0
    intval                                          54      standard 4.0.0           4.0.0
    is_array                                        51      standard 4.0.0           4.0.0
    is_dir                                          11      standard 4.0.0           4.0.0
    is_file                                         1       standard 4.0.0           4.0.0
    is_int                                          3       standard 4.0.0           4.0.0
    is_null                                         19      standard 4.0.4           4.0.4
    is_numeric                                      31      standard 4.0.0           4.0.0
    is_object                                       1       standard 4.0.0           4.0.0
    is_readable                                     1       standard 4.0.0           4.0.0
    is_string                                       4       standard 4.0.0           4.0.0
    json_decode                                     1       json     5.2.0           5.2.0
    json_encode                                     3       json     5.2.0           5.2.0
    ksort                                           3       standard 4.0.0           4.0.0
    localeconv                                      1       standard 4.0.0           4.0.0
    log                                             1       standard 4.0.0           4.0.0
    log10                                           9       standard 4.0.0           4.0.0
    ltrim                                           2       standard 4.0.0           4.0.0
    max                                             35      standard 4.0.0           4.0.0
    mb_detect_encoding                              1       mbstring 4.0.6           4.0.6
    mb_strlen                                       4       mbstring 4.0.6           4.0.6
    mb_strtolower                                   2       mbstring 4.3.0           4.3.0
    md5                                             1       standard 4.0.0           4.0.0
    metaphone                                       4       standard 4.0.0           4.0.0
    microtime                                       3       standard 5.0.0           5.0.0
    min                                             20      standard 4.0.0           4.0.0
    mktime                                          3       date     4.0.0           4.0.0
    mt_rand                                         2       standard 4.0.0           4.0.0
    mt_srand                                        1       standard 4.0.0           4.0.0
    number_format                                   3       standard 4.0.0           4.0.0
    ob_clean                                        4       standard 4.2.0           4.2.0
    ob_end_clean                                    2       standard 4.0.0           4.0.0
    ob_get_clean                                    5       standard 4.3.0           4.3.0
    ob_get_length                                   1       standard 4.0.2           4.0.2
    ob_start                                        3       standard 4.0.0           4.0.0
    octdec                                          2       standard 4.0.0           4.0.0
    parse_url                                       1       standard 4.0.0           4.0.0
    pow                                             8       standard 4.0.0           4.0.0
    preg_match                                      21      pcre     4.0.0           4.0.0
    preg_match_all                                  6       pcre     4.0.0           4.0.0
    preg_quote                                      9       pcre     4.0.0           4.0.0
    preg_replace                                    19      pcre     4.0.0           4.0.0
    preg_replace_callback                           2       pcre     4.0.5           4.0.5
    preg_split                                      9       pcre     4.0.0           4.0.0
    print_r                                         3       standard 4.0.0           4.0.0
    prune_labels                                    2       user                     4.0.0
    rand                                            3       standard 4.0.0           4.0.0
    range                                           1       standard 4.0.0           4.0.0
    rex_escape                                      31      user                     4.0.0
    rex_get                                         34      user                     4.0.0
    rex_getUrl                                      2       user                     4.0.0
    rex_post                                        16      user                     4.0.0
    rex_request                                     21      user                     4.0.0
 C  rex_textile::parse                                      user                     4.0.0
    rex_warning                                     1       user                     4.0.0
    rgb                                             2       user                     4.0.0
    round                                           2       standard 4.0.0           4.0.0
    rtrim                                           1       standard 4.0.0           4.0.0
    scandir                                         4       standard 5.0.0           5.0.0
    search_it_config_unserialize                    1       user                     4.0.0
    search_it_doPlaintext                                   user                     5.5.0
    search_it_getArticleIds                         1       user                     4.0.0
    search_it_getArticles                           4       user                     4.0.0
    search_it_getCategories                         1       user                     4.0.0
    search_it_getDirs                               3       user                     5.0.0
    search_it_getFiles                              2       user                     5.0.0
    search_it_getPlaintext                          1       user                     5.5.0
    search_it_getSettingsFormSection                20      user                     5.4.0
    search_it_getStatSection                                user                     4.0.0
    search_it_handle_extensionpoint                         user                     4.0.0
    search_it_reindex_cols                                  user                     4.0.7
    search_it_search_highlighter_getHighlightedText 1       user                     5.3.0
    search_it_search_highlighter_output                     user                     4.0.0
    search_it_stats_addtruncate                             user                     4.0.0
    search_it_stats_bytesize                        4       user                     4.0.0
    search_it_stats_storekeywords                           user                     4.0.0
    serialize                                       3       standard 4.0.0           4.0.0
    setlocale                                       3       standard 4.0.0           4.0.0
    sin                                             3       standard 4.0.0           4.0.0
    sort                                            1       standard 4.0.0           4.0.0
    soundex                                         4       standard 4.0.0           4.0.0
    soundex_ger                                     4       user                     5.0.0
    sprintf                                         43      standard 4.0.0           4.0.0
    str_get_dom                                             user                     4.0.0
    str_get_html                                            user                     4.0.0
    str_ireplace                                    1       standard 5.0.0           5.0.0
    str_repeat                                      3       standard 4.0.0           4.0.0
    str_replace                                     14      standard 4.0.0           4.0.0
    str_split                                       2       standard 5.0.0           5.0.0
    strcasecmp                                      3       Core     4.0.0           4.0.0
    strcmp                                          1       Core     4.0.0           4.0.0
    strcspn                                         1       standard 4.0.0           4.0.0
    strftime                                        1       date     4.0.0           4.0.0
    strip_tags                                      2       standard 4.0.0           4.0.0
    stripslashes                                    6       standard 4.0.0           4.0.0
    strlen                                          22      Core     4.0.0           4.0.0
    strpos                                          18      standard 4.0.0           4.0.0
    strrpos                                         2       standard 4.0.0           4.0.0
    strspn                                          2       standard 4.0.0           4.0.0
    strtolower                                      21      standard 4.0.0           4.0.0
    strtoupper                                      3       standard 4.0.0           4.0.0
    strtr                                           1       standard 4.0.0           4.0.0
    substr                                          29      standard 4.0.0           4.0.0
    substr_count                                    5       standard 4.0.0           4.0.0
    substr_replace                                  1       standard 4.0.0           4.0.0
    tempnam                                         1       standard 4.0.0           4.0.0
    test                                            5       user                     4.0.0
    test_color_range                                3       user                     4.0.0
    test_count_data_sets                            8       user                     4.0.0
    test_driver_color_range                         1       user                     4.0.0
    test_driver_count_data_sets                     1       user                     4.0.0
    time                                            1       date     4.0.0           4.0.0
    trigger_error                                   3       Core     4.0.1           4.0.1
    trim                                            16      standard 4.0.0           4.0.0
    unlink                                          1       standard 4.0.0           4.0.0
    unserialize                                     3       standard 4.0.0           4.0.0
    urlencode                                       4       standard 4.0.0           4.0.0
    usage                                           2       user                     4.3.0
    utf8_decode                                     5       xml      4.0.0 => 7.1.25 4.0.0
    utf8_encode                                     4       xml      4.0.0 => 7.1.25 4.0.0
    wordwrap                                        1       standard 4.0.2           4.0.2
    Total [225]                                                                      5.5.0

Constants Analysis

    Constant                            Matches REF      EXT min/Max PHP min/Max
    DIRECTORY_SEPARATOR                 2       standard 4.0.6       4.0.6
    ENT_COMPAT                          3       standard 4.0.0       4.0.0
    ENT_QUOTES                          1       standard 4.0.0       4.0.0
    EXTR_PREFIX_ALL                     1       standard 4.0.0       4.0.0
    E_USER_ERROR                        1       Core     4.0.0       4.0.0
    FALSE                               115     Core     4.0.0       4.0.0
    False                               8       Core     4.0.0       4.0.0
    HDOM_INFO_BEGIN                     9       user                 4.0.0
    HDOM_INFO_END                       18      user                 4.0.0
    HDOM_INFO_ENDSPACE                  3       user                 4.0.0
    HDOM_INFO_INNER                     7       user                 4.0.0
    HDOM_INFO_OUTER                     3       user                 4.0.0
    HDOM_INFO_QUOTE                     6       user                 4.0.0
    HDOM_INFO_SPACE                     5       user                 4.0.0
    HDOM_INFO_TEXT                      18      user                 4.0.0
    HDOM_QUOTE_DOUBLE                   3       user                 4.0.0
    HDOM_QUOTE_NO                       2       user                 4.0.0
    HDOM_QUOTE_SINGLE                   2       user                 4.0.0
    HDOM_TYPE_COMMENT                   2       user                 4.0.0
    HDOM_TYPE_ELEMENT                   1       user                 4.0.0
    HDOM_TYPE_ENDTAG                            user                 4.0.0
    HDOM_TYPE_ROOT                      1       user                 4.0.0
    HDOM_TYPE_TEXT                      4       user                 4.0.0
    HDOM_TYPE_UNKNOWN                   2       user                 4.0.0
    IMAGETYPE_GIF                       1       standard 4.0.0       4.0.0
    IMAGETYPE_JPEG                      1       standard 4.0.0       4.0.0
    IMAGETYPE_PNG                       1       standard 4.0.0       4.0.0
    IMG_ARC_EDGED                       1       gd       4.0.0       4.0.0
    IMG_ARC_NOFILL                      1       gd       4.0.0       4.0.0
    IMG_ARC_PIE                         2       gd       4.0.0       4.0.0
    IMG_COLOR_STYLED                    1       gd       4.0.0       4.0.0
    IMG_COLOR_TRANSPARENT               1       gd       4.0.0       4.0.0
    IMG_GIF                             1       gd       4.0.0       4.0.0
    IMG_JPG                             1       gd       4.0.0       4.0.0
    IMG_PNG                             1       gd       4.0.0       4.0.0
    IMG_WBMP                            1       gd       4.0.0       4.0.0
    LC_NUMERIC                          3       standard 4.0.0       4.0.0
    NULL                                127     Core     4.0.0       4.0.0
    PREG_OFFSET_CAPTURE                 1       pcre     4.3.0       4.3.0
    PREG_SET_ORDER                      6       pcre     4.0.0       4.0.0
    PREG_SPLIT_DELIM_CAPTURE            4       pcre     4.0.5       4.0.5
    PREG_SPLIT_NO_EMPTY                 3       pcre     4.0.0       4.0.0
    SEARCH_IT_ART_404                   2       user                 4.0.0
    SEARCH_IT_ART_ERROR                 2       user                 4.0.0
 C  SEARCH_IT_ART_EXCLUDED              2       user                 4.0.0
    SEARCH_IT_ART_GENERATED             2       user                 4.0.0
    SEARCH_IT_ART_IDNOTFOUND            2       user                 4.0.0
    SEARCH_IT_ART_NOTOK                 2       user                 4.0.0
    SEARCH_IT_ART_REDIRECT              2       user                 4.0.0
    SEARCH_IT_FILE_EMPTY                2       user                 4.0.0
    SEARCH_IT_FILE_FORBIDDEN_EXTENSION  2       user                 4.0.0
    SEARCH_IT_FILE_GENERATED            2       user                 4.0.0
    SEARCH_IT_FILE_NOEXIST              5       user                 4.0.0
    SEARCH_IT_FILE_XPDFERR_OPENDEST     2       user                 4.0.0
    SEARCH_IT_FILE_XPDFERR_OPENSRC      2       user                 4.0.0
    SEARCH_IT_FILE_XPDFERR_OTHER        2       user                 4.0.0
    SEARCH_IT_FILE_XPDFERR_PERM         2       user                 4.0.0
    SEARCH_IT_SIMILARWORDS_ALL          2       user                 4.0.0
    SEARCH_IT_SIMILARWORDS_COLOGNEPHONE 4       user                 4.0.0
    SEARCH_IT_SIMILARWORDS_METAPHONE    4       user                 4.0.0
    SEARCH_IT_SIMILARWORDS_NONE         2       user                 4.0.0
    SEARCH_IT_SIMILARWORDS_SOUNDEX      4       user                 4.0.0
    STDERR                              1       Core     4.3.0       4.3.0
    TRUE                                234     Core     4.0.0       4.0.0
    True                                1       Core     4.0.0       4.0.0
    __DIR__                             7       Core     5.3.0       5.3.0
    __FUNCTION__                        42      Core     4.3.0       4.3.0
    false                               210     Core     4.0.0       4.0.0
    null                                59      Core     4.0.0       4.0.0
    true                                109     Core     4.0.0       4.0.0
    Total [70]                                                       5.3.0

Conditions Analysis

    Condition                           Matches REF      EXT min/Max PHP min/Max
    class_exists(rex_markdown)          1       user                 4.0.0
    defined(SEARCH_IT_ART_EXCLUDED)     1       user                 4.0.0
    function_exists(exec)               1       standard 4.0.0       4.0.0
    function_exists(rex_textile::parse) 1       user                 4.0.0
    Total [4]                                                        4.0.0

Requires PHP 5.5.0 (min), PHP 5.5.0 (all)

**Comment by alexplusde** [comment]
krasser shit
