### ISSUE TITLE
Sucheingabe / Suchergebnisse als Fragment

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/search_it#258]
Als Alternative zur sehr ausführlichen Doku. Die Beispiele können dann eingedampft werden.

**Comment by alxndr-w** [comment]
Meine jetzige Planung sieht keine sich selbständigen Module vor, sondern die REX_VAR-Variante vom consent_manager, die ein Fragment ausgibt.

**Comment by tyrant88** [comment]
Hmmm. Dann sollten wir über die Planung noch mal reden ;-) ;-)
Ein Modul anzupassen ist für Anfänger leichter, als ein Fragment. Da möchte ich noch mal drüber nachdenken.

**Comment by alxndr-w** [comment]
Kann ja jeder machen, wie er möchte. Der Code wird immer auch über die Doku offengelegt.
