### ISSUE TITLE
Ziel-URL als Feld in Treffer mit aufnehmen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/search_it#273]
Wie bereits besprochen fände ich es sinnvoll, wenn in im Treffer-Array ($hit) bereits die Ziel-URL zur Ausgabe liegt, um diese nicht mehr selbst bauen zu müssen. Bei der Indexierung muss demzufolge Search_it dieses Feld befüllen.

**Comment by tyrant88** [comment]
halte ich nicht für sinnvoll. URL könnte sich geändert haben.

**Comment by alexplusde** [comment]
Wenn sich die URL geändert hat, wäre auch der Index zu aktualisieren.

**Comment by tyrant88** [comment]
eben nicht! 
Wenn sich ein Artikel nicht geändert hat, man aber die URL dazu ändert, warum sollte dann der Index neuaufgebaut werden?

**Comment by alexplusde** [comment]
Änderungen der URL könnten bewirken, dass Links in anderen Seiten und damit auch deren Content verändert hat, bspw. durch Änderung des Artikelnamens

**Comment by tyrant88** [comment]
Schön, dass du es einsiehst! ;-)

**Comment by alexplusde** [comment]
Da hast du mich missverstanden :P

**Comment by alexplusde** [comment]
Lass uns bitte dazu nochmal auch den Bereich der Doku anschauen, an dem ich dir gerne deutlich machen möchte, warum das im Standardfall eine Verbesserung ist. Danach lass ich mich auch überreden, hier zuzumachen.
