### ISSUE TITLE
Fehler beim Anlegen der neuen Tabellen mit "tmp"

### ISSUE THREAD

**Issue by rolandsee** [FriendsOfREDAXO/search_it#280]
Hi, ich habe in zwei Redaxo 5.10 Installationen das AddOn search_it v.6.6.0 auf v.6.7.0 aktualisiert und anschließend folgende Whoops bekommen:

`Error while executing statement "INSERT INTO `rex_tmp_search_it_stats_searchterms` SET `term` = :term, `time` = :time, `resultcount` = :resultcount" using params {"term":"stellenangebot","time":"2020-04-29 12:41:07","resultcount":3}! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydatabase.rex_tmp_search_it_stats_searchterms' doesn't exist`

Ich habe zur Behebung des Fehlers die betroffene Tabelle per Hand umbenannt. 
Ist das bisher nur mir passiert?

**Comment by tyrant88** [comment]
Ja und nein. @alexplusde hat mir schon ein issue geschrieben #279 . Ich fixe es sobald ich kann.

**Comment by alexplusde** [comment]
Duplicate #279
