### ISSUE TITLE
Statische Methoden greifen auf private Klassenvariablen zu

### ISSUE THREAD

**Issue by xong** [FriendsOfREDAXO/search_it#287]
Die Methoden getMinFID UND getMaxFID sollten nicht statisch sein (wenn sie auf nicht statische Klassenmember zugreifen müssen).
https://github.com/FriendsOfREDAXO/search_it/blob/cdd4aeef16b373787fc90f4aee8562bfb384b77b/lib/search_it.php#L1019-L1039

**Comment by tyrant88** [comment]
Okay. Hab mich mal in Thematik reingedacht. Ich würde dazu tendieren `tablePrefix, tempTablePrefix, urlAddOnTableName` zu statischen Klassenmebern zu machen.
