### ISSUE TITLE
Beispiel-Module: URL Ausgabe bei Nutzung von yrewrite in einer Multidomain Umgebung fehlerhaft

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/search_it#314]
`rex_getUrl()` gibt bei der aktuellen Domain die relative Url aus (deshalb ist in den Beispielen `$hit_server` vorangestellt. Wenn im Multidomainumfeld auf eine andere Domain verwiesen wird, gibt `rex_getUrl()` jedoch die absolute Url aus. Daher wird die Domain in dem Fall doppelt ausgegeben.
Die Ausgabe über `rex_yrewrite::getFullUrlByArticleId($hit['fid'], $hit['clang'], array('search_highlighter' => $request))` löst das Problem.

**Comment by tyrant88** [comment]
die 7.0 kommt bald, dafür werden auch noch mal die Beispiele überarbeitet, da kommt das auf jeden Fall mit rein.

**Comment by alxndr-w** [comment]
PR welcome

**Comment by marcohanke** [comment]
PR war unerwünscht @alxndr-w

**Comment by tyrant88** [comment]
Oh man! Du Unglückswurm! ;-)
Wir haben gerade auf slack diskutiert, dass ich keinen PR wollte.

**Comment by alxndr-w** [comment]
Das konnte ich nicht wissen. 🤷‍♂️

Fände es aber auch geiler, wenn die Beispiele allesamt stimmen würden.

**Comment by tyrant88** [comment]
Genau darum geht es ja. Deine Überlegung war ja sogar auch, auf ein instaliertes Modul zu wechslen... gerade dann muss das ja alles gut überlegt sein. Wenn wir den Leuten schon was vorschreiben, dann auch richtig :-)

**Comment by alxndr-w** [comment]
Das Beispiel ist ja nicht falsch - und bezieht sich auf Installationen ohne Multidomain-Kontext. Das kurz anzupassen ist, finde ich, kein Problem.

Da kein PR möglich und keine 7.0.0 in Sicht, mache ich hier mal zu.
