### ISSUE TITLE
Nach Einspielen eines Backups muss die Tabelle neu angelegt werden

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/search_it#316]
Ich glaube, das betrifft auch hier unsere Temp-Tabellen, analog zu https://github.com/FriendsOfREDAXO/yform_spam_protection/issues/31

Da diese nicht im Backup landen, fehlen sie hinterher.

**Comment by tyrant88** [comment]
Die Temp-Tabellen waren mir noch nie sympathisch.

**Comment by alxndr-w** [comment]
Es ist schon der richtige Ansatz, die Daten nicht mit im Backup zu haben - die Schema-Definition hingegen wäre wünschenswert.
