### ISSUE TITLE
Aktuelles Release

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/search_it#317]
- Die aktuelle Installer-Release lässt sich nicht unter PHP8 installieren. 
- Die GitHub-Version schon. 

@tyrant88 machst du - oder ich?

**Comment by tyrant88** [comment]
hab ich gerade keinen Kopf für ...

**Comment by skerbis** [comment]
dann mach ich eben.

**Comment by tyrant88** [comment]
?Häh

**Comment by tyrant88** [comment]
Was willst du denn überhaupt machen?

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/search_it/releases/tag/6.7.4
Ich habe nur die Bedingung in der Package geändert. Sonst löppt es

**Comment by tyrant88** [comment]
Ich hatte die Änderung auf PHP8 zwar abgenickt, aber Releases mache ich gerne selber.
Ihr wollt immer alle im Installer auf Update klicken. Das ist aber nicht meine Release-Politik.
Faktisch hast du vergessen den Plugins die Versionnummer zu erhöhen.
I am not amused.

**Comment by skerbis** [comment]
Ok. Reverted

**Comment by alxndr-w** [comment]
So, bin ich mal Streitschlichter: @skerbis hat im Issue vermerkt, er möchte den Release haben. Und wir sind hier bei FOR. @tyrant88 möchte sicher gehen, dass die Qualität stimmt.

Ein Satz in der README oder andernorts dokumentiert und zukünftig könnte man diesen Fehler ausschließen.

**Comment by skerbis** [comment]
Alles gut. Das war kein Streit. ich war zu voreilig.

**Comment by tyrant88** [comment]
Genau. Alles gut, hätte noch ein Smiley dahinter setzen sollen...
