### ISSUE TITLE
Updatefehler von 6.7.3 auf 6.8.8 (redaxo 5.13.0-beta2)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/search_it#324]
![image](https://user-images.githubusercontent.com/330516/141948768-17305fde-fa94-4988-8ce5-d7d20d5dc3fb.png)

**Comment by tyrant88** [comment]
Ja, da bringt 5.13 ein Problem, da muss ich mal mit @gharlan schnacken...

**Comment by tyrant88** [comment]
rex_exception thrown with message "Calling getPath on rex_null_package is not allowed"

Stacktrace:
#9 rex_exception in D:\weblocal\redaxo\redaxo\src\core\lib\packages\null.php:50
#8 rex_null_package:getPath in D:\weblocal\redaxo\redaxo\src\addons\.new.search_it\update.php:10
#7 include in D:\weblocal\redaxo\redaxo\src\core\lib\packages\package.php:285
#6 rex_package:includeFile in D:\weblocal\redaxo\redaxo\src\addons\install\lib\package\package_update.php:63
#5 rex_install_package_update:doAction in D:\weblocal\redaxo\redaxo\src\addons\install\lib\package\package_download.php:44
#4 rex_install_package_download:run in D:\weblocal\redaxo\redaxo\src\addons\install\lib\api\api_package_update.php:21
#3 rex_api_install_package_update:execute in D:\weblocal\redaxo\redaxo\src\core\lib\api_function.php:180
#2 rex_api_function:handleCall in D:\weblocal\redaxo\redaxo\src\core\backend.php:234
#1 require in D:\weblocal\redaxo\redaxo\src\core\boot.php:143
#0 require in D:\weblocal\redaxo\redaxo\index.php:9

**Comment by gharlan** [comment]
Der Fehler kommt also aus dieser Zeile: https://github.com/FriendsOfREDAXO/search_it/blob/e9d9eabae0a2934b17e6385e83412945ab188349/update.php#L10

Wenn das Plugin bereits nicht mehr existiert, ruft man dort `getPath` auf zu einer Instanz von `rex_null_package` (ein nicht existierendes Package). 
Da hatte REDAXO bisher `null` geliefert. 
Eigentlich sollte man aber bei einem nicht existierenden Package gar nicht mit den Pfaden hantieren. Vor allem wenn man nicht weiß, ob ein package oder null-package vorliegt, ist es tendenziell problematisch mit getPath zu arbeite (man denke an sowas wie `$package->getPath().'/foo'`, wo man dann plötzlich im Root `/foo` landen würde).

Bei dir ist die Zeile eigentlich aber so unproblematisch. Bin daher am überlegen, ob ich die Änderung in 5.13 rückgängig mache. Eigentlich ist die Exception aus obigen Grund mir aber sehr recht dort.
Mit PHP 8.1 wird die Zeile auch bei der bisherigen Variante eine Deprecated-Meldung erzeugen: https://3v4l.org/DWVo2
Daher wirst du die Zeile sowieso anpassen müssen. Daher wäre es ok, wenn wir die Exception drin lassen und du die Zeile anpasst?
Vorschlag:
```php
if ($addon->pluginExists('reindex')) {
    rex_dir::delete(...);
```

**Comment by tyrant88** [comment]
Kein Problem.

Ich bin beim Selbst-Debungen nicht vorwärts gekommen, weil bei mir der stacktrace (grafischer Teil) so aussah:..
![Zwischenablage-1](https://user-images.githubusercontent.com/1277494/141995690-9a9e4acb-1a2b-4457-b157-294da2d8b8d3.jpg)

**Comment by tyrant88** [comment]
Neues release --> bitte testen @olien

**Comment by olien** [comment]
Klappt. Danke!
