### ISSUE TITLE
documentation-plugin: fehlermeldung wenn backendsprache nicht deutsch

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/search_it#329]
wenn in systemeinstellungen die backendsprache nicht auf "Deutsch (de_de)" eingestellt ist, gibt es folgenden whoops:

`/redaxo/src/addons/search_it/plugins/documentation/docs/en_gb/" not found!`

**Comment by tyrant88** [comment]
Danke für den Hinweis!
