### ISSUE TITLE
Setup -> Umstellung auf utf8mb4 -> Fehler bei der Datenbankaktualisierung

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/search_it#331]
System AddOn(s) konnte nicht installiert werden
AddOn search_it konnte aus folgendem Grund nicht installiert werden:
```
SQL error: Error while executing statement "ALTER TABLE `rex_tmp_search_it_keywords` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;": SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Morgengruß-1' for key 'keyword'
```

**Comment by tyrant88** [comment]
Yo. Da gibt es in deiner Tabelle wahrscheinlich "Morgengruß" und "Morgengruss" im key Feld keyword, was unter der bisherigen collation wohl als verschieden betrachtet wurde, in utf8mb4_unicode_ci aber als gleich gilt.

**Comment by tyrant88** [comment]
Ich wüsste nicht, was search_it machen kann, um das zu verhindern.
Wenn dir auch nichts einfällt --> close

**Comment by alxndr-w** [comment]
`rex_tmp_search_it_keywords` – es könnte die Tabelle geleert werden, da temporär, oder man könnte zusammenführen.

**Comment by alxndr-w** [comment]
So käme man an die einzelnen Datensätze, um sie zu identifizieren: https://stackoverflow.com/a/71169436
