### ISSUE TITLE
Zusätzliche Datenquellen - Ausschluss/ Manipulation von diversen Zeilen

### ISSUE THREAD

**Issue by thorol** [FriendsOfREDAXO/search_it#336]
Es sollte eine Möglichkeit geben das Indexieren von zusätzlichen Datenquellen zu manipulieren bzw. einzelne Zeilen zu verhindern, z.B. mittels Extension-Point im Bereich [https://github.com/FriendsOfREDAXO/search_it/blob/master/lib/search_it.php#L777 ](https://github.com/FriendsOfREDAXO/search_it/blob/master/lib/search_it.php#L777 )

Derzeit blende ich die nicht gewünschten Ergebnisse im Suchmodul aus, jedoch wird in der Statistik die Suche als Erfolgreich angezeigt, auch wenn keine Ergebnisse anzeigt wurden. Besser wäre es, ich könnte die Indexierung dieser Zeilen verhindern. Auch der Index würde damit verkleinert werden und die Suchgeschwindigkeit vermutlich optimiert werden.

**Comment by tyrant88** [comment]
Wenn es allgemeine Kriterien sind, kannst du dir einen SQL-View mit den passenden Daten erstellen und dann diesen View als zusätzliche Datenquelle nutzen.

**Comment by thorol** [comment]
Daran hatte ich nicht gedacht, ist noch einfacher. Danke!
