### ISSUE TITLE
Re-Indexieren von yForm 4 Tabellen 

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/search_it#337]
Ich habe hier ein Redaxo 5.13.2 mit aktueller Version des search_it AddOns, dazu werkelt yForm 4.0.2 und das URL-AddOn in Version 2.

Wenn ich meine yForm-Tabelle in den Suchindex aufnehme und die Option "Reindexieren aller Spalten, wenn Tabellen mit YForm oder form bearbeitet werden" in den Einstellungen aktiviere, dann führt das zu folgendem "Fehler" beim Anlegen eines Datensatzes in der betreffenden yForm-Tabelle:
<img width="967" alt="Bildschirmfoto 2022-04-29 um 14 56 18" src="https://user-images.githubusercontent.com/10958385/166424202-2ad20a3d-f809-4e21-8f49-bf39dfdc05ea.png">

Der Datensatz wird trotzdem gespeichert, aber die Redakteure nehmen es als Fehler wahr, denn die Tabelle wird dann adrunter NICHT ausgegeben und erfordert einen neuen Klick auf die Table.

Sobald ich die Option "Reindexieren aller Spalten, wenn Tabellen mit YForm oder form bearbeitet werden" deaktiviere wird der Datensatz ohne diese Störung gespeichert und meine YFORM_DATA_LIST auch angezeigt...

Ich werde das jetzt vermutlich umgehen und das Re-indexieren per Cronjob anstoßen. Mal schauen.

Danke fürs Lesen :)

**Comment by tyrant88** [comment]
Das erste was mich stutzig macht ist, bei mir ist der Funktionsaufruf von `rex_sql->rollback()` in Zeile 462...
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/manager.php#L462

**Comment by tyrant88** [comment]
Du könntest in der Zeile davor mal den Kommentar entfernen und damit die exception dumpen.

**Comment by dpf-dd** [comment]
Das hatte ich im Zuge der Fehleranalyse gemacht. Der Dump sagt, dass das SQL-Objekt leer ist bzw. nicht existiert.
Außerdem hatte ich das gestern auch mit yForm 3.4.2 als auch mit 4.x probiert - das Problem passiert in beiden Versionen, nur die Zeilennummer ändert sich.
<img width="974" alt="bildschirmfoto_2022-04-29_um_14 56 18" src="https://user-images.githubusercontent.com/10958385/166436429-c4033305-abfb-4d76-985f-2ee29b19a6b1.png">

**Comment by dpf-dd** [comment]
OK, oben im Screenshot ist der Dump auf das sql-Object. Hier folgt jetzt der dump auf das auskommentierte $e-Object
![Bildschirmfoto 2022-05-03 um 12 21 43](https://user-images.githubusercontent.com/10958385/166437747-bd511846-83d5-439e-b199-403ef8938e72.png)

**Comment by tyrant88** [comment]
Da kann ich so schnell jetzt nix sagen. Dazu muss es ja noch an deiner Config/Tabelle liegen, da die Meldung bei uns anderen nicht auftaucht.

**Comment by dpf-dd** [comment]
Ich versuche das Problem heute Abend mal in einem jungfräulichen Redaxo nachzustellen. Allerdings wüsste ich nicht, was ich da jetzt anders mache als der Standard... Es gibt eine yForm-Tabelle mit dem Feld "headline" - woraus sich das URL-AddOn die Url generiert. Die Tabelle erscheint dann yForm-bedingt automatisch unter "Tabellen" und ich kann Datensätze anschauen, editieren und hinzufügen. Ich habe da auch keine Skripte, die sich per EP iwo einklinken - alles "nativ" verbunden (yForm - search_it - url). Ich wüsste auch gar nicht, was ich da jetzt manuell noch "abstöpseln" könnte um das möglichst "roh" zu testen... 

Aber danke erstmal für dein schnelles Feedback. Hab ja erstmal eine "Lösung" gefunden und der Kunde kann erstmal weiter damit arbeiten... :)

**Comment by fietstouring** [comment]
Habe ein ähnliches Setup und bekomme bei jedem Seitenaufruf diesen Fehler im Systemlog:
Dazu muss nur "URLs aus dem URL Addon (Version >=2) indexieren" angehakt sein.

```
rex_sql_exception | Error while executing statement "SELECT search_it.id FROM `rex_tmp_search_it_index` AS search_it LEFT JOIN `rex_url_generator_url` as url ON search_it.fid = url.url_hash WHERE texttype = 'url' AND url.id IS NULL;": SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='
-- | --
```

**Comment by tyrant88** [comment]
Dann pass doch die collations mal an.

**Comment by tyrant88** [comment]
utf8mb4_unicode_ci ist die von REDAXO empfohlene Collation.

**Comment by fietstouring** [comment]
Ich musste die Spalte **"fid"** der Tabelle **[rex_tmp_search_it_index]**(auf VARCHAR(191) umstellen, da die Konvertierung sonst nicht klappt, siehe hier https://stackoverflow.com/questions/1814532/mysql-error-1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by tyrant88** [comment]
Cool, danke.  Das hatte ich übersehen.

**Comment by xong** [comment]
Keine Ahnung, ob es damit zusammenhängt, aber seit YForm 4 hat sich auch der EP geändert: https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/action/db.php#L91
