### ISSUE TITLE
Doku: Bildersuche file-Treffer

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#34]
Dadurch funktioniert die Bildersuche nicht.

**Comment by tyrant88** [comment]
Hattest du das nicht bei der RUGRM erfolgreich gezeigt?

**Comment by alexplusde** [comment]
Nur, weil ich getrickst habe, und die Datenbankfelder zusätzlich indexieren lassen habe. Damit waren sie zwar in $hit['values'], aber nicht in $hit['filename'] und $hit['fileext'], wo sie hingehören (und ohne Datenbank-Indexierung)

**Comment by tyrant88** [comment]
gut dann schaue ich es mir an

**Comment by alexplusde** [comment]
Auch hier habe ich gerade noch mal nachgesehen, was in der Datenbank drinsteht und festgestellt, dass das Suchmodul auf die db_column-Treffer reagiert hat (ohne fileext, filename), nicht aber auf die Treffer vom Typ "file", weil etwas in den Indexierungseinstellungen nicht gepasst hat. 

Das Ganze funktioniert ordnungsgemäß und ist einfach ein Konfigurations- und damit ein Doku-Problem.

**Comment by tyrant88** [comment]
Love it

 
 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Dienstag, 27. September 2016 19:17
An: tyrant88/search_it
Cc: Norbert Micheel; Assign
Betreff: Re: [tyrant88/search_it] Bildersuche: $hit['filename'] und $hit['fileext'] sind leer (#34)

 
Auch hier habe ich gerade noch mal nachgesehen, was in der Datenbank drinsteht und festgestellt, dass das Suchmodul auf die db_column-Treffer reagiert hat (ohne fileext, filename), nicht aber auf die Treffer vom Typ "file", weil etwas in den Indexierungseinstellungen nicht gepasst hat. 

Das Ganze funktioniert ordnungsgemäß und ist einfach ein Konfigurations- und damit ein Doku-Problem.

**Comment by alexplusde** [comment]
Hat jetzt 3,5 Jahre niemand danach gefragt.
