### ISSUE TITLE
SQLSTATE[HY000]: General error

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/search_it#346]
**Description / Beschreibung**

Diese Zeile hat den Fehler ausgelöst und die Suche warf ein Whoops.
https://github.com/FriendsOfREDAXO/search_it/blob/fe7cd68a31c56f7394c90e2c4d5b542f3bc32b7d/lib/search_it.php#L1931

Ich habe dann die Methode so abgeändert

```php

    /* caching */
    /**
     * Returns if a search term is already cached.
     * The cached result will be stored in $this->cachedArray.
     *
     * @param string $_search
     *
     * @return bool
     */
    private function isCached($_search)
    {
        $sql = rex_sql::factory();
        $results = $sql->getArray('SELECT '.$sql->escapeIdentifier('returnarray').' FROM '.$sql->escapeIdentifier(self::getTempTablePrefix().'search_it_cache').' WHERE hash = :hash', ['hash' => $this->cacheHash($_search)]);
        foreach ($results as $value) {
            return false !== ($this->cachedArray = unserialize($value['returnarray']));
        }

        return false;
    }
```

Ob das mit dem Cache jetzt so richtig läuft, müsstet ihr bitte einmal prüfen. Hier funktionierte die Suche erst einmal wieder.

**Comment by tyrant88** [comment]
Irgendein spezielles Setup? Die Funktion wird ja bei jeder Suche aufgerufen, dass müsste soch sonst mehr Leuten passieren.
Wie bist du denn auf deinen Fix gekommen?

**Comment by tbaddade** [comment]
> Irgendein spezielles Setup?

Nein

> Wie bist du denn auf deinen Fix gekommen?

Der Fehler schlug bei `getArray()` und nicht bei der Zeile darüber bei `select('returnarray')` an. 
Ich wollte dann das doppelte Ausführen des Queries vermeiden und siehe da es funktionierte.

**Comment by tyrant88** [comment]
Ach stimmt durch das if wird es doppelt ausgeführt. Das ist mir Grund genug es zu ändern, auch wenn ich den Fehler nicht kapiere. :-)
