### ISSUE TITLE
Aktiviertes Maintenance-Modul

### ISSUE THREAD

**Issue by ritzfritz** [FriendsOfREDAXO/search_it#351]
**Feature description / Feature Beschreibung**
Ein Warnhinweis bei aktiviertem Maintance-Modul wäre super!

**Comment by tyrant88** [comment]
Sorry, aber das sehe ich nicht als Aufgabe von Search it.

**Comment by ritzfritz** [comment]
@tyrant88 
Hatte das Problem halt schon mal vor 3 Monaten und wieder vergessen.
Dann wieder in der Doku gefunden. Heute zum 2. Mal einiger Maßen viel Zeit verbröselt.
Endlich in der Doku von Search_it wiederholt den Hinweis gefunden.
Daher kam mein Gedanke und meine userhafte Idee, dass das vielleicht einfach einzubauen wäre.

**Comment by tyrant88** [comment]
Die Absicht ist schon klar, aber vor anderen AddOns warnen ist keine Vorgehensweise.
Da fände ich es interessanter beim Maintenance die Search It-Aufrufe durchzulassen.
Es könnte den Aufruf auf den URL-Parameter "search_it_build_index" und die eigene IP prüfen.
@skerbis

**Comment by skerbis** [comment]
äh einfach die IP des Servers in die Whitelist von Maintenance setzen? Das gibt's doch schon lange

**Comment by tyrant88** [comment]
Sorry, richtig, Brett vorm Kopf !

**Comment by ritzfritz** [comment]
Danke für die Info meine beiden Besten!
