### ISSUE TITLE
Ähnlichkeitssuche: Verbesserte Vorschläge? / Hunspell?

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/search_it#36]
Wie werden Keywords für die Ähnlichkeitssuche aktuell generiert? Mir kommt es vor, als ob dafür jeder eingegebene Suchbegriff herangezogen wird (, der zumindest einen Treffer gelandet hat). Das führt dazu, dass auch falsch geschriebene Suchbegriffe das darauffolgende Mal verwendet wird und in "Meinten Sie..." vorgeschlagen wird.

Test:
- Suchbegriff "Puddi" findet "Pudding" (Puddi wird in den Index aufgenommen)
- Suchbegriff "Pudde" führt zu "Meinten Sie Puddi"?

So ist die "Meinten Sie..."-Suche ja nicht gedacht. Die Meinten-sie-Vorschläge sollte nur aus Begriffen bestehen, die bei der Indexierung gefunden wurde.

**Comment by alexplusde** [comment]
Hätte ich mal #RTFM gemacht.
https://github.com/tyrant88/search_it/blob/master/plugins/documentation/docs/de_de/howto-simsearch.md

Das ist noch aus der RexSearch-Doku:

>Search it baut anschließend bei jeder Suche, die einen Treffer ergab, einen Schlagwortindex aus. Dabei wird angenommen, dass Wörter, die zu Suchergebnissen führen, richtig geschrieben sind.

> Tipp: Um die Ähnlichkeitssuche effektiv einsetzen zu können, empfiehlt es sich, die Suche selbst mit richtigen Schlagwörtern zu füttern. Dadurch sind erste Suchwörter indexiert und die Ähnlichkeitssuche kann bei einer falschen Schreibweise dieser Wörter diese vorschlagen.

Ist natürlich utopisch, bei größeren Seiten erstmal selbst 1000 Begriffe fehlerfrei einzugeben und zu erwarten, dass nur fehlerfreie Begriffe in den Index kommen - wobei der selbstlernende Ansatz ja gar nicht so schlecht ist.

Um bei dem Beispiel oben zu bleiben: Wenn `Puddi` als Teilwort `Pudding` findet, sollte stattdessen Pudding in den Ähnlichkeits-Index aufgenommen werden. 

Ich werde mal testen, ob der Effekt auch bei MATCH AGAINST eintritt - vielleicht war die Ähnlichkeitssuche nie dafür gedacht, mit dem LIKE-Modus zu arbeiten.

**Comment by alexplusde** [comment]
Idee: Eingabe Optional mit hunspell vorbehandeln. (Man wird ja wohl noch träumen dürfen)

**Comment by tyrant88** [comment]
können wir das mal schließen?

**Comment by alexplusde** [comment]
Das Problem besteht weiterhin, dass Teilwörter in den Index aufgenommen werden und dadurch die Ähnlichkeitssuche mit falschen Wörtern befüllt wird und man Ähnlichkeitssuche + LIKE-Modus nicht gemeinsam verwenden kann.

**Comment by tyrant88** [comment]
Problem besteht, aber stört keinen? ;;;;-)

**Comment by alexplusde** [comment]
Ich kann mir auch heute gut vorstellen, bei der Indexierung einen Keyword-Index mit aufzubauen. Das Problem da oben ist der Grund, dass ich die Ähnlichkeitssuche nicht aktiviere. Denn so ist sie Murks.
