### ISSUE TITLE
Speichern eines YForm Datensatzes, indexiert alle Datensätze 

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/search_it#364]
**Description / Beschreibung**
Beim debuggen für #361 ist mir aufgefallen, dass nach dem Speichern **eines** YForm-Datensatzes **alle** Datensätze der Tabelle indexiert werden.

Würde es nicht ausreichen, nur diesen bearbeiteten Datensatz neu zu indexieren?

**Comment by tyrant88** [comment]
Ja, das ist super. Da ist tasächlich ein Bug drin. Ich bau die IndexColumn()-Methode um. Das könnte ein echter Performance-Gewinn werden.

**Comment by tyrant88** [comment]
@palber war schon mitten dabei, aber danke für das Angebot!!!

**Comment by tyrant88** [comment]
wäre cool wenn du es noch nmal testen kannst

**Comment by tyrant88** [comment]
mist doch noch ein bug

**Comment by palber** [comment]
Habe es nun getestet. Mein Fall scheint ebenfalls behoben zu sein! Danke dir!

**Comment by tyrant88** [comment]
Das freut mich!
