### ISSUE TITLE
Notice iconv(): Detected an illegal character in input string

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/search_it#373]
**Description / Beschreibung**
Die Meldung iconv(): Detected an illegal character in input string erscheint als Notice nach der Umstellung auf PHP 8.2 im Logfile

**Affected versions / Verwendete Versionen**
Version 6.9.8

REDAXO:  5.15.1
PHP: 8.2.7
Database: MariaDB 10.3.38
Browser: alle
AddOns: Ja, schon einige, aber nichts exotisches.

**Did it whoops? / Whoops erhalten?**
Nein, kein whoops, nur eine Zeile im Log.

**What I did to fix it**
Ich habe den fraglichen String mal geloggt:
rex_logger::factory()->log('info',(string) $Apieces[$i],[],__FILE__,__LINE__);
Es war dies ein einzelnes Zeichen oder nichts. Wo es her kam (Article_id oder sowas) konnte ich nicht herausfinden.

GLG, Wolfgang

**Comment by alxndr-w** [comment]
Laut https://github.com/search?q=repo%3AFriendsOfREDAXO%2Fsearch_it+iconv%28%29&type=code verwendet search_it kein iconv() (direkt).

Aus dem Issue wird nicht klar, um was für einen fraglichen String es sich handelt, wo dieser entsteht oder wie dieser mit search_it in Verbindung zu bringen ist. Ich habe auch eine Installation mit PHP 8.2 und kann hier keine Probleme im Log erkennen.
