### ISSUE TITLE
Ausgabemodul für die Suche über URLs aus dem URL Addon (>= Version 2.0) wirft einen error

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/search_it#374]
**Diese Zeile im Ausgabemodul für die Suche über URLs aus dem URL Addon (>= Version 2.0) wirft einen error**

Zeile:
                $url_sql->setWhere(['url_hash' ==> $hit['fid']]);

**ParseError:** syntax error, unexpected token ">"

**Did it whoops? / Whoops erhalten?**
**ParseError:** syntax error, unexpected token ">"

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                                     | Line     |
| -------------------------------------------- | ------------------------------------------------------------------------ | -------- |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content.php      | 123      |
| rex_article_content->getArticle              | rex:///template/1                                                        | 48       |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 456      |
| rex_article_content_base->{closure}          | redaxo/src/core/lib/util/timer.php                                       | 56       |
| rex_timer::measure                           | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 457      |
| rex_article_content_base->getArticleTemplate | redaxo/src/addons/structure/plugins/content/boot.php                     | 58       |
| rex_package::{closure}                       | redaxo/src/core/lib/extension.php                                        | 52       |
| rex_extension::{closure}                     | redaxo/src/core/lib/util/timer.php                                       | 56       |
| rex_timer::measure                           | redaxo/src/core/lib/extension.php                                        | 63       |
| rex_extension::registerPoint                 | redaxo/src/core/frontend.php                                             | 22       |
| require                                      | redaxo/src/core/boot.php                                                 | 155      |
| require                                      | index.php                                                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.15.1, PHP 8.1.22, MariaDB 10.5.19)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.22     |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.5.19 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/116.0 |
|      Protocol | HTTP/2.0      |
|         HTTPS | yes           |

| Packages                          |            |
| --------------------------------: | :--------- |
|                           adminer | 1.9.3      |
|                            backup | 2.9.0      |
|                          be_style | 3.2.0      |
|               be_style/customizer | 3.2.0      |
|                   be_style/redaxo | 3.2.0      |
|                           bloecks | 3.1.1      |
|                  bloecks/cutncopy | 3.1.1      |
|                 bloecks/dragndrop | 3.1.1      |
|                      bme_extended | 1.0b       |
|                   consent_manager | 4.1.3      |
|                           cronjob | 2.10.0     |
|                           cropper | 2.0.2      |
|                        d2u_helper | 1.12.4     |
|                           install | 2.11.1     |
|                            mblock | 3.4.12     |
|                     media_manager | 2.14.0     |
|                         mediapool | 2.13.0     |
|                          metainfo | 2.10.0     |
|                             mform | 7.2.8      |
|                     modulsammlung | 4.15.4     |
|                       multiupload | 2.1.3      |
|                        navbuilder | 1.0.6      |
|                         phpmailer | 2.12.0     |
|                           project | dev        |
|                  quick_navigation | 6.0.2      |
|                         search_it | 6.9.8      |
|           search_it/documentation | 6.9.8      |
|                             sprog | 1.5.1      |
|                         structure | 2.15.0     |
|                 structure/content | 2.15.0     |
|                          tinymce5 | 1.2.17     |
|                          ui_tools | 1.2.2      |
| ui_tools/bootstrap-datetimepicker | 4.17.47    |
|        ui_tools/jquery-minicolors | 2.4.0      |
|                ui_tools/selectize | 0.2.0      |
|                               url | 2.1.0      |
|                             users | 2.10.0     |
|                     xoutputfilter | 3.0.0      |
|       xoutputfilter/documentation | 1.0.0      |
|            xoutputfilter/frontend | 3.0.0      |
|                              ycom | 4.1.0      |
|                         ycom/auth | 4.1.0      |
|                        ycom/group | 4.1.0      |
|                             yform | 4.1.1      |
|                       yform/email | 4.1.1      |
|                     yform/manager | 4.1.1      |
|                        yform/rest | 4.1.1      |
|                          yrewrite | 2.10.0     |

</details>

**Comment by tyrant88** [comment]
Danke, ich hab die Doku korrigiert.
