### ISSUE TITLE
Search_it vs. access denied

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/search_it#383]
Search_it  versucht Artikel die mit accessdenied gesperrt wurden zu indexieren. Das wirft Fehler im Log. (404). 
Ich denke es liegt an der Vererbung der Rechte von accessdenied. 
Könnte access denied eine Info vorab an search_it übergeben diesen Artikel zu überspringen?

Beispiel: https://github.com/FriendsOfREDAXO/accessdenied/blob/133d97e317498b1eb46cdb4ef1a5126860e50d41/boot.php#L23

**Comment by tyrant88** [comment]
Ich nehme mal an, du hast "Indexiere offline Artikel" angehakt?
Und access_denied setzt den Status auf "2"?

**Comment by skerbis** [comment]
Nein. Offline Artikel werden nicht indexiert und die mit Status 2 auch nicht. Accessdenied hat aber eine Vererbung auf Unterkategorien (Siehe Beispiel oben) dort wird der Status nicht verändert. Somit versucht search_it diese zu indexieren?

**Comment by tyrant88** [comment]
Ah, okay. Puh, das macht die Sache schwierig. Da muss ich noch mal überlegen...

Bisher habe ich als Problem gefunden:
Im Moment wird nur geprüft, ob eventuell die Option "indexoffline" gesetzt ist. Das könnte ich erweitern zu ("indexoffline" UND status == 0). Also "nur wenn old school offline"...

**Comment by skerbis** [comment]
Wo findet der check beim indexieren statt? ... würde mir das gerne mal anschauen. Vielleicht finden wir gemeinsam eine Lösung.

**Comment by tyrant88** [comment]
Nun ja...
unmittelbar... hier:
https://github.com/FriendsOfREDAXO/search_it/blob/master/lib/search_it.php#L258

**Comment by skerbis** [comment]
ok. Dann wäre dort bzw davor ein EP ganz gut wo das Access-Denied vielleicht reingrätschen kann und im IF dann eine weitere Bedingung reinmogeln könnte für den aktuellen Artikel. ?

**Comment by tyrant88** [comment]
Das wäre eine Idee.

**Comment by skerbis** [comment]
Mache ich fertig

**Comment by skerbis** [comment]
So könnten auch andere AddOns darauf Einfluss nehmen :-)

**Comment by tyrant88** [comment]
Ja, sonst fände ich die Idee auch nicht gut.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/search_it/pull/384

**Comment by skerbis** [comment]
Merged in: https://github.com/FriendsOfREDAXO/search_it/pull/384
Danke @tyrant88

**Comment by tyrant88** [comment]
So bald ich Zeit habe mach ich auch ein release

**Comment by skerbis** [comment]
👍🏻
