### ISSUE TITLE
Es sind keine Datenbankspalten selektiert und dennoch wird indexiert

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/search_it#56]
Eventuell die Datenbankspalten vorselektieren. Wenn welche Spalten markiert sind, das entsprechende Accordion initial geöffnet anzeigen.

**Comment by tyrant88** [comment]
Die Datenbankspalten sind ja nur optional. Also welche sollte man vorselektieren? 
Eigentlich sollten alle Accodions geöffnet sein, die markierte Checkboxen enthalten... Das ging bis neulich noch.

**Comment by tbaddade** [comment]
> Die Datenbankspalten sind ja nur optional

Ok, ich dachte das zumindest die Tabellen `rex_article` und `rex_article_slice` mit den sinnvollen Spalten vorselektiert sein sollten. 

Das mit den geöffneten Accordions funktioniert tatsächlich.

**Comment by tyrant88** [comment]
Bei Artikeln ( und Slices ) machen ja nur Metadaten Sinn, die nicht im Inhalt vorkommen. Aber welche das sind ist doch wirklich von Projekt zu Projekt verschieden. Auch die Datumsangaben machen wenig Sinn.
Also ich sehe nach wie vor keine allgemeingültige ( oder zumindest für eine Mehrheit sinnvolle) Voreinstellung.

**Comment by tbaddade** [comment]
Ich meinte diese Spalten: `article.name`, `article.catname`, `slice.valueN` etc.
Das hatte mich schon bei RexSearch gewundert. Es wird etwas indexiert obwohl keine Spalten selektiert sind. Wenn die Artikel generell indexiert werden, dann könnte man diese Tabellen eher nicht zur Auswahl stellen.

**Comment by tyrant88** [comment]
Ja ich glaube da liegt ein grundsätzliches Missverständnis vor. Die Hauptaufgabe von Search it ist, die Website-Inhalte durchsuchbar zu machen, soll heißen die Infos, die im Sichtbaren liegen. D.h. die Informationen, dei der Websitebetreiber verfügbar machen will. Wenn im Template nicht der REDAXO-Artikel-Titel auftaucht, muss ich davon ausgehen, der soll nicht öffentlich sein. 
Genauso `catname` - wenn es nicht sichtbar ist, warum sollte man danach suchen können?
'slice.ValueN' ist in diesem Sinne ja ganz falsch, da das eh dargestellt wird, wenn es ein Textfeld ist und umgekehrt wenn es ein "soll der Block eingerückt werden?"-Selectfeld ist, was will ich denn mit dem Wert???

Und jetzt, für genau den Fall, dass dir ein Feld einfällt in deinem Projekt, in dem das trotz meines Geseiers Sinn macht, kannst du das Häkchen setzen. Toll oder? :-)

**Comment by tyrant88** [comment]
Ich werde den Einstellungspunk von "Quelle" in "Zusätzliche Datenquellen" umbenennen, vielleicht hilft das auch es klarer zu machen

**Comment by alexplusde** [comment]
Ich weiß auch noch, dass ich am Anfang nicht verstanden habe, warum bspw. der Artikelname nicht mit indiziert wird. die Frage wird auf jeden Fall immer wieder aufkommen, man sollte sie daher in der Doku protokollieren und beantworten. Bitte Issue offen lassen.

**Comment by tyrant88** [comment]
EIn Bisschen Text hab ich eingebaut, aber wir brauchen einen Text wie man vorgeht:
-Was soll durchsuchbar sein? (Artikel, Metainfos, Dateien) -> Passende Häkchen setzen (oder view bauen ;-)
 Mit Template oder ohne? Per HTTP oder aus dem Cache?
-Wie soll es ausgegeben werden? ->Passende Häkchen setzen + passendes Modul auswählen
Und klar machen, dass verschiedene Module an verschiedenen Stellen verschiedene Ausgaben machen können.

**Comment by alexplusde** [comment]
okay. Ist auf meiner Todo-Liste :)
