### ISSUE TITLE
Suggest Funktion / Autocomplete

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/search_it#60]
Hi, eben im Forum gesehen, vielleicht wäre es schön, was ähnliches in der Doku oder Beispielmodulen für R5 search_it mit anzubieten?
http://www.redaxo.org/de/forum/post119187.html#p119187

**Comment by alexplusde** [comment]
Ich frag mal den Autor des Forum-Beitrags, ob er Zeit hat, das Beispiel an R5 anzupassen. 





Oh Mist, das bin ja ich.

Wäre auf jeden Fall sinnvoll, wobei ich mir nicht sicher bin, ob der gewählte Ansatz mit JQueryUI zeitgemäß ist. Von der Performance war die Lösung auch nicht sonderlich schön - und sie zerhaut einem die Ähnlichkeitssuche, weil jeder eingegebene Buchstabe mehr ein neues Wort erzeugt.

**Comment by alexplusde** [comment]
https://github.com/tyrant88/search_it/issues/61

**Comment by alexplusde** [comment]
Memo: https://github.com/twitter/typeahead.js

**Comment by rkemmere** [comment]
Wir haben es als Plugin adaptiert.

https://github.com/FriendsOfREDAXO/search_it/issues/144

**Comment by alexplusde** [comment]
@rkemmere toll :) Danke!

**Comment by alexplusde** [comment]
@tyrant88 mergen, testen und releasen? mergen, als beta releasen und auf Feedback warten?

**Comment by tyrant88** [comment]
Ich hab es gestern nur mal installiert, würde mir gerne noch ne Meinung bilden. Eigenes Template und Modul erhöht irgendwie die Komplexität. 
Es nutzt eine eigene colognephone Funktion...
Aber ich bin auch nicht das Maß der Dinge.

**Comment by rkemmere** [comment]
Hi, 

die Lösung über die Template und Modul Kombination macht es für uns einfach flexibler. Wir haben es bei drei Projekten im Einsatz und es war so einfach die beste Variante. Des Weiteren werden die Module und das Template bereits mitinstalliert. 

Wir bräuchten die Möglichkeit eine Datei zu benutzen welche uns den Redaxo Context anbietet. So dass wir die Search aufrufen können und auch SQL Abfragen absenden können. 

Im 4er Plugin war das über den Include der Master.inc gelöst, was wir aber nicht für richtig halten.


Bzgl. der colognephone Funktion. Diese haben wir auch aus der rexseach von redaxo 4 übernommen.

Habe aber gerade gesehen, dass eigentlich aktuell in der Suche bei der Kölner Methode die soundex_ger verwendet wird.

>  - Methode cologne_phon() durch soundex_ger() ersetzt (wegen Lizenz, jetzt BSD)

**Comment by alexplusde** [comment]
Ich bin auch noch unschlüssig, statt des `Suchhandle-Artikels` wäre ein API-Call doch die saubere Variante, oder?

Also ich finde es wirklich toll, dass du dich darum gekümmert hast, vielleicht können wir hier in der Community noch den letzten Feinschliff machen, das würde mich wirklich freuen.

**Comment by rkemmere** [comment]
Wenn ihr uns einen Anstoß gebt, wie wir aus dem Frontend einen API Call starten und diesen dann aus dem Frontend per JS Aufrufen können. Setzen wir das um.

**Comment by alexplusde** [comment]
Aber sicher! @rkemmere https://github.com/FriendsOfREDAXO/tricks/blob/master/howto_ajax_rexapi.md
