### ISSUE TITLE
Doku: Verzeichnistiefe und Objekt-Optionen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/search_it#62]
Memo an mich:

- Verzeichnistiefe = Tiefe im Medienpool, nicht in der Ordnerwahl.

- Suche nur in DB ohne Artikel, vice versa: Für die Beispiele
```
	$rexsearch_article = new RexSearch(REX_CLANG_ID);
	$rexsearch_article->setLimit(array($offset, $max));
	$rexsearch_article->doSearchArticles(true);
	$rexsearch_article->searchInDbColumn('rex_article', 'name');
	$rexsearch_article->searchInDbColumn('rex_article', 'seo_description');
	$rexsearch_article->searchInDbColumn('rex_article', 'seo_keywords');
	$rexsearch_article->searchInFileCategories(false);
	$results['rex_article'] = $rexsearch_article->search(rex_request('search', 'string', ''));
```

**Comment by tyrant88** [comment]
Findest du keine andere Stelle für Memos als meine möchte-ich-leer-haben issue Liste?

Zum Inhalt:
> "Verzeichnistiefe = Tiefe im Medienpool, nicht in der Ordnerwahl."  
Natürlich ist die Ordnerauswahltiefe gemeint!

bitte `setSearchAllArticlesAnyway`anstelle von `doSearchArticles`verwenden. Und wenn du nur in der DB suchen willst, solltest du es auf false setzen...

und bitte keine Variablen mit `$rexsearch_` mehr...

**Comment by alexplusde** [comment]
Hach, damals, als die Repo nocht nicht auf FOR lag und alles noch nicht so eng gesehen wurde ;)

Ich schau zu, dass ich die Issues zeitnah bearbeite. Allerdings finde ich Doku-Issues schon auch wichtig und richtig, sie sind ja mir zugewiesen. Filter meine Issues doch weg :P

**Comment by tyrant88** [comment]
Alles jut, du darfst das natürlich prinzipiell!

**Comment by alexplusde** [comment]
`setSearchAllArticlesAnyway(false)` durchsucht aber weiterhin Medienpool-Dateien, oder?
