### ISSUE TITLE
Maximale Trefferanzahl prüfen

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/search_it#76]
Es wäre ganz hilfreich, wenn der Wert für "Maximale Trefferanzahl" auf Plausibilität geprüft würde, da ein Wert von 0 alle Treffer verhindert. Bei leerem Feld oder einer nicht bemerkten Fehleingabe wird das Feld als 0 gewertet.

**Comment by tyrant88** [comment]
Jut. Nicht numerische Eingaben und 0 werden jetzt nicht gespeichert.
Und das leere Feld führt dann zu sinnvollen Vorgaben.

thanks FOR verbessering search it.
