### ISSUE TITLE
Der Search-Highlighter zeichnet auch im <title> Tag aus

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/search_it#77]
Hier müsste wohl auf den body begrenzt werden?

**Comment by alexplusde** [comment]
Sollte eigentlich auch laut https://github.com/FriendsOfREDAXO/search_it/issues/32

**Comment by tyrant88** [comment]
Sorry, Anfängerfehler. Jetzt mit regex besser und richtiger.

thanks FOR verbessering search it
