### ISSUE TITLE
Feature: Im Backend die Suche testen

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/search_it#78]
Hi,

aktuell muss man zwingend ein Modul im Frontend installieren, um seine Sucheinstellungen zu testen. Ich würde mir eine "Spielwiese" im Form eines Widgets oder einer Addon-Page wünschen, um schnell mal den Output der Suche zu testen. Einfach nen kleiner Default-Output und ein print_r($hits) oder Ähnliches.

**Comment by alexplusde** [comment]
Finde ich eine gute Idee.

Allerdings ist print_r je nach Abfrage schon ein Overkill, das müsste man evtl. noch mit einem toggle kaschieren können.

**Comment by Hirbod** [comment]
Hoch lebe 
```php 
dump(); 
```

**Comment by alexplusde** [comment]
Bin auch gerade schwer begeistert davon.
Dann könnte man die Muster-Module soweit anpassen, dass überall dump(); vorgeschlagen wird.

**Comment by alexplusde** [comment]
@Hirbod kannst du möglicherweise direkt einen dazu einen PR machen? Ich würde da einen neuen Reiter / neue Unterseite namens "Debug" dazu vorschlagen, wo vielleicht auf gleichem Wege die Konfiguration ausgegeben wird.

**Comment by Hirbod** [comment]
Kann ich demnächst gerne machen. Muss zuerst aber noch meine eigenen Baustellen (AddOns) eigentlich vorher abschließen

**Comment by alexplusde** [comment]
Muster-Module habe ich mal angepasst. Über eine separate Seite im Addon-Backend würde ich mich nach wie vor freuen.

**Comment by alexplusde** [comment]
Halbes Jahr später: Kann jetzt selbständig Backend-Seiten anlegen ;) Wenn ihr wollt, dann bitte anschauen und testen :)
