### ISSUE TITLE
Per default: Artikelname beachten

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/search_it#79]
In der Default-Einstellung wird der Artikelname nicht indiziert. Man müsste es als zusätzliche DB-Quelle unter rex_article.name mit angeben. Es wird dann aber dennoch nicht im hit-type "article" aufgeführt, sondern müsste gesondert innerhalb von $hit-type "db-column" abgefrühstückt werden.

Ich finde, der Artikel-Name gehört explizit zum type "article"

**Comment by alexplusde** [comment]
Sofern der Artikelname auf der Seite ausgegeben wird, landet er automatisch im Index. Darauf bezieht sich auch der Treffertyp `article`. Ich meine, es gibt immer die Möglichkeit, die Abfrage zu kombinieren, in etwa: `if($hit['type'] == 'article' || $hit['type'] == 'db-column')` (<- nur das Prinzip, bitte nicht 1:1 übernehmen) 

Das Thema wurde und wird immer wieder diskutiert, weil es nicht ganz intuitiv ist. Ist aber das Prinzip der Volltextsuche.

**Comment by Hirbod** [comment]
So in der Art hab ich es auch gelöst :). Ist jetzt nicht super umständlich, die Beispiele sollten es vllt beinhalten

**Comment by alexplusde** [comment]
Wäre es für dich ok, das Issue damit zu schließen?
