### ISSUE TITLE
Bug beim Speichern eines Artikels

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/search_it#80]
Zuerst dachte ich, es wäre ein REDAXO 5.3 Problem, jedoch verursacht dieses AddOn das Problem.

https://github.com/redaxo/redaxo/issues/1023

Hier noch mal der Text dazu. Diesen Code in die Modulausgabe:

```php
<?php echo rex_article::getCurrent()->getId(); ?>
```

<img width="1048" alt="bildschirmfoto 2017-02-12 um 06 51 12" src="https://cloud.githubusercontent.com/assets/504909/22859984/db6de1c0-f0ef-11e6-924b-6317473dc8b8.png">

Das Modul kann sogar "übernommen werden", klicke ich aber auf "speichern", kommt besagte Fehlermeldung von oben. Der Artikel wird trotzdem gespeichert und die Ausgabe im Frontend klappt trotzdem. Dennoch whoops es mir dazwischen, wenn ich speichere.

<img width="1049" alt="bildschirmfoto 2017-02-12 um 06 53 40" src="https://cloud.githubusercontent.com/assets/504909/22859990/077e96ba-f0f0-11e6-9125-744e1160485c.png">

**Comment by Hirbod** [comment]
Bei deaktiviertem AddOn kein Problem.

**Comment by gharlan** [comment]
Ist bereits gefixt, auch wenn es die Commit Message einem eher nicht verrät.. ;)
https://github.com/FriendsOfREDAXO/search_it/commit/384a4b1824c619acf0af6fe5cea869abcbc22e20

Das Problem tritt übrigens auf, wenn ein Artikel mit der ID 1 nicht mehr existiert. Aber auch ansonsten wäre die Artikel-ID dann falsch (halt 1), bloß würde nicht der Fehler erscheinen.

**Comment by alexplusde** [comment]
Da's gefixt sei, mach ich's zu.

**Comment by Hirbod** [comment]
vllt nur mal flott ne fixed version bereitstellen ;)
