### ISSUE TITLE
Artikel (ADD, EDIT, DELETE) automatisch (de)indexieren verlangsamt das CMS

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/search_it#84]
Die Einstellung "Artikel (ADD, EDIT, DELETE) automatisch (de)indexieren"
verlangsamt das CMS merklich beim (direkten) Aufruf eines Artikels im Backend. Was ja auch logisch ist, da hier der komplette Suchcache geleert und neu aufgebaut wird. Bei Artikeln mit mehren Slices kann es schon (je nach Server Config) auch mal mehr als 5 Sek dauern, bis der Artikel wieder editierbar ist...
Könnte das nicht iwie im Hintergrund ablaufen und nicht im direkten Aufruf des Backends?
Liegts evtl doch "nur" am Server.

Danke.

**Comment by tbaddade** [comment]
Vermutlich liegt es am EP "SLICE_SHOW". Das zumindest war der Hauptgrund bei Rexsearch. Lag aber auch daran, dass die EPs SLICE_ADD, EDIT, DELETE nicht gab.

@darwin26 nimm mal den EP `SLICE_SHOW`aus der `boot.php`

**Comment by tbaddade** [comment]
[Diese Zeile](https://github.com/FriendsOfREDAXO/search_it/blob/master/boot.php#L57) einfach in Kommentar setzen und testen.

**Comment by darwin26** [comment]
SLICE_SHOWaus der boot.php entfernt (auskommentiert).
Ja... jetzt performance deutlisch besser.

Danke @tbaddade

**Comment by alexplusde** [comment]
d.h. die Zeile kann raus, ohne dass es Probleme gibt bei der (De-/Re-)Indexierung?

**Comment by darwin26** [comment]
yep. habs in der DB überprüft (rex_search_it_index), es wird "nur noch" beim Add/Edit reIndexiert... beim SHOW zu re-indexen wäre ja auch nicht sinnvoll. Es reicht ja wenn Add/Edit eines Slices das Indexieren angeschubbst werden.

Danke

**Comment by tbaddade** [comment]
> d.h. die Zeile kann raus, ohne dass es Probleme gibt bei der (De-/Re-)Indexierung?

@alexplusde das weißt du oder @tyrant88 am besten. Falls dadurch irgendein indexieren nicht gestartet wird, würde die Zeile bei jedem Projekt dennoch löschen und ggf. den Index eher via Cronjob oder manuell starten lassen.

**Comment by tyrant88** [comment]
Ich prüfe es noch mal - irgendeinen Grund werde ich hoffenltich gehabt haben das zu übernehmen...

**Comment by tyrant88** [comment]
@tbaddade hat Recht, früher gab es die extension points SLICE_UPDATED, etc nicht, deshalb hatte Xong das mit SLICE_SHOW versucht.
Ich hatte es aber auch schon deaktiviert, wie man [hier sieht](https://github.com/FriendsOfREDAXO/search_it/blob/master/functions/functions_search_it.php#L290-L295) wollte dann später entscheiden.
Jetzt ist es soweit, denke ich. Fliegt raus.

Und wie @tbaddade denke ich auch, wenn Redakteure wirklich oft Artikel ändern, sollte man eher einen cronjob nehmen.

**Comment by darwin26** [comment]
wunderbar. danke ... 👍
