### ISSUE TITLE
Dateien indizieren: /media/-Dateien indexieren

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/search_it#92]
Wenn ich nur die checkbox **/media/-Dateien indexieren** aktiviere, können die Files (meist PDF) nicht indiziert werden. 
Wähle ich aber den Medienordner unter -**Zusätzliche Datenquellen** - aus, werden die PDF indiziert.

**Comment by tyrant88** [comment]
Alex hat das umbenannt, das hieß früher "Medienpool indexieren".  Deshalb nur meine Nachfrage: sind die Dateien auch im Medienpool?

**Comment by skerbis** [comment]
Ja sie sind im Medienpolitik

**Comment by alexplusde** [comment]
Mir war der Zusammenhang zwischen den Einstellungen schon bei RexSearch etwas suspekt, denn es gibt ja verschiedene Szenarien:

* Nur Dateien, die sich im /media/-Ordner befinden
* Nur Dateien, die sich im /media/-Ordner befinden UND im Redaxo-Medienpool (rex_media) indexiert sind
* Dateien, die sich außerhalb des /media/-Ordner befinden.

Von außen ist nicht klar, welche Einstellung da zu welchem Verhalten führt, weil die Einstellungen ja z.T. redundant sind (bspw: "ich indexiere das /media/-Verzeichnis, aber, nicht den Medienpool - was passiert dann?")

In meinen Augen müsste man die Einstellungen und ggf. das Indexierungsverhalten von `Search it` da nochmal neu denken und an die Erwartungen der Nutzer anpassen.

**Comment by skerbis** [comment]
kurz noch mal ... wenn die Checkbox aktiviert ist, geht der zwar die Mediendateien durch, aber er kann sie nicht indexieren.  Eine Auswahl Medienpool gibt es doch nicht - oder?

**Mit Checkbock:**
![bildschirmfoto 2017-03-17 um 14 33 27](https://cloud.githubusercontent.com/assets/791247/24045254/b43d180c-0b1e-11e7-93dd-d26588b23c42.png)

**Ohne Checkbox aber Ordner /media/ ausgewählt**
![bildschirmfoto 2017-03-17 um 14 35 19](https://cloud.githubusercontent.com/assets/791247/24045328/f74faa2e-0b1e-11e7-972c-7f7ab5689887.png)
:

**Comment by alexplusde** [comment]
@skerbis https://github.com/FriendsOfREDAXO/search_it/issues/57 ?

**Comment by skerbis** [comment]
@alexplusde wie du gut erkennen kannst werden die pdf im 2. Schirm indexiert. bei /media/-Dateien indexieren muss was anders sein. Finde aber auch keinen Fehler in den Logs.

**Comment by skerbis** [comment]
Bekomme aber ständig Notices:  Array to string conversion, redaxo/src/addons/search_it/pages/settings.addsources.php - Zeile 40 
....

**Comment by tyrant88** [comment]
Ich schau es mir an sobald ich kann.

**Comment by tyrant88** [comment]
So, ist gefixed... 
Sowohl das Problem wie auch die Notices.
Der Dateipfad stimmte nicht, wenn der Index schrittweise erstellt wurde...
thx again an @skerbis "Power User"
Ich mach heute noch ein Release...
