### ISSUE TITLE
Benutzung von rex::isBackend kann Fehler erzeugen

### ISSUE THREAD

**Issue by Web-Work24** [FriendsOfREDAXO/search_it#93]
Sobald das AddOn aktiviert ist wird beim speichern eines Moduls in der Struktur bei allen modulen rex::isBackend ausser Kraft gesetzt was uns beim laden der Google API jedesmal einen Fehler bringt.
Einfach ein Modul erstellen bei welchem in der Ausgabe eine Klasse geladen wird z.B.
` if (!rex::isBackend()) {  //Laden der Klasse } `
Dieses Modul kann bei aktivierten search_it nicht einmal in die Struktur eingebunden werden ohne Fehler.

**Comment by Hirbod** [comment]
Ich bemerke es jetzt auch bei mir. Ich hab bisschen durch den Code geschaut, noch konnte ich den Fehler nicht finden.

**Comment by tyrant88** [comment]
Das bei Search it beim Speichern etwas passiert, liegt an der Einstellung "Artikel (ADD, EDIT, DELETE) automatisch (de)indexieren". 

Wenn Search it etwas indexiert, dann immer das, was im Frontend zu sehen ist. 
Die Indexierung wird aber immer im Backend angestoßen. 
Also muss ich `rex::isBackend()` auf false setzen und die Inhalte holen. Das ist Prinzip bedingt.
Und deshalb wird dann bei dir das `include xy.php` im Backend ausgeführt, was dann durch seinen Inhalt zu einem Fehler führt.

Es gibt auch ein weiteres Themenfeld, das Probleme bereitet, nämlich YCom. Deshalb ist mir schon klar, dass Verbesserungspotential besteht, aber das ist nicht trivial.

**Comment by tbaddade** [comment]
> Also muss ich rex::isBackend() auf false setzen und die Inhalte holen. Das ist Prinzip bedingt.

Kannst du das genauer erklären!

**Comment by tyrant88** [comment]
Gerne ;-)
Ich gebe dem Indexierungsmechanismaus den Artikel-Inhalt mit `$rex_article->getArticle()`, weil ich möchte, dass die sichtbaren Informationen in den Index wandern. Ohne Template.
Es besteht die Chance (es gab auch jemanden), dass in den Modulen `if ( rex::isBackend() ) ` verwendet wird. Werden dort Ausgaben gemacht, gehören die nicht in den Index.
(Oder man stelle sich den umgekehrten Fall vor: der Anwender möchte sein include nur im Backend machen, dann hätten wir dieselbe Unterhaltung -bzw hatte ich ja)

Die Methode bei der über HTTP indexiert wird bietet (noch) keine Möglichkeit nur die Inhalte zu indexieren. Aber ich hatte gestern schon mal kurz mit @gharlan geschnackt, denn man sieht ja: es muss prinzipiell irgendwie anders gelöst werden.

**Comment by olien** [comment]
Nur so nebenbei bemerkt: ```if ( rex::isBackend() )```habe ich glaube ich in jedem modul...

**Comment by tyrant88** [comment]
Ich auch :-)

**Comment by skerbis** [comment]
Ich auch

**Comment by tyrant88** [comment]
So:
Der "Frontend Mode" ist Geschichte. Jetzt sollten alle Verrücktheiten die man in Template und Modulen machen kann, keine Probleme mehr bei der normalen Indexierung über die Artikel-Inhalte bereiten.
Ich habe den Algorithmus für die Indexierung komplett geändert. 
@alexplusde Da kommt Doku-Arbeit auf uns zu

**Comment by skerbis** [comment]
Wird es Änderungen seitens der Ausgabe-Module geben (müssen)?

**Comment by tyrant88** [comment]
Nein. Muss nichts geändert werden.
Man aber kann jetzt im Template noch zusätzlich Bereiche markieren, die außer den reinen Artikel-Inhalten indexiert werden sollen.
Wie das geht, muss noch in die Doku...

**Comment by alexplusde** [comment]
Dann sollten wir demnächst wieder skypen :) @tyrant88
