### ISSUE TITLE
Probleme mit Artikel-Markierung <!-- search_it [ID] --> ... <!-- /search_it [ID] -->

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/search_it#98]
Wenn man in einem Artikel über ein Template mit
`rex_response::sendContentType('application/xml; charset=utf-8');`
`print $this->getArticle(1);`
einen RSS-Feed generieren lässt, verändert die Search_it-Markierung `<!-- search_it [ID] -->` ... `<!-- /search_it [ID] -->` die XML-Formatierung des Feed-Headers in der Weise, dass dieser nicht mehr valide ist.
Es kommt bei der Ausgabe des Feeds zu der Fehlermeldung: 

> XML-Verarbeitungsfehler: XML- oder Text-Deklaration nicht am Beginn der Entität Adresse: http://.../rss/ Zeile Nr. 1, Spalte 22:<?xml version="1.0"?> ---------------------^

Siehe zur Feed-Generierung:
https://github.com/FriendsOfREDAXO/tricks/blob/master/modul_minibeispiel_rss-feed.md

Es wäre daher begrüßenswert, wenn man z.B. in der **_Blacklist_** für ausgeschlossene Artikel auch wählen könnte, dass der entsprechende Tag nicht gesetzt werden soll.

**Comment by alexplusde** [comment]
D.h. du hast den betroffenen Artikel in der Blacklist und dieser wird trotzdem verändert?

**Comment by tyrant88** [comment]
Ah, was ein Kampf.
Jetzt hab ich endgültig alle Indexierungsmodi rausgeschmissen, damit ALLES funktioniert was die Leute so treiben im Frontend.

New Version im Installer.

thx @greatif

**Comment by tyrant88** [comment]
stimmt das mit dem Blacllisting muss ich noch schauen...

**Comment by tyrant88** [comment]
Bei mir funzt es. Ich denke du hast nur vergessen, den Suchindex neu zu generieren.
